### ISSUE TITLE
User Acceptance Testing Round 1

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10176]
Listed below are pages that needs to be rigorously tested from an end user POV. It is split by the different users of the system and their respective pages ~on the top nav bar~.

1. Student
   - Home ✅ 
   - Profile ✅ 
   - Help ✅ 
   - View Team  ✅
   - Submission (after login) 🚧 
   - Submission (not logged in, using regkey) 🚧 
   - Session View Results 🚧
   - Join Course
2. Instructor
   - Home✅
   - Submission 🚧 
   - Courses ✅
   - Course Enroll Students ✅
   - View Course Details (Home > Students > View/Edit) ✅
   - Edit Course Details (Home > Instructors > View/Edit or Home > Course > View/Edit) ✅
   - View Student Details ✅
   - Edit Student Details ✅
   - Sessions Add/Edit/Delete 🚧 
   - Sessions View Results 🚧 
   - Search ✅
   - Student List ✅
   - Student Records ✅
   - Join Course
   - Help ✅
3. Admin ✅
    - Home ✅
    - Search ✅
    - Sessions ✅
    - Timezone Listing ✅
4. Landing Page ✅ 
    - Home ✅ 
    - Features ✅ 
    - About ✅ 
    - Contact ✅ 
    - Terms ✅ 
    - Help ✅ 
    - Account Request ✅
    - Usermap ✅
    - Session Links Recovery ✅
    - Sitewide Bottom Banner ✅

**Comment by ccyccyccy** [comment]
Testing Instructor Sessions Add/Edit/Delete

**Comment by ccyccyccy** [comment]
@xpdavid @wkurniawan07 Is this thread for bug reports and missing features, or UI/UX issues as well?

**Comment by t-cheepeng** [comment]
Testing Instructor: Courses page

**Comment by ccyccyccy** [comment]
# Session add/edit

- Missing from V6
    - Missing common visibility (Essay, MCQ, MSQ, Distribute points (among options), Rank (options) question)
    - Missing common feedback paths (Distribute points (among recipients) question)
    - Remind particular student feature missing
    - Feedback path should be disabled if there is only 1 possible path. E.g. Team contribution question
- MCQ: Trying to delete after drag to reorder is buggy
- Distribute points (among options) and MSQ drag to reorder not as smooth as the MCQ's one. Boxes are draggable even when editing is disabled
- MSQ checkboxes should not be unchecked after toggling generate options
- Rich text editor behaving weirdly
- Numerical Scale Question default values shows error? Seems like error checking has issues

# Instructor Result page

- Missing from V6
    - Edit feedback session detail button beside "Session:"
    - "Non-english not showing correctly" help option missing. Not sure if still needed?
    - No response behavior different (V7 shows result with no response, V6 omits them)

**Comment by wkurniawan07** [comment]
On instructor help page:

- Finding students > How do I search for students in my course > 2nd and 3rd example boxes > the view/edit/all records buttons are active.
- Managing session responses > How do I view the results of my session > 2nd example box > "Remind all" collapses the modal when clicked. Might be the problem of the actual component also.

**Comment by madanalogy** [comment]
I'll focus on the student submission and result pages

**Comment by Derek-Hardy** [comment]
I will start with `Admin` pages.

**Comment by t-cheepeng** [comment]
## Landing Page
- Video tour probably has to be updated to reflect new UI in V7
- Dead link under `Well Received by the Academic Community: CSEET`
- Features images has to be updated as well

## Instructor Course Page
- Deleting all students from the course in the view course details page does not refresh the table but the number in the top info box changes. Same goes for deleting a single student from the table
- Course page table should not show when instructors has no courses available to him. Currently, the headers are shown
- Edit course details allows users to click on the Give different permissions for a specific section infinitely
- In view course details page, the non-english characters not displayed properly does not change cursor to pointer when hovering above it
- In edit course details page, labels for checkboxes are not clickable, only the checkboxes are

## Student Profile Page
- Upload photo popup, the left/up arrows are not intuitive. Did not know they reflected the image. Would be great if a tooltip/label was added
- Upload photo popup does not mention about the max size limit of 5MB
- Upload/Edit photo and Delete photo button should be in a row, not stacked
- Save changes popup button order should be reversed. Cancel should be on the left
- Radio button labels for gender is not aligned

## Student View Team Page
- V6 allows students to mail to instructor and other students. V7 view team page is missing that feature

**Comment by Derek-Hardy** [comment]
### Admin Home Page:
* Add instructor action is a 2-step workflow (stage, add) in v7. All buttons are named similar as "Add Instructor", which might confuse user about the workflow.

* After staging the instructor, in Result -> Action, "Add Instructor" and "Cancel" have no separation and are not aligned vertically in length in mobile screen.

* After staging the instructor, in v6, Message has horizontal scroll in mobile screen. In v7, long message populates the entry vertically, leaving large empty space.

### Admin Search Page:
* "Search" button is expected to be blue (active), but is currently grey (inactive).

* In a new keyword search, when no result is found, previous search result is still present. (In v6, no result is shown)

* Missing key word highlight in the results found.

* No header widget to indicate that single result entry can be expanded.

* Click “Google ID”, “Manage this account”, “Reset Google ID” will expand the result entry before redirection (should stop event propagation)

* In v6, all redirections (“Google ID”, “Manage this account”, “Reset Google ID”) are handled by opening in a new tab. In v7, redirection happens in the current page. When going back, no result is cached. (Suggest to follow v6 style)

* The “send mail” button on each link in v6 is missing in expanded result entry.

* Reset Google ID option should have a warning pop-up, like “Regenerate links” does.

* When input ` . ` or `-` as the search input, no result is found in v6, but everything is returned in v7.

### Admin Session Page:
* Missing “Currently no ongoing session” tab from v6, leaving large white space.

* Filter panel should change to vertical mode starting from larger screen, prevent date and Time Zone input from being hidden by input box.

* Separators near “To” and “Time Zone” persist in vertical mode.

* "Filter by Range" button did not provide any feedback when no result is found. (V6 shows “Currently no ongoing session”)

* No text explanation for number in result panel header. (which reports number of results found)

* No widget indication that panels are collapsable. (However, onHover is present)

* Click on creator link should open in new tab, since the current result is not cached when going back.

**Comment by Derek-Hardy** [comment]
### Instructor Home Page:
* Missing “New to TEAMMATES” welcome tab.

* “students”, “instructors”, “sessions”, “course” buttons in the header have no vertical separation & inconsistent alignment in middle-sized screen.

* Add new course -> missing “Active courses” header, user might not know what is listed under the creation tab.

* Add new course -> input headers in add new course tab is right aligned in mobile screen. It should be left aligned.

* Add new course -> active courses entry goes outside mobile screen.

### Instructor Search Page:
* we should either cache search results when going back or open actions in new tab.

* Some action button -> Go back -> page will return to previous search.

* For invalid inputs like . or -, No results found is shown in v6, but server error banner is shown in v7.

**Comment by madanalogy** [comment]
### Submission (after login)
- Main details displays badly on mobile, might be fixed by ##10186
- V7: Essay submission box does not indicate where the user should click to type input. This is very misleading and might make the student believe there is a problem when there isn't. V6: Essay submission box is clearly defined for the user.
- Multiple choice (single answer & multiple answer) comment prompt doesn't indicate/imply that the comment is optional (v6 does indicate this).
- MCQ single answer displays badly on mobile, might link to #10042 
- Rank options question displays badly on mobile, might link to #10042 
### Submission (not logged in, using regkey)
Note that this is not allowed in v6 (or so it appears from my testing) i.e. all submissions require the user be logged in via google account. See second point below.
- v7 does not prompt user when logged in and accessing a link meant for another user (i.e. A & B both in course, logged in as A, accessing email link meant for B). V6 prompts user to associate session with a google account.
- Using regkey alone in incognito mode allows direct access to feedback submission in v7, but doing the same prompts for login in v6.
### Session View Results
- No error handling for non google account logged in student when accessing results from link (server error, no option for resolution) v6 prompts you to login via google
- Accessing link will always show results based on logged in google account regardless of email shown in link -> if I access my link from a friend's laptop or device, I will see his results as if I were accessing his link; v6 prompts user to associate session with a google account.
### Join Course
- Does not work properly when user is not logged in to a google account. Error page shown with no prompt for login available. v6 immediately redirects to login page.

**Comment by wkurniawan07** [comment]
Marking as done. Kudos to everyone involved.
