### ISSUE TITLE
Instructor view results: multiple photo popups

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10356]
![image](https://user-images.githubusercontent.com/1673303/87858732-a0349500-c962-11ea-9410-adff2f949df8.png)

These things pops up (and stays) as you move the move across the page

**Comment by damithc** [comment]
Can even get in the way, covering up other clickable elements. Perhaps provide a clickable icon beside the name instead?

**Comment by t-cheepeng** [comment]
![resut](https://user-images.githubusercontent.com/28994607/88133571-fcbedb00-cc14-11ea-9f59-b95a93d9b6ef.gif)
Would this be better behaviour? Add a small icon to click on and it shows the photo popover. The popover will close immediately after cursor leaves the small portrait icon

**Comment by damithc** [comment]
Use grey? It should attract too much attention. Not sure if it will look like disabled though.
Neater to show the icon at the start rather than at the end? Not sure if it will affect sorting though.
Post screenshots of different options so that we can compare.

**Comment by damithc** [comment]
Also try black icon (without bg color)

**Comment by t-cheepeng** [comment]
> affect sorting

Nope, the sorting will not be affected by position of icons

>Also try black icon (without bg color)

For the portrait icon, we cannot use the black w/o bg since that is pro only and we are on the free version of font awesome. Some alternatives icon shown below

- ID badge icon black
![id badge black full](https://user-images.githubusercontent.com/28994607/88135930-c84e1d80-cc1a-11ea-91ab-034655469a2b.PNG)
![id badge black nobg](https://user-images.githubusercontent.com/28994607/88135935-cab07780-cc1a-11ea-91af-cf718a45989c.PNG)
- User icon black
![user black full](https://user-images.githubusercontent.com/28994607/88135931-c97f4a80-cc1a-11ea-86a7-b377dea361ce.PNG)
![user black nobg](https://user-images.githubusercontent.com/28994607/88135932-ca17e100-cc1a-11ea-8b05-183eaf1b2b6e.PNG)
- Portrait icon grey
![portrait grey full](https://user-images.githubusercontent.com/28994607/88135936-cbe1a480-cc1a-11ea-9c9b-b5305231dc4c.PNG)

**Comment by damithc** [comment]
I like the 2nd one because the icon looks similar to the actual pop up. Perhaps we should change the trigger from hover to click too, for both first time access and subsequent times? The objective is to prevent the popup unless the user deliberately asks for it.

**Comment by t-cheepeng** [comment]
So the user icon right? The one that is filled or just the outline? 

> change the trigger from hover to click 
Got it

**Comment by damithc** [comment]
> So the user icon right? The one that is filled or just the outline?

The one with the outline only


> Got it. It is already having that behaviour. Don't think it would be necessary for subsequent times though. The user has asked for it when they clicked on the icon so having to click again sounds like a hassle

Needed. Otherwise it pops up all the time whenever the mouse travels across it and and blocks other elements behind it. That's what we are trying to prevent. Plus, it's better to be consistent.
