### ISSUE TITLE
Session results csv: differences between v6 and v7

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10350]
![image](https://user-images.githubusercontent.com/1673303/87857157-1fbc6700-c957-11ea-982f-a8b31a7f5122.png)

1. v6 file name is more specific
1. v6 uses double quotes around text (safer? in case there are commas in the text)
1. sorting order of results rows seems to be different
1. line endings seem to be different (according to my diff program)

**Comment by wkurniawan07** [comment]
(2) is non-issue. The system knows when to and not to put `"`, covered by unit tests.
(3) are there specific expected sorting?
(4) is also non-issue because the line is hard-coded to `\r\n`, as the line-joining happens in front-end. Previously it happens in back-end and in Linux box it would be `\n`.

**Comment by damithc** [comment]
> (2) is non-issue. The system knows when to and not to put `"`, covered by unit tests.
> (3) are there specific expected sorting?

I see. I was rather hoping that I could diff the csv files between v6 and v7 to confirm the results are exactly the same. The diff tool can ignore line endings but the difference in sorting order and double quotes makes diffing impossible.
