### ISSUE TITLE
Instructor delete question: the button stay pressed after cancelling the operation

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10413]
Steps:
1. Go to the edit page of a session
1. Click on the delete button of a question
1. Cancel the delete operation

Problem: the delete button stay pressed (although it can be clicked again)
![image](https://user-images.githubusercontent.com/1673303/88460576-ca8cd200-cecf-11ea-8517-0213148aeb40.png)

**Comment by t-cheepeng** [comment]
This behaviour actually comes shipped with bootstrap modals. The issue was with accessibility. If the button unfocuses after dismissing the modal, the user is sent to the top of the page and not remain at where they are before the modal opens. Not sure if we should override this behaviour

https://github.com/twbs/bootstrap/issues/15195

**Comment by damithc** [comment]
> This behaviour actually comes shipped with bootstrap modals. The issue was with accessibility. If the button unfocuses after dismissing the modal, the user is sent to the top of the page and not remain at where they are before the modal opens. Not sure if we should override this behaviour

Should be fine in that case. Thanks for the investigation @t-cheepeng
