### ISSUE TITLE
Buttons in table/panel headings should use the darker shade

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10510]
I thought we decided to use the darker shade buttons here?

![image](https://user-images.githubusercontent.com/1673303/89115468-1553ae80-d4bb-11ea-952a-8ad7c5b02a93.png)

**Comment by wkurniawan07** [comment]
Standardizing button style is still ongoing. This is a site-wide undertaking that cannot be done that soon.

**Comment by wkurniawan07** [comment]
@ccyccyccy it looks like the one in instructor home page is missed? Everywhere else looks good.

**Comment by ccyccyccy** [comment]
I think we didn't really decide what color should dropdowns within a panel header be, since this is the only such occurance. 

@damithc How does this look? It's the same as the other buttons.
![image](https://user-images.githubusercontent.com/32454748/89180928-4ddfaf00-d5c5-11ea-9296-e0290545c0df.png)

**Comment by damithc** [comment]
> @damithc How does this look? It's the same as the other buttons.

I'm OK with this version.
