### ISSUE TITLE
Pages with rich text editors cannot be displayed

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10559]
Chrome, Win10

Steps:
1. Open a fresh browser
1. Login as an instructor
1. Click on the `Sessions` link in the top navigation bar

Problem: nothing happens. Same for the `Search` link. But you can go to the page by editing the browser URL. Furthermore, the problem goes away after visiting that page once.

Let me know if cannot reproduce.

**Comment by madanalogy** [comment]
Can confirm that this is an issue in the latest master (both on my dev server and staging server). Affected nav items: `Sessions`, `Search`, `Help`. Clicking on a link pops up the following error in the dev console:

`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/"`

**Comment by wkurniawan07** [comment]
@damithc can you re-deploy after changing the following line:
https://github.com/TEAMMATES/teammates/blob/748cc55e52ee30f9aa41aef61f4612dab927585f/src/main/java/teammates/ui/webapi/action/WebPageServlet.java#L19

```patch
- "script-src 'self' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/", 
+ "script-src 'self' 'unsafe-eval' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/", 
```

This fixes the problem but takes away an important security layer.

**Comment by wkurniawan07** [comment]
Ok I found the solution that doesn't require changing the CSP. Will submit a PR.
