### ISSUE TITLE
Instructor copying sessions: operation not atomic

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10657]
When copying a session to another course, either the full session should be copied or the entire operation must be aborted (i.e., it should be atomic). Currently, the session can get created without the questions if there is some problem with the questions.

Not sure if this is an old problem or caused by the new V7 API.

**Comment by wkurniawan07** [comment]
This is definitely not a V7 problem.

**Comment by rrtheonlyone** [comment]
This is an interesting issue. 

From what I can see, how the copying works is that it:
1. Creates a new feedback session with the same details as the one we are copying from by calling `POST /session`
2. For each question in the current form:
    - create a brand new question in the session from (1) by calling `POST /question`

Note: step (2) is done in sequence `q1 -> q2 -> q3 -> ....` where `q1` is the first question in our session

If the creation of a single question fails in (2),  we stop the transaction and the user is greeted with a toast message of the failure (no page redirection happens). However, (1) has taken place and any previous question for (2) is also created. So, the user will still see a new feedback session (with possibly some questions) when he goes back to the main page. 

Some ways to fix (not ideal I believe):
- create a new resource on the backend for this transaction e.g. we make one API call instead of many and the backend handles both (1) and (2) 
- delete the feedback session if any question in (2) fails?

**Comment by damithc** [comment]
I think it's the #10656 that's aggravating this issue. Normally, the copy operation should not fail halfway as existing questions are not supposed to be _invalid_.

**Comment by wkurniawan07** [comment]
@damithc on a higher level, none of the operations in TM, V6 or V7, are atomic. The DB that we use is not an ACID DB.

**Comment by damithc** [comment]
> @damithc on a higher level, none of the operations in TM, V6 or V7, are atomic. The DB that we use is not an ACID DB.

Yes, that's correct. We have to do it ourselves where it is required, and to the extent it is possible.

**Comment by madanalogy** [comment]
I think this should have been resolved with #10676 yes?

**Comment by wkurniawan07** [comment]
No, it's not. #10676 merely guarantees (to some extent) that the copied sessions will be valid.

But "operation not atomic" is a very contentious topic. Definitely not something that can be fit in one issue. Of course, it doesn't help that we don't use ACID DB. With ACID DB, we can make use of transactions and commits to ensure atomicity. Not here: e.g. if one argues that "if any operation fail we just undo everything", then the reply will be "what if the undo operation fails?".

That being said I don't think this issue is worth being kept open.

**Comment by madanalogy** [comment]
Agreed, closing for now. We can bring up atomicity if necessary again starting from the DB layer.
