### ISSUE TITLE
Unregistered student submitting responses/viewing results: show institute at the footer

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10750]
I was troubleshooting the submission link for a student and noticed that the institution is not shown in the page footer.

![image](https://user-images.githubusercontent.com/1673303/94981473-4147ea80-0565-11eb-9891-21f3af4bf0ef.png)

**Comment by madanalogy** [comment]
> I was troubleshooting the submission link for a student and noticed that the institution is not shown in the page footer.

Was the submission accessed via unregistered reg key? The institute will only show if a user is registered and logged in (i.e. the institute field can be populated from the user's details)

**Comment by damithc** [comment]
> Was the submission accessed via unregistered reg key? The institute will only show if a user is registered and logged in (i.e. the institute field can be populated from the user's details)

Yes, unregistered. I didn't realize that was a limitation. Registering is not the norm though. Is there any way to get that info in another way? For example, through the session -> course object?

**Comment by wkurniawan07** [comment]
> through the session -> course object

Session/course has no such field. The closest thing is getting the institute information from the course's instructor, i.e. the same logic used to determine the institute upon joining.

**Comment by damithc** [comment]
> Session/course has no such field. The closest thing is getting the institute information from the course's instructor, i.e. the same logic used to determine the institute upon joining.

As we are showing NUS as the sponsor, it's best if we can also show their own institution or else it will feel like they are using someone else's system. Perhaps we should consider adding the institution to the student object at the time of creation? More duplication and storage but fewer reads.

**Comment by wkurniawan07** [comment]
That's not going to help. The institute is shown based on the login information. If we need to query a student object just to get the institute, we might as well just use the original method. Admittedly, using a student object will result in less/cheaper queries.

**Comment by damithc** [comment]
> That's not going to help. The institute is shown based on the login information. If we need to query a student object just to get the institute, we might as well just use the original method. Admittedly, using a student object will result in less/cheaper queries.

The problem is, students joining the course is rare. Vast majority access TEAMMATES using links. Our strategy should work for both cases (ideally).

**Comment by wkurniawan07** [comment]
What I'm saying was the proposed change offers little help because the page skeleton (the header and footer) is based on login information and not any specific student/instructor entity.

**Comment by damithc** [comment]
> What I'm saying was the proposed change offers little help because the page skeleton (the header and footer) is based on login information and not any specific student/instructor entity.

I see. Anyway, I'm not sure how to achieve it but the desired end goal is that institution to be shown for both registered and unregistered users.

**Comment by wkurniawan07** [comment]
What I said here:

> If we need to query a student object just to get the institute, we might as well just use the original method. Admittedly, using a student object will result in less/cheaper queries.

**Comment by damithc** [comment]
> What I said here:
> 
> > If we need to query a student object just to get the institute, we might as well just use the original method. Admittedly, using a student object will result in less/cheaper queries.

Sure, as long as the requirement is met at a reasonable cost :-) The dev team can decide the best way to get there.

**Comment by madanalogy** [comment]
I'm thinking we could add an `/institute` endpoint that can receive a `courseId` and try to find the course owner then return the institute of the course owner. This would be an additional http request for every user load though and could end up being very costly for us.

Alternatively, we can focus on the typical use case for the average user. Since this problem is specifically relating to unregistered users, we can add a method in the submission page load (where students would immediately go upon clicking their email link) to populate the institute field with the course details. This might not be ideal but suffices the idea of reflecting familiarity. The footer would show for example: [symbol] for CS2103: Software Engineering

**Comment by damithc** [comment]
> This might not be ideal but suffices the idea of reflecting familiarity. The footer would show for example: [symbol] for CS2103: Software Engineering

It's better if we can show the actual institute name. Students may not like if when they pay for school X and then have to use a product sporting the name of school Y, from a different country too. Eventually, someone could complain to the instructor/university or rant about it somewhere -- you know how things are these days. :-p

**Comment by madanalogy** [comment]
> I'm thinking we could add an /institute endpoint that can receive a courseId and try to find the course owner then return the institute of the course owner. This would be an additional http request for every user load though and could end up being very costly for us.

@wkurniawan07 @xpdavid any other suggestions? If not I can try out this approach. This is as opposed to changes to `StudentAttributes` which might require a data migration I'm guessing.

@damithc let me know if you're not keen on this approach considering the potential added cost

**Comment by wkurniawan07** [comment]
> This would be an additional http request for every user load though and could end up being very costly for us.

Additional HTTP request is not necessarily an issue. It will if the request has many DB read operations, and unfortunately for this case (getting institute given course ID) there is a good chance that the cost is not cheap. In particular, one needs to get the list of instructors in the course for this operation:

https://github.com/TEAMMATES/teammates/blob/1c2b94d63a7be533d96e149223c0f4368bcea1cd/src/main/java/teammates/logic/core/AccountsLogic.java#L63-L84

Of course, I have no proof that the cost will be unbearably high, but the above code snippet shows a good indication.

**Comment by damithc** [comment]
> I'm thinking we could add an /institute endpoint that can receive a courseId and try to find the course owner then return the institute of the course owner. This would be an additional http request for every user load though and could end up being very costly for us.

In addition to this, if we duplicate the institution name into the course at the point of creation, fewer reads are needed. No migration needed if you make the code backward compatible. i.e., show if the field is present only. I think GAE datastore allows (being an object database) addition of fields without needing to update all existing entities. When you read a legacy entity, the added field will have null as the value (IIRC). @xpdavid might be able to confirm.

**Comment by xpdavid** [comment]
> When you read a legacy entity, the added field will have null as the value (IIRC). @xpdavid might be able to confirm.

Yes. This leads us to question: "Why we design to have `institute` to tracked by `Account` and `Instructor` previously?"

> I'm thinking we could add an /institute endpoint that can receive a courseId

@madanalogy I guess you don't need new endpoint. `institute` field is available in `StudentData`(`GetStudentAction`)

**Comment by damithc** [comment]
> Yes. This leads us to question: "Why we design to have `institute` to tracked by `Account` and `Instructor` previously?"

In fact, this causes other problems in cases where the instructor teaches in multiple institutions. We can still have the institution as part of instructor account and copy it over to the course when creating a new course, but allow the instructor to edit it per course. The editing part can be a separate PR.

**Comment by madanalogy** [comment]
> @madanalogy I guess you don't need new endpoint. `institute` field is available in `StudentData`(`GetStudentAction`)

That's convenient. Adding the institute can be quite straightforward then, i.e. calling `getCourseInstitute()` in the `GetStudentAction` and adding it to the `StudentData`. This would result in higher DB reads however as @wkurniawan07 pointed out. I'm going to refer to this as option A.

An alternative implementation is having the institute be a native element of the course. This would involve adding that extra step in course creation and adding institute CRUD to the various course endpoints as well as frontend displays. This is on top of modifying the current workflow for the result and submission page to somehow retrieve this info (currently the pages only retrieve `FeedbackSession` details, not `Course`). I'm going to refer to this as option B.

Option B is more work but could potentially save us actual dollars so I'm more keen on taking this route. Additionally, we could tweak the entity involved and have `institute` be a native element of `FeedbackSession` instead of `Course` to resolve the workflow issue. On the other hand, we could go with both (i.e. implement option A first then eventually work adding option B). As mentioned as well, another approach is to split option B to separate issues (i.e. one purely for institute generation and the other for CRUD).

@damithc with most of the considerations laid out, do you have any preferred approach?

**Comment by damithc** [comment]
> @damithc with most of the considerations laid out, do you have any preferred approach?

What's the difference in terms of number of reads per one submissions/results page of an unregistered user?

**Comment by madanalogy** [comment]
> What's the difference in terms of number of reads per one submissions/results page of an unregistered user?

If we adopt option A then it is dependent on the number of reads in the `getCourseInstitute()` method which appears to be retrieving information from 3 different entities, so 3 reads.

If we adopt option B then we make `institute` a native attribute of `Course` which means we just need to add one http call in loading the submission/result page and 1 read from the DB (to retrieve the course), so 1 read.

@xpdavid do let me know if I'm mistaken or if there's another possible option.

**Comment by damithc** [comment]
Dollar saving is not an immediate concern (as SoC is paying, we are fine as long as we are within budget) so I'm fine with either, or doing A first (if it is much simpler) and keeping B for the next CS3281 batch. That will also allow us to measure the actual impact on cost.

**Comment by madanalogy** [comment]
I'll wait and see if anyone else wants to work on it. If no one picks this up by mid October I'll go with implementing option A

**Comment by wkurniawan07** [comment]
> retrieving information from 3 different entities, so 3 reads.

On a general note, the number of reads is one thing, but you need to be more concerned about the number of entities returned. One of the operations in the option A is listing instructors, which in practice should not be a lot per course, but when multiplied by the number of times the request comes this may or may not have visible impact.

**Comment by rrtheonlyone** [comment]
Just adding an idea here: 

What about adding the institute into the web link we give the students? Then we can immediately give them the footer information without any additional costs.

e.g. /web/sessions/submission?courseid=rr.r.c-demo&key=2906774B64722AB76063CA67B14179E31707726AE6274AD24C3A1B84EFE9E5AC&studentemail=1%401.com&fsname=Second%20team%20feedback%20session&**institute=.....**

In order to generate the above link, we are already fetching the course/student/session information. We can also get institution by adding on to the existing functions.

**Comment by damithc** [comment]
> What about adding the institute into the web link we give the students? Then we can immediately give them the footer information without any additional costs.

Good point. A bit worried that the longer the link is, scarier it looks to users, and higher the chance of our emails getting flagged as 'unsafe' (?)
