### ISSUE TITLE
Instructor viewing results: apply numeric sorting whenever possible

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10785]
Example, from a distribute points question:

This sorting in the summary table is correct.
![image](https://user-images.githubusercontent.com/1673303/96017619-cb088980-0e7c-11eb-88ba-b7545abf7468.png)

For the same question, the details table:
![image](https://user-images.githubusercontent.com/1673303/96017836-0c993480-0e7d-11eb-8249-136b7ed6d21c.png)

Suggestion: Apply numerical sorting consistently in all tables.

**Comment by wkurniawan07** [comment]
This suggestion doesn't look valid. `Team` is a string.

**Comment by damithc** [comment]
> This suggestion doesn't look valid. `Team` is a string.

I said the same thing to the user who reported this. He pointed out that the two sorting methods used within the same question and that TEAMMATES seems to know how to do it already; just need to apply it consistently. The two screenshots above are from the same question in the same course. The team numbers are 1 to 39. One table sorts it numerically and the other sorts it alphabetically. Here's a longer screenshot.
![image](https://user-images.githubusercontent.com/1673303/96022911-2e49ea00-0e84-11eb-883d-e688e75382fe.png)

Minimally, the two tables need to behave consistently. On top of that, perhaps we should always sort numerically? Would that mess up the order if the team IDs are non-numeric strings?

**Comment by wkurniawan07** [comment]
> Would that mess up the order if the team IDs are non-numeric strings?

Of course. All strings are basically `NaN` when forced to be a number, i.e. no sorting would even occur. So it would satisfy this one user, but will trigger complain from 100 others.
One would need a custom sorting order to support this kind of requirement. But judging by the said user's observation, it's already present somewhere in the code base. Point being, it's not pure numeric or pure string: it's a mixture of both.

**Comment by damithc** [comment]
> One would need a custom sorting order to support this kind of requirement. But judging by the said user's observation, it's already present somewhere in the code base. Point being, it's not pure numeric or pure string: it's a mixture of both.

Sure, that works.

**Comment by nicolas-sterose** [comment]
Hello, we are a group of students who is beginner in open-source and we would like to tackle this issue. Is it possible ?

**Comment by Grahamet** [comment]
Hi I'm a student new to open source and I see that this issue has been requested but i was wondering if it is possible to work on as it still is tagged as open and hasn't been commented on since November 2020?

**Comment by xyzhang00** [comment]
Hi! May I ask if this issue is still relevant? If so I would like to work on it :)

I have taken a look at the current TEAMMATES and it would seem that response details table already supports sorting by giver team name. However, different question types support different sorting methods when the tabs are first expanded. For example, `constsum-recipients-question` initially sorts by `Points Received`.
<img width="793" alt="Screenshot 2021-07-30 at 3 00 49 AM" src="https://user-images.githubusercontent.com/54242896/127550804-01dcdac9-b1d6-438e-b073-f694bfa02f84.png">

Some question types, like `contribution-question` (and `Participants who have not responded to any question` panel), does not have an initial sorting order.

I assume resolving this issue would involve sorting the results table by the first column whenever possible. Is this a reasonable assumption?

**Comment by damithc** [comment]
> I assume resolving this issue would involve sorting the results table by the first column whenever possible. Is this a reasonable assumption?

I don't think this issue is about the _initial_ sorting order (which is also important but that's a separate issue). It's about being able to sort a column by numerical order, _if_ the column contains numbers only.
If we know in advance the column should contain numbers only (e.g., `total points` column), we should sort numerically, for sure.
But it is tricky if there is no such guarantee e.g., `Team` column, which can be numbers or strings or a mix. But as the user pointed out, TEAMMATES seem to do that in some places already (see https://github.com/TEAMMATES/teammates/issues/10785#issuecomment-708542686).
I think the first step is to find out how it is being done in the summary table, which the user says is using numerical sorting. It could be either a clever implementation that caters for this tricky situation, or simply an incorrect application of numerical sorting to a column that is _not_ guaranteed to have numbers only. If the former, we can apply the same solution to other similar places. If the latter, we have to revert that back to alphabetical sorting, which is at least consistent with other places.

**Comment by xyzhang00** [comment]
> I think the first step is to find out how it is being done in the summary table, which the user says is using numerical sorting. 

Hi prof, sorry for misunderstanding the issue! I went to take another look and response details table sorting by `Team` doesn't actually sort numerically. This is because sorting by `GIVER_TEAM` attribute is done lexicographically:
<img width="153" alt="Screenshot 2021-07-31 at 12 05 03 AM" src="https://user-images.githubusercontent.com/54242896/127680651-6c91a1b5-0f0a-4eb7-a5f0-21272191af4f.png">
If the attribute is sorted naturally, which TEAMMATES already support, the order will be correct:
<img width="162" alt="Screenshot 2021-07-31 at 12 06 28 AM" src="https://user-images.githubusercontent.com/54242896/127680809-59f76b27-8beb-4066-a184-b2bfdf16eb7d.png">
Is this what we are looking for?

**Comment by damithc** [comment]
@xyzhang00 I'm not entirely sure if you have a full picture. Read through the full thread carefully and see if you missed something.

**Comment by xyzhang00** [comment]
I am really sorry if I am misunderstanding something. I thought the main issue here is that summary table and details table have different sorting orders for team names, which should be the same thing and hence sorted in the same way. That is because the summary table `Team` (`TEAM_NAME`) is sorted naturally and details table `Team` (`GIVER_TEAM`) is sorted lexicographically (see `TEAM_NAME` vs `GIVER_TEAM` in [here](https://github.com/TEAMMATES/teammates/blob/master/src/web/services/table-comparator.service.ts)). 
Minimally, same type of attributes should have the same comparing method (i.e. all team names sort lexicographically/naturally)?

**Comment by damithc** [comment]
> I am really sorry if I am misunderstanding something. I thought the main issue here is that summary table and details table have different sorting orders for team names, which should be the same thing and hence sorted in the same way. That is because the summary table `Team` (`TEAM_NAME`) is sorted naturally and details table `Team` (`GIVER_TEAM`) is sorted lexicographically (see `TEAM_NAME` vs `GIVER_TEAM` in [here](https://github.com/TEAMMATES/teammates/blob/master/src/web/services/table-comparator.service.ts)).
> Minimally, same type of attributes should have the same comparing method (i.e. all team names sort naturally)?

Yes, I think you are right.

> If the attribute is sorted naturally, which TEAMMATES already support, the order will be correct:

Yes, I think so too.

I think you have understood the problem correctly after all. Sorry, my bad. Go ahead and submit a PR.
