### ISSUE TITLE
Admin search page: show instructors and students in different colors

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10844]
Current: When an admin uses the search page, students and instructors in results are shown in separate panels but of same type  (i.e., primary).

![image](https://user-images.githubusercontent.com/1673303/99463118-06144600-2970-11eb-8e46-096a5ffc00e7.png)

Suggested: Use a different type of panel for instructors (e.g., info), to make it easy to distinguish between the two.

**Comment by prirai** [comment]
Hi everyone, I'm new in open source and this will be my first contribution if I'm able to make it. 
Please tell me what knowledge should I have in order to tackle this issue. I've studied and done great programs in pure Java and I recently completed my grade 12 (ISC).
In addition to core Java, I have very basic knowledge of multi-threading, graphics and applets.
I use Intellij-Idea for programming.

**Comment by sanket0354** [comment]
Going to take a look at this issue as my first one once I set up the project.
