### ISSUE TITLE
Skip 'session closed' emails if already submitted

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10902]
Similar to #10901

**Comment by rrtheonlyone** [comment]
Actually for this, I am wondering what is the purpose of the 'session closed' emails in the first place. I initially thought that the 'closed' emails are for a student to just double-check that his submission is okay. 

In this case, if we only send this to students who have not even attempted a single question, what would be the purpose? (since they cannot go and submit anymore)

**Comment by madanalogy** [comment]
@damithc can we get your input on this? Maybe remove session closed emails altogether

**Comment by damithc** [comment]
> In this case, if we only send this to students who have not even attempted a single question, what would be the purpose? (since they cannot go and submit anymore)

They can ask for a deadline extension. It also reminds the instructor that the session is over (when s/he receives a copy) so that the followup actions can be taken without delay. So, there is _some_ use although not a lot.
