### ISSUE TITLE
Support tracking of result view by instructors

### ISSUE THREAD

**Issue by ypinhsuan** [TEAMMATES/teammates#11139]
**Description of feature**
Provide a way for instructors to track if the sessions results were viewed by students.

**Justification**
This will help instructors identify students who do not even bother to read feedback they have received.

UI prototype
![image](https://user-images.githubusercontent.com/58677983/119068516-f1943180-ba16-11eb-861c-7bbcc47c8cb8.png)
Is just knowing whether a student has viewed the results sufficient or do we need a column for time (to know when the student viewed the results)?

**Comment by damithc** [comment]
Looks good. Some suggestions:
* Show `Not viewed` in red?
* Sort by `Status` (`not viewed` on top) and then by name?
* Are we going to limit the search to go only up to the date the session was published? In that case, we may want to show that date in the results page, just in case the session was published and unpublished earlier (which means some students would have viewed the results prior to the latest 'published' date. 
* If the published date is older than 30 days, we want to show a dialog to warn that only activities within the last 30 days are captured. That dialog should also have an `abort` button so that we can avoid an unnecessary search if the instructor doesn't want to go ahead.
* Yes, good to show the `last viewed at` date, if no extra cost.
   An alternative is to show the following in the the status column: `Viewed last on {date/time}`, `Not viewed since {published date or the earliest search date}`

* Probably no need for the result to be inside a panel?

**Comment by ypinhsuan** [comment]
Would it be good to allow users to sort by both name and status? By default the table will be sorted by status (not viewed on top). But users can sort by name as well by clicking on the `name` column.

I think we can limit the search to go only up to the date the session was published since earlier than that results will not be significant.

Dialog as below will  be displayed if published date is more than 30 days before today
![image](https://user-images.githubusercontent.com/58677983/119129117-11ecdc00-ba69-11eb-867f-61a6cdd62fb5.png)

Option 1. Show time in status column. I think it might be better to use a separate column for time since monospaced font is used to make timestamps aligned. Might look a bit weird to have 2 fonts in the same cell.
![image](https://user-images.githubusercontent.com/58677983/119129923-22ea1d00-ba6a-11eb-9ffb-6fc416534341.png)


Option 2. The time column is used to display both `last viewed at` and `not viewed since`. Not sure if it will be slightly confusing for users.
![image](https://user-images.githubusercontent.com/58677983/119129403-714aec00-ba69-11eb-8b66-515aa485e65c.png)


Option 3. Another way is to show the `not viewed since` time will at the top of the table since this date is the same for all students who have not viewed the session results.
![image](https://user-images.githubusercontent.com/58677983/119129661-c981ee00-ba69-11eb-9842-ad9bd11f1ba0.png)

**Comment by damithc** [comment]
> Would it be good to allow users to sort by both name and status? By default the table will be sorted by status (not viewed on top). But users can sort by name as well by clicking on the `name` column.

Yes, any column can be made sortable when it makes sense.

> Option 1. Show time in status column. I think it might be better to use a separate column for time since monospaced font is used to make timestamps aligned. Might look a bit weird to have 2 fonts in the same cell.
> ![image](https://user-images.githubusercontent.com/58677983/119129923-22ea1d00-ba6a-11eb-9ffb-6fc416534341.png)

I think this option is fine. You can use mono-space for the whole cell. Probably can get the time stamps to align by using a few extra spaces:
```
Not viewed since {date}
Last viewed at   {date}
```

Minor: The button should be `View` or `Show` rather that `Search`?

**Comment by ypinhsuan** [comment]
> I think this option is fine. You can use mono-space for the whole cell. Probably can get the time stamps to align by using a few extra spaces:
> 
> `Not viewed since {date}`
> `Last viewed at   {date}`
> Minor: The button should be View or Show rather that Search?

Made the above changes. If ok, I will work on this design for now
![image](https://user-images.githubusercontent.com/58677983/119211279-c62b4880-bae3-11eb-9cd6-2e50ce1253e8.png)

**Comment by damithc** [comment]
Looks good @ypinhsuan. I think we should put the status column as the first column. As the user is going to be more interested in the status and the name columns, it's better to put them close together rather than far apart.
