### ISSUE TITLE
Instructor checking student activity: use grey panel if no results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11176]
Steps:
1. Instructor goes to `/web/instructor/logs`
2. Search for activities of some student/session
3. No results returned for some sessions:
   ![image](https://user-images.githubusercontent.com/1673303/120956906-35ad6300-c787-11eb-80cc-01e10b9ab602.png)

Suggestion: Empty panels are shown in green (i.e., success) style. Perhaps we can use a different style for empty panels e.g., grey?

**Comment by damithc** [comment]
@t-cheepeng is this suitable for first-timers?

**Comment by t-cheepeng** [comment]
Yes, suitable

**Comment by blancont** [comment]
First-timer here, could I try working on this issue?

**Comment by rrtheonlyone** [comment]
> First-timer here, could I try working on this issue? 

Yes please go ahead!

**Comment by blancont** [comment]
Hi, I apologize for the long wait, I'm unfamiliar with contributing to open-source software so I've been slow to setting up the development environment.

I'm trying to create an instructor to simulate the issue but attempts to add the instructor fails. I assume this is because no email containing a join link actually gets sent on the dev server. The development guidelines say to use the join link given after adding an instructor to complete the joining process, but I can't seem to find this link anywhere. Where can I find this link?

If this is the wrong place to ask, I can redirect my question somewhere else instead. Apologies for the trouble.

**Comment by t-cheepeng** [comment]
> Where can I find this link?

Hi @blancont, you can find the link in the admin page when you add the instructor.

Follow the steps here under the `Logging in to a TEAMMATES instance` section 
https://github.com/TEAMMATES/teammates/blob/eb6f5dba9927a7149cf2a52f735199659374781a/docs/development.md
