### ISSUE TITLE
Give a better error message when a user attempts to paste an image from clipboard

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11477]
Reported by a user who attempted to paste an image from the clipboard into the text box (which is not supported by TEAMMATES):
![image](https://user-images.githubusercontent.com/1673303/142721427-2856efbb-aff2-4a41-bed0-62afaa332a4c.png)

Perhaps we can give a better error message?

**Comment by wkurniawan07** [comment]
That error message (and style) came straight from tinymce library.

**Comment by fsgmhoward** [comment]
I tried to look into this issue on my local dev server but I cannot reproduce it with either Edge 97.0.1072.55 or Firefox 95.0.2. When tried to paste images (either screenshot or copy of file), nothing is pasted into the textbox but there is also no error messages popped out. May I know if it had been fixed in some commits before?

**Comment by damithc** [comment]
@fsgmhoward thanks for checking. It looks like the problem no longer exists (I tried using Chrome 96, Win 10). Closing.
