### ISSUE TITLE
Student submitting MCQ question: comments are not loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11693]
Situation:
A student is editing responses to an MCQ question that she submitted earlier, and reported that she is seeing the following error.
![image](https://user-images.githubusercontent.com/1673303/161076713-ab88d1c2-0084-4c31-a630-8eb8d8bca063.png)

It turns out the submission page is not loading the comments she submitted earlier i.e.,  clicking this button given below shows an empty form instead of the comment she submitted previously.

![image](https://user-images.githubusercontent.com/1673303/161076941-bb920134-51b6-41d8-ad72-6ca723964eb0.png)

When she enters a new comment, the above error message shows. I've checked the database to confirm the comment is in the database, and it even shows up in the results page when instructor views it.

**Comment by samuelfangjw** [comment]
Did some investigation, seems like a valid bug. Part of the issues stem from here:

https://github.com/TEAMMATES/teammates/blob/7dfda8ba63070c0924eb397c98bae8008c00b30b/src/web/app/pages-session/session-submission-page/session-submission-page.component.ts#L533-L580

For `FIXED_RECIPIENT` types, existing comments are added (lines 547-549). However, for `FLEXIBLE_RECIPIENT` type, existing comments are not added to the form model.

However, the issue doesn't seem to be as simple as adding the comment to the form model for `FLEXIBLE_RECIPIENT` type.  Currently, when submitting responses, we don't account for a change in recipients of the comment (i.e. add comment -> change recipient -> submit response -> error because comment is still tied to old respondent).
