### ISSUE TITLE
Error when copying feedback question: session name is not acceptable

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11774]
v8.14.1

I'm seeing the following error in the production server logs from time to time (3 times during the last week). 

>Error when copying feedback question: The provided feedback session name is not acceptable to TEAMMATES as it contains only whitespace or contains extra spaces at the beginning or at the end of the text.

No one has complained about it yet though.

My thoughts:
* If the user didn't type anything for the session name, the submission can be blocked at the UI itself
* If there are leading/trailing spaces, they can be auto-trimmed

**Comment by hoanglan21** [comment]
I'm not sure which one you are talking about because when you want to copy a question from another session, you don't have to type in the session 
<img width="873" alt="Screen Shot 2022-05-15 at 9 43 55 PM" src="https://user-images.githubusercontent.com/46897782/168506292-f5273c9e-2282-43d6-ba22-1266d51a9878.png">
if you are copying a feedback session, if the session's name is empty then you would not be able to click next 
<img width="519" alt="Screen Shot 2022-05-15 at 9 44 33 PM" src="https://user-images.githubusercontent.com/46897782/168506368-24dec872-6a56-42e4-aa11-e5136311c11a.png">
if you are copying a new course, you can indeed leave the course's name blank by filling it with black space. However, when clicking next, an error message will show up:
<img width="518" alt="Screen Shot 2022-05-15 at 9 45 22 PM" src="https://user-images.githubusercontent.com/46897782/168506453-29db600e-3e60-48be-bccd-40e6adc27c59.png">
<img width="618" alt="Screen Shot 2022-05-15 at 9 45 29 PM" src="https://user-images.githubusercontent.com/46897782/168506470-853e6109-3ebf-4a8f-99b3-f0b8a31a880b.png">
is this what you mean?

**Comment by damithc** [comment]
@hoanglan21 The given error message was found in logs (not reported by a user). One approach is to locate the code that produces this error message and work your way backwards to find which user action can potentially cause this error to be logged.

**Comment by damithc** [comment]
Still finding these ERROR level log messages in the logs ... I examined logs further and the target session name indeed as a trailing space. Shouldn't this be caught (or even auto-trimmed) at the UI? 
The relevant backend action: `CreateFeedbackSessionAction POST /webapi/session`

```
"feedbackSessionName": "Peer Evaluation For MBA522Su2022 ",
  "instructions": "<p>The purpose ....</p>",
  "toCopySessionName": "Peer Evaluation For",
  "toCopyCourseId": "MBA522",
  "submissionStartTimestamp": 1592402400000,
  "submissionEndTimestamp": 1593234000000,
  "gracePeriod": 15,
  "sessionVisibleSetting": "AT_OPEN",
  "responseVisibleSetting": "LATER",
  "isClosingEmailEnabled": true,
  "isPublishedEmailEnabled": true
```

Perhaps the user is shown the appropriate error message (as there are no user complaints regarding this) but in that case it should not be logged as an ERROR level log by the backend (because ERROR level logs trigger a notification to the admin).

**Comment by sivayogasubramanian** [comment]
@damithc Investigated this issue. 

Why the problem occurs:

When we try to create a new session by copying a previous session, the name of the session cannot be empty (UI restricts submission of the form). However, trailing spaces are allowed. 

<img width="731" alt="Screenshot 2022-07-06 at 9 22 28 PM" src="https://user-images.githubusercontent.com/53614454/177560195-51e5cf70-280e-4f64-aed6-e3cd627991e8.png">

This causes a `SEVERE` level error log in the backend. The backend does not use the trimmed version of the feedbackSessionName for this edge case (when copying from the previous session).
