### ISSUE TITLE
Responding to team contribution questions: the percentage is not visible unless clicked

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11796]
v8.15, production, Windows 10, Chrome 101

Context: a user responding to a 'Team Contribution' type question

Current:
![image](https://user-images.githubusercontent.com/1673303/168719480-6aa0493c-611e-427f-a9e5-dfa291050c7f.png)

Problem: The percentage value is not visible to the user unless the dropdown is clicked. It's hard to see at a glance what values each were given.

![image](https://user-images.githubusercontent.com/1673303/168719616-b051e7b9-8218-4da4-a0a5-4b360a3519c4.png)

**Comment by LaideLawal** [comment]
I would like to contribute to this issue

**Comment by samuelfangjw** [comment]
> I would like to contribute to this issue

@LaideLawal Please go ahead!

**Comment by LaideLawal** [comment]
Hi Samuel,

Thank you for giving me the opportunity to contribute to the laudable
project.

However, I cannot find my way to logging-in into the application and check
out the look and feel before attempting to attend to the issue I wish to
take up, this is possibly because I am a newbie.

Please, I need a guidean, a mentor in order to get my footings, I have been
reading this and that for the past 4 days to no avail.

While awaiting your favorable response, I thank you in advance.

Yours Sincerely

Laide Lawal


please, my request is to have a
