### ISSUE TITLE
Update Jetty library to 10 or 11

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#12021]
As announced in https://github.com/eclipse/jetty.project/issues/7958, Jetty 9.x have ceased community support.

It is not EOL and will still receive security patches for the foreseeable future, but at the same time, there is no pull factor for us to stay at Jetty 9.x either. It may be a good time to explore upgrading to Jetty 10 or 11 now.

_Should we instead move to other web framework such as Spring Boot?_

While the idea is welcome, it is a far more disrupting change to the application architecture, and the cost/benefit must be thoroughly explored. And in the event it does happen, this issue is no longer the place for it.

**Comment by ohmoomtang** [comment]
Hi @wkurniawan07 first of all, nice to know the TEAMMATES project. This is my first contribution to community project ever. 

I'm a developer by profession. However, I'm quite new to modern Java ecosystem and I think this is a very good opportunity to be familiar with (as my new workplace using quite a lot of Java, also, the same stack - Java + Angular)

I'm happy to help you on this. However, just wondering about post-upgrade testing, should I do the whole E2E (blackbox) or just only component testing is enough?

Thanks very much.

**Comment by ohmoomtang** [comment]
Hi @wkurniawan07 I already finished this with open PR. This is ready for review.

As Jetty 11 rename all `javax` to `jakarta` and some of Google Cloud dependencies still refer to `javax` so will need to upgrade at the latest Jetty 10 (10.0.13) instead of using version 11. However, the code base should be ready for a further version of Jetty from now.
