### ISSUE TITLE
Team members cannot see responses received by the team

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12029]
v8.20.0

Question setting:
![image](https://user-images.githubusercontent.com/1673303/213059680-88759dfb-7228-49e5-9e7d-6b3e8f4e7400.png)

Problem: team members can't see the responses received although there are responses.
![image](https://user-images.githubusercontent.com/1673303/213059585-a5257b1e-5d63-4ef3-a6b0-4e60b23cf155.png)

**Comment by hhdqirui** [comment]
I think the problem is in the method `isResponseVisibleForUser` in `src/main/java/teammates/logic/core/FeedbackResponsesLogic.java`. In this file, from line 635 to 652, the responses do not satisfy any of the condition to set `isVisibleResponse` to `true`. The question recipient type is `TEAMS_EXCLUDING_SELF`, question giver type is `STUDENTS`, and the question shows response to `INSTRUCTORS` and `RECEIVER`, but there is no code to handle such situation. Therefore, the response is never set to visible.

**Comment by damithc** [comment]
I see. Thanks for investigating @hhdqirui 
Must be a recent regression, as this was not the case one year ago. And we need to fix it soon, as giving feedback to a team is not-so-rare use case.
