### ISSUE TITLE
Instructor results page stats tables: differentiate students with same team and name

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12125]
Currently, in the instructor view results (course-wide) page, there is no way to differentiate two students that are in the same team and have the same name in statistics tables (e.g. below screenshot from per criterion stats table for rubric questions).
![image](https://user-images.githubusercontent.com/54243224/220728448-9ad62b37-88ab-4a34-83ca-30616f2d470c.png)

Suggestion: add an email column to the stats tables, or include the email in the giver/receiver columns.

**Comment by samuelfangjw** [comment]
@zhaojj2209, @damithc,any thoughts on re-using the Giver/Recipient column here instead of adding a new email column? 

e.g. `Hugh Ivanov (hugh@teammates.tmt)`.

Table already has quite a few columns, if we add an email field we may have to add up to 2 more columns, one for recipient and one for giver. Furthermore, email field is not always used (depending on visibility and feedback path options).

We could also expand this issue to cover all statistics tables of other question types as well since they all seem to have the same issue.

**Comment by zhaojj2209** [comment]
Sounds good, will modify the issue to cover all stats tables.

**Comment by ellaella12** [comment]
Hi I have created a pr with my attempt at adding email to giver/recipient columns. May I request for some help reviewing the pr? thank you!
