### ISSUE TITLE
Instructor adding a new session: stray X in the form UI

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12161]
v8.23.*, production

Context: instructor is adding a new session to a course

Problem: there is an `X` that should be on the top-right (not top-left) or not present at all.
![image](https://user-images.githubusercontent.com/1673303/222875181-d9f3b498-8cfe-4649-81f6-ca5f24d5b074.png)

**Comment by samuelfangjw** [comment]
<img width="1240" alt="Screenshot 2023-03-07 at 2 27 10 AM" src="https://user-images.githubusercontent.com/60355570/223198557-c7936b08-056d-44b1-9c8b-26f4a8523bdf.png">

The close button was intentional and not a mistake. Think we can move it to the right instead of removing it. Here's how it will look for reference.

**Comment by damithc** [comment]
> Think we can move it to the right instead of removing it. 

👍

**Comment by SudarshanSirsi** [comment]
Hello @damithc  and @samuelfangjw I am new to the opensource community. and I think  I can fix this issue. If no one is currently working on this issue can you please assign this to me?.

**Comment by domlimm** [comment]
@SudarshanSirsi Hello, welcome! You may proceed to open a Pull Request (PR) to solve this issue. You are encouraged to take a look at [TEAMMATES development documentation](https://teammates.github.io/teammates/index.html) before getting started!
