### ISSUE TITLE
raise-edge image should be removed 

### ISSUE THREAD

**Issue by sumitshinde-84** [TEAMMATES/teammates#12186]
raise edge image should be removed from home page .

- **Environment**: 

**Steps to reproduce**
- open this page on any browser : https://teammatesv4.appspot.com/web/front/home
- take look at below the request a free instructer account  button 

**Expected behaviour**
![Screenshot (86)](https://user-images.githubusercontent.com/110285294/224227510-2106db4e-6cc3-40c6-af9f-98d9b3c58261.png)

**Actual behaviour**
![Screenshot (85)](https://user-images.githubusercontent.com/110285294/224227461-975cb867-132a-4b91-a1c0-a086f57a3159.png)

**Additional info**

**Comment by sumitshinde-84** [comment]
hellow i would like to work on this issue

**Comment by weiquu** [comment]
Hi @sumitshinde-84, may I know why exactly this is an issue? My understanding is that the raised edge serves as a divider between the summarised features of Teammates above and the other, more detailed information below. Hence, I'm not sure if the behaviour you pointed out is really an "expected behaviour", or simply one that is more aesthetically pleasing to you. More information would be much appreciated.

@ more experienced contributors, please weigh in if you know why the raised edge was put there / if it should be removed (:

**Comment by sumitshinde-84** [comment]
Thank you so much for giving reply .
raise edge is not seem like any divider .
And according to me that part doesn't need any divider. 
And still you want that you can use border or div as divider .

**Comment by zhaojj2209** [comment]
I agree that the raised edge image is not necessary to the UI and can be removed. However, personally, I would take this one step further and remove the image from the codebase altogether. This would mean removing the image from the features page as well.
