### ISSUE TITLE
Consolidate duplicate modified timestamp modals

### ISSUE THREAD

**Issue by samuelfangjw** [TEAMMATES/teammates#12327]
This code snippet can be found in three separate locations in the codebase:

https://github.com/TEAMMATES/teammates/blob/7b315223cc2d3b681d219283389c7f675574ea56/src/web/app/pages-instructor/instructor-session-edit-page/instructor-session-edit-page.component.html#L52-L97

See also:
- src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
- src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.html

In addition, a fourth snippet with very minor differences can be found in the course page.
- src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.html

Duplicates should be consolidated into a single component if possible, similar to other existing modals and following DRY.

**Comment by mud1tx** [comment]
@samuelfangjw In this, do we just have to remove all the duplicate code to just a single component?

**Comment by weiquu** [comment]
Hi @mud1tx, I think the issue description is fairly self-explanatory. In particular, note the following sentence: "Duplicates should be consolidated into a single component if possible, similar to other existing modals and following DRY."

In a sense, your understanding is correct, although I would say a more accurate phrasing would be to replace the duplicate code with a single component (that contains the consolidated code).

Do also refrain from spamming comments across multiple issues. It's better to focus on 1 issue and do it well, rather than try to work on many haphazardly.

**Comment by ellaella12** [comment]
Hi, is anyone working on this issue? If not, can i work on it?

**Comment by ellaella12** [comment]
Hi, I have made a pr for this. When you have time, may I request for some help reviewing it? Thank you!
