### ISSUE TITLE
Bug in instructor registration

### ISSUE THREAD

**Issue by lucasfs1007** [TEAMMATES/teammates#12432]
When registering the instructor, as one of the first stages of using the platform, the following failures were identified:
- IIt was verified that we can register the instructor's name with less than 3 characters. This being a case of non-existent name
- It was verified that we can register the instructor's name with numerical characters. This being a case of non-existent name
- It was found that we did not receive a confirmation email when registering an instructor, so it is very difficult to verify whether this email exists or not. Currently we only check the "@" and "."
- When deleting an instructor, it does not send a message to confirm the completion of the action, which is a clear IHC problem. If a user accidentally clicks, he would lose his data.

**Comment by riotgage** [comment]
I am new to this repository so please correct me if i am wrong.
From what I saw. Validation for email is performed by calling an api. I think this can very much be done at front end itself. Validations like length and characters of instructor name can also be done at front end level itself without calling the API.

**Comment by zhaojj2209** [comment]
@lucasfs1007 Thank you for submitting the issue. However, there are multiple things to discuss here:

- Fixing the first two points is not trivial as we have to check for the validity of existing data.
- For the third point, an email will be sent if the instructor email is valid, please provide more details.
- For the fourth point, we already have a confirmation modal that pops up on the UI, please provide more details.

@riotgage Validation on the the backend is for data security purposes. Ideally validation should be done on both backend and frontend.

**Comment by wkurniawan07** [comment]
- The first two points are moot. There are no heuristics for "non-existent name"; how can we be sure that there is no one in the world whose name does not match with the name we thought as "non-existent", or purely numerical characters? Weird usage does not equate invalid usage.
- "We did not receive a confirmation email when registering an instructor" is likely because there is no email service being set up.
- The last point I assume relates to the function used by admin, because the function used by instructor had the confirmation modal as pointed by @zhaojj2209. This is not an issue as at this point there is no data created yet; whatever data is displayed in the table is a verification step before actually creating the instructor in the database. Deletion here simply means that part of data that was filled in (notice I do not say created) before could be faulty / duplicated. For that purpose, having a confirmation modal here would actually be a nuisance.

Will close the issue as all the raised points are not valid.
