### ISSUE TITLE
Documentation issue - Docker-compose v2 upgrade

### ISSUE THREAD

**Issue by Raphides** [TEAMMATES/teammates#12444]
# Docker-compose v2 upgrade

- **Environment**: Linux Mint 21.1 Cinnamon

**Steps to reproduce**
On the process of creating a local dev environment, complete the Setting Up and go to the [Development Workflow](https://teammates.github.io/teammates/development.html). At the Pre-Requisites step, there is the following code:

```bash
docker-compose up -d
```

When you succeed to install Docker command line instance at their own webpage, you can try to use `docker-compose`, but an error is going to pop up, as Linux does not recognize this package as part of docker.

I believe this issue happens due to Docker v2 upgrade at compose feature, as noticed [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwieqayXp4r_AhVEEbkGHQ4uCpcQFnoECAgQAw&url=https%3A%2F%2Fwww.docker.com%2Fblog%2Fnew-docker-compose-v2-and-v1-deprecation%2F&usg=AOvVaw0EcJUlgIg-1by7S-gOn73Q). Docker compose v2 already comes with docker engine and is called without " _-_ ". Knowing this, I tested the command with `docker compose` instead of `docker-compose` and it worked fine.

**Additional info**
I do not know a lot about Docker, so I would like to know if my conclusions are correct. If yes, I would like to ask you to update the tutorial by simply deleting the "_-_" at docker-compose statement. It causes confusion in many people that does not know Docker well. If all this bug was some mistake I made, I ask you all to pardon me.

**Comment by wkurniawan07** [comment]
@Raphides thanks for the report. It is a valid issue. Since its introduction a few years back, `docker-compose` and `docker compose` are always usable interchangeably if the Docker version allows. There is no simple solution here; displaying either `docker-compose` or `docker compose` will always disadvantage one group of developers, a classic example of "it (does not) work(s) on my machine".
However given the direction of the product (i.e. Docker), it makes sense to update the guide to `docker compose`. Please be welcome to submit a fix.
