### ISSUE TITLE
BUGnotification with 1500 characters

### ISSUE THREAD

**Issue by TaynaraCris** [TEAMMATES/teammates#12447]
when i create a notification with 1500 characters i get an error message

- master branch

**Steps to reproduce**
1. click on notification
2. click add new notification
3. type 1500 characters

**Expected behaviour**
Notification created successfully.

**Actual behaviour**
The value of property "message" is longer than 1500 bytes.

**Comment by weiquu** [comment]
Hi @TaynaraCris, I think that the current behaviour is fine. I don't foresee a need to send out long notifications (and the height of the notification banner also points to long notifications being discouraged). In any case, there's always the option of putting a link in the notification to lead to a longer announcement.

@ other contributors, pls let us know your opinion as well

**Comment by wkurniawan07** [comment]
@TaynaraCris thanks for the report. This issue is classified won't fix because:
- 1,500 chars is the limitation of indexed string in Datastore, which we are in the process of migrating out of.
  - Arguably, the so-called "mistake" happens from the onset by not adding the `@Unindex` annotation, but it is not worth the trouble to fix now.
- As mentioned by @weiquu, there is currently no (short-term) need for such long notification.
