### ISSUE TITLE
Make the table buttons easier to use on mobile devices

### ISSUE THREAD

**Issue by athakaras** [TEAMMATES/teammates#12457]
Issue title: Change the instructor student buttons change on mobile devices

- **Environment**: The environment in which the said feature/enhancement is absent is the master branch

**Description of feature/enhancement**

Currently when an instructor is at the students page the actions buttons have different sizes when the user is logged in from a mobile device. This is not very aesthetically pleasant for the user. The UI is given below:

![new issue before](https://github.com/TEAMMATES/teammates/assets/95168947/e0dc2ad4-71c4-4115-b3ed-12a10a5609ad)

After some time and many alterations to the code, I managed to change the actions buttons to be all the same size **only when the user is logged in from a mobile screen**. The change of the UI can be seen below:

![new issue after](https://github.com/TEAMMATES/teammates/assets/95168947/55a64897-feaf-4787-ad6d-0693cd54a217)

**Justification**
The instructors will benefit from this change as the page seems more "clean" , organized, and professional. I added a css class where the size of the button (width and height) can change so that the button can become smaller or larger if it is required by the TEAMMATES team, and I also added the necessary code so that the respective buttons refer to the respective css class

**Comment by weiquu** [comment]
Thanks @athakaras for raising this issue! I think in addition to changing the size, we could also add some spacing between the buttons so that [users can more easily tap them on mobile devices](https://teammates.github.io/teammates/best-practices/mobile-friendliness.html). Perhaps a more appropriate issue title would then be "Make the instructor student buttons easier to use on mobile devices".

Also worth to check if this issue is present in other tables, since I assume the fix would be essentially the same.

**Comment by athakaras** [comment]
@weiquu shall I raise a PR for this issue with the suggested changes?

**Comment by weiquu** [comment]
Hi @athakaras, yup please go ahead!

**Comment by athakaras** [comment]
@weiquu okay! I have also found a similar issue for the home page of students. Should I open a different issue and PR for this?

**Comment by weiquu** [comment]
Thanks @athakaras for checking! Took a quick look and I think the issue and fix is more or less the same, so let's keep to 1 PR

**Comment by athakaras** [comment]
@weiquu just raised the respective PR :)
