### ISSUE TITLE
Edit student

### ISSUE THREAD

**Issue by edilbertocantuaria** [TEAMMATES/teammates#12451]
The function that allows **editing a student** has some errors: The fields "name," "section," and "team" allow the input of numbers, which means it is possible to register a name like 123. The same applies to the "section" and "team" fields. Additionally, the "email" field allows the input of email addresses with special characters, such as `something{here@mail.com`.

**Comment by wkurniawan07** [comment]
"Name like 123" is not necessarily a mistake. Weird usage, many would think (although I wouldn't rule out the possibility that there is someone named entirely with numbers, somewhere in this world), but not something that would lead to system error.  Sections and teams named entirely with numbers are valid and can never have this restriction.

Email, on the other hand, has been a very contentious matter for years (if not decades). Special characters don't necessarily make an email invalid as there is no definite RFC on that matter; the email `something{here@mail.com` could very well be a valid address depending on the email provider.
The domain part (`@mail.com` in this case), on the other hand, is indeed something that can use more validation (`something.here@mail}.com` is definitely invalid), but the value-add is quite minor here as (1) the chance of misuse/mistake is very low, and (2) any intentional misuse would only harm the abuser.

Close as not planned.
