### ISSUE TITLE
Clarify masquerade mode in docs 

### ISSUE THREAD

**Issue by NicolasCwy** [TEAMMATES/teammates#12466]
The [docs](https://teammates.github.io/teammates/development.html#logging-in-to-a-teammates-instance) on masquerade mode is unclear on what username is on the development server 

`When logged in as administrator, masquerade mode can also be used to impersonate instructors and students by adding user=username to the URL e.g http://localhost:8080/web/student/home?user=johnKent.`

Developers who want to use masquerade mode have to ensure that the`username`  is the email address used to verify the user e.g (person@x.com) when signing up mock instructors. Username such as jack (for google id jack@example.com) would not work as the username.

![image](https://github.com/TEAMMATES/teammates/assets/25302138/cff2d547-3e57-4a12-b67d-0904f9245976)
Signed up jack@example.com as instructor, which is also used as google id

![image](https://github.com/TEAMMATES/teammates/assets/25302138/355ca06c-c467-45b7-8bb4-8ab63658bfcc)
Incorrect username used (jack)

![image](https://github.com/TEAMMATES/teammates/assets/25302138/0744fbfc-7c36-4b6d-84a1-a877d6c1f2e3)
Correct username used (jack@example.com)

**Comment by wkurniawan07** [comment]
Remnant of #11586.

Now that I see this page again, we might need to reword "Google ID" in places where they are used, because once Firebase is integrated (it already is, but not actually used yet) that term will stop making sense.

But don't let that be a distraction; this issue simply calls for documentation update.

**Comment by domlimm** [comment]
Should we also add steps to how one can use the masquerade feature? There was a recent discussion [here](https://github.com/TEAMMATES/teammates/discussions/12433#discussioncomment-5933766).

**Comment by NicolasCwy** [comment]
> Should we also add steps to how one can use the masquerade feature? There was a recent discussion [here](https://github.com/TEAMMATES/teammates/discussions/12433#discussioncomment-5933766).

Yup this sounds like a good idea, it has always been a point of confusion for me. Perhaps we can add the instructions in a new section and link the existing reference in this post to it

**Comment by domlimm** [comment]
@NicolasCwy alright! Should we do it in the same PR that solves this current issue?

**Comment by NicolasCwy** [comment]
@domlimm Yup if possible, it would be good

**Comment by domlimm** [comment]
Apologies for spamming up this issue.

@NicolasCwy On second thought, let's open up another issue as a good first one. It might be rather complex for the current author of the PR to try it out and add the docs.

Do you reckon we should add a new sub-section between `Logging in to a TEAMMATES instance` and `Logging in without UI`?

![image](https://github.com/TEAMMATES/teammates/assets/46486515/a56cd901-371f-4613-a665-cbd4d1d1f295)

**Comment by NicolasCwy** [comment]
@domlimm Ok sounds good to me. I think we can put it after the login without UI, so we can group the login docs together. Then we can link the current snippet on masquerade to the new section which elaborates on how to use masquerade

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by jasonqiu212** [comment]
Hi @vimalJD, Yes this issue is still open! Feel free to submit a PR for it :)

Just to reiterate the main problem in this issue:

`When logged in as administrator, masquerade mode can also be used to impersonate instructors and students by adding user=username to the URL e.g http://localhost:8080/web/student/home?user=johnKent.`

The above line in the [docs](https://teammates.github.io/teammates/development.html#logging-in-to-a-teammates-instance) (Under the "As administrator" dropdown panel) is unclear on what `username` is. 

Since we now have a [section](https://teammates.github.io/teammates/development.html#masquerading-as-another-user) dedicated to explaining how to use masquerade mode in detail (#12506), a simple solution to this issue is:
- Replace the problematic line above with a link to the new section
