### ISSUE TITLE
Fix running of component tests using Windows Powershell

### ISSUE THREAD

**Issue by NyndoND** [TEAMMATES/teammates#12481]
I followed the developer guide provided in the project documentation, but when I run the command to check the code line coverage of the tests, I get the following error: 
I try to run: ./gradlew componentTests
and: ./gradlew componentTests jacocoReport 

![image](https://github.com/TEAMMATES/teammates/assets/64983769/237421e0-d3cb-483f-9f5b-022ec191be89)
Guide link I followed: https://teammates.github.io/teammates/development.html

**Comment by guilherme-puida** [comment]
This happens when running the `componentTests` under Powershell. The `del` command only exists in `cmd`, so it errors out when trying to delete temporary files created by the `afterTestClosure` in `build.gradle`.

A simple fix would be changing the `afterTestClosure` to be more shell-agnostic. I'll open a PR fixing this in a few moments :^)
