### ISSUE TITLE
InstructorCourseView: 'send invite' should not reset the sort order

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1753]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 27, 2014 16:10:58_

Currently, clicking the 'send invite' line causes the page to reload, and sort order to go back to the default.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1756_

**Comment by VamsiSangam** [comment]
This issue is not yet fixed. Upon clicking "Send Invite" in ```/page/instructorCourseDetailsPage``` this JS is executed -

``` javascript
function attachEventToSendInviteLink() {
    $('.course-student-remind-link').on('click', function(event) {
        event.preventDefault();

        var $clickedLink = $(event.target);
        var messageText = 'Usually, there is no need to use this feature because TEAMMATES sends an automatic '
                          + 'invite to students at the opening time of each session. Send a join request anyway?';
        var okCallback = function() {
            window.location = $clickedLink.attr('href');
        };

        BootboxWrapper.showModalConfirmation('Confirm sending join request', messageText, okCallback, null,
                BootboxWrapper.DEFAULT_OK_TEXT, BootboxWrapper.DEFAULT_CANCEL_TEXT, StatusType.INFO);
    });
}
```

It pops up a modal for confirmation and upon approval the ```window.location``` causes the page to load over again which resets the sorting. The ```window.location``` sends a request to ```/page/instructorCourseRemind``` which redirects back to the ```/page/instructorCourseDetailsPage```.

My proposed solution is that instead of using ```window.location``` we could send an AJAX request so that the page doesn't reload, thus preserving the sort. So the new function in ```okCallback``` must send an AJAX request to ```$clickedLink.attr('href')``` and display the success status message to user if everything is all right. But I'm not sure exactly how can we check if the AJAX request was successful one.

**Comment by VamsiSangam** [comment]
Can I work on this issue?

**Comment by damithc** [comment]
> Can I work on this issue?

Sure @VamsiSangam .
