### ISSUE TITLE
Instructor: add instructor to course: show instructors in alphabetical order

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2203]
~~It is more intuitive if the new instructor is added to the bottom of the list~~

It is better if the instructor list is shown in alphabetical order. Even better if we auto-scroll to the the new instructor after adding a new instructor.

**Comment by chanjunweimy** [comment]
Dear prof,
I have tried to run the localhost and saw the "add new instructor" is already at the bottom of the list. 

![addnewinstructoratbottom](https://cloud.githubusercontent.com/assets/7464833/6820991/e660e952-d30e-11e4-838d-b94223bbf095.PNG)

Is this issue closed or it needs to be added to the top of the list? 

Thank you.

Regards,
Jun Wei

**Comment by damithc** [comment]
No that's not what this is about.
Add a second instructor. The 2nd instructor appears at the top of the
instructor list instead of the bottom. It is more intuitive if the new
instructor appears at the bottom of the list.

**Comment by chanjunweimy** [comment]
Prof,

Thanks for your clarification. I got it now. I will start working on it. 

Regards,
Jun Wei

**Comment by chanjunweimy** [comment]
Is the role "observer" cannot "view details"? I can't view that details, other is fine.

**Comment by chanjunweimy** [comment]
And according to observation, I realize the new instructor need not be added to the top, their placement is according to their "email".

![addnewinstructor1](https://cloud.githubusercontent.com/assets/7464833/6825617/cc733f40-d336-11e4-9732-1c014f980fd2.PNG)

Initially I only have 1 instructor and his email is :
teammates.instructor@......

Then I try to add another instructor whose email is:
zzz@zzz

Then this is what happened:
![addnewinstructor2](https://cloud.githubusercontent.com/assets/7464833/6825671/2ba227ec-d337-11e4-9894-fad52b87a253.PNG)

Note that the instructor whose email is zzz@zzz is added below the instructor whose email is teammates.instructor@......

Then I try to add another instructor whose email is:
aaa@aaa

Then this is what happened:
![addnewinstructor3](https://cloud.githubusercontent.com/assets/7464833/6825711/6ec8f186-d337-11e4-9ccf-c29feb54b97c.PNG)
The instructor whose email is aaa@aaa is now at the first place.

To confirm what I observe is correct, I dig through the code:
![addnewinstructorcode](https://cloud.githubusercontent.com/assets/7464833/6826298/68e6a5c0-d33b-11e4-91dc-95e5e63f20e6.PNG)

If I din understand wrongly, when the email is keyed in correctly:

            data.instructorList.add(logic.getInstructorForEmail(courseId, instructorEmail));

the instructorList is added according to the instructor Emails, and I not sure is it because the db returns the email in ascending order..

If I am correct, then I not sure how to edit to make this thing works,,,

***Please correct me if I am wrong***

Thanks a lot,

Regards,
Jun Wei

**Comment by kanghj** [comment]
@chanjunweimy, if you are still not sure about how to fix this issue, you can look for another one?

**Comment by chanjunweimy** [comment]
@kanghj , hi, thanks for your reply. :) Actually what I am trying to ask is, should I change the ui display algorithm in order to solve this issue, or I could just make a pull request to try solving it first?

**Comment by chanjunweimy** [comment]
There is 1 way I could think of is adding a "joiningDate" attribute (indicate which date the instructor/tutor has joined the course) for InstructorAttribute, and when the storage return, it return the result sort by the joiningDate. Then whenever we add the instructor, it will appear at the bottom of the list. Is the way ok? Or I should think of another way for it?

**Comment by kanghj** [comment]
Currently, a new "joiningDate" attribute just to fix this issue might be a bit too excessive and not worth the effort? Try to find another method instead.

**Comment by chanjunweimy** [comment]
Thank you for your reply, @kanghj 

Hmm.. I thought of another method that might achieve a slightly different result but could consider as a fix for this issue, which is: through caching the InstructorAttribute in InstructorLogic. The goal is: to identify which is the new instructor that is added, and I switch it to the bottom of the list. The caching method should look like this:

I would save the courseId as the key of a hashmap, then the value of the hashmap would be the InstructorAttribute. Everytime I add a new instructor, as the instructor is not in the "cache", it will append to the bottom of the list. 

To get a more accurate result, we could add an attribute "joiningDate" or by using another hashmap to save the "joiningDate" attribute. Is this method ok? :)

Thank you.

Regards,
Jun Wei

**Comment by damithc** [comment]
Instructor objects don't have a createdAt field? If not, we can add it.

**Comment by chanjunweimy** [comment]
Ok, I will work on creating the createdAt field

**Comment by mukesh14149** [comment]
@damithc "createdAt" field you mean joining date for a instructor in a course?

**Comment by damithc** [comment]
> And i think it is more convenient to show instructor list by sorting because after adding instructors when instructor came to this page again he does not going to bother which instructor joined at which date if he wanted to edit any instructor he just visually search by email.
> What do you think sir?

Yes, I think we can show instructors in alphabetical order instead. Even better if we can scroll to the newly-added instructor.

**Comment by amarlearning** [comment]
Taking this one

**Comment by amarlearning** [comment]
Taking this one
