### ISSUE TITLE
Instructor: edit questions: give more recipient type options

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2488]
Suggested by a user:
My suggestion is about the “feedback recipient” field. As it stands, we have this useful option “Giver’s team members and Giver”, which allows for simultaneous self- and peer-assessment. However, there is no equivalent option for the other types of recipient. In other words, I think you should add the following options:

·         Other students in the course, and Giver

·         Other teams in the course, and Giver’s team

**Comment by samuelfangjw** [comment]
Hi, is this issue still relevant? Seems like we already have a pretty comprehensive range of common feedback paths to choose from, although the two mentioned by the user in the original post "Other students in the course, and Giver" and "Other teams in the course, and Giver’s team" do not seem to be one of the common feedback paths.

<img width="785" alt="Screenshot 2021-08-03 at 5 24 14 PM" src="https://user-images.githubusercontent.com/60355570/127992261-d332fd00-365a-4d8b-880b-844361619d0a.png">

**Comment by damithc** [comment]
@samuelfangjw I think adding those options can be useful, specifically, to this dropdown.

![image](https://user-images.githubusercontent.com/1673303/128050297-a0467ad5-5175-4e79-b6c1-0adbb26315cb.png)

**Comment by samuelfangjw** [comment]
Hi, I looked into this issue but am currently a little unsure of the appropriate way to approach this issue.

Currently, `STUDENTS` in `FeedbackParticipantType` enum seems to have different meaning depending on context.

When selecting feedback path:
`STUDENTS`: Students excluding self
`STUDENTS_EXCLUDING_SELF`: not used

When generating options for MCQ & MSQ:
`STUDENTS`: Students including self
`STUDENTS_EXCLUDING_SELF`: Students excluding self

I would like to add a constant representing "students including self" when selecting feedback path.

The easiest solution seems to be to add `STUDENTS_INCLUDING_SELF` constant (for use when selecting feedback path), but this might not be ideal because it will result in 3 different constants to represent two possible states depending on context, which could be confusing. Ideally we might have `STUDENTS` represent students including self and `STUDENTS_EXCLUDING_SELF` to represent students excluding self, but I'm not sure if it's feasible to make this potentially breaking change.

Thanks in advance for any advice on this!

**Comment by xyliew25** [comment]
I've also looked into the code, and yes, I agree with @samuelfangjw that the ideal solution proposed is potentially change-breaking since `STUDENTS` is widely used, and is used in feedback path selection and options generation with different definitions. However, I think it is worth a try. Any advice?

**Comment by wkurniawan07** [comment]
This is unfortunately a legacy mistake that we have to undo. But we cannot just recklessly change the definitions; we need to do it in steps:
1. For feedback path, modify the code such that the previously unused `STUDENTS_EXCLUDING_SELF` enum indicates exactly what it is named, but keep `STUDENTS` similarly defined. This will be the brief period whereby "old definition" and "new definition" exists; existing data will still follow the former, but all newly added data will follow the latter.
2. Write and run a data migration script to migrate all `STUDENTS` to `STUDENTS_EXCLUDING_SELF`.
3. Remove the code that interprets `STUDENTS` as "students excluding self". This frees up `STUDENTS` enum to be used for other purposes.
