### ISSUE TITLE
Instructor: download results: constant sum questions: give total per student and individual values

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2676]
Current: only the average is given.

![image](https://cloud.githubusercontent.com/assets/1673303/25771070/6d524afc-3279-11e7-9582-5ab14388ae2d.png)

Suggestion: Give total and the individual values received by that student. e.g.
![image](https://cloud.githubusercontent.com/assets/1673303/25771078/bd503ae6-3279-11e7-935f-ea3ee16cc914.png)

**Comment by yasirunilan** [comment]
can you explain more about this issue?

**Comment by damithc** [comment]
@yasirunilan can post a screenshot of the current situation of the relevant section of the results page? I can explain based on that screenshot.

**Comment by nikiforosbotis** [comment]
Dear @damithc : I am interested in that issue but I am not sure that I have correctly understood what you want. I follow the advice that you gave to the guy above, in order to explain me better. 

This is the screenshot of the corresponding web page:
![a](https://cloud.githubusercontent.com/assets/9116253/24241596/9e0d1bb8-0fb5-11e7-81b7-d46929f4eb2c.png)

And this is the one of the downloaded results (excel):
![b](https://cloud.githubusercontent.com/assets/9116253/24241603/a6a19c9a-0fb5-11e7-95f1-5f401f89e386.png)

Thank you.

**Comment by damithc** [comment]
@nikiforosbotis 
This issue is about 'constant sum' type questions (i.e. divide a fixed number of points among recipients). The question shown in your screen shot is of type 'team contribution'.

**Comment by nikiforosbotis** [comment]
@damithc Got it. 
This is the corresponding screen, right?
![a](https://cloud.githubusercontent.com/assets/9116253/24376274/fe013d38-1343-11e7-9b10-48f53c8e3a7a.png)

**Comment by shrut1996** [comment]
@damith Do you mean that the section under 'Response Summary' requires an extra column named 'Total' that gives the total of all points received? 

![screenshot from 2017-04-05 00-14-36](https://cloud.githubusercontent.com/assets/20799404/24673307/56133872-1967-11e7-991d-625fa3064098.png)

**Comment by nikiforosbotis** [comment]
@shrut1996 I would be glad if you let me some time to work on this issue. I have already started :)

**Comment by shrut1996** [comment]
@nikiforosbotis Sure no problem :+1:

**Comment by nikiforosbotis** [comment]
@shrut1996 thank you! If I face any difficulty or decide that I will not proceed with completing that, I will let you know.

**Comment by Mynk96** [comment]
@damithc is this how, change in summary section should look like?
![summary](https://cloud.githubusercontent.com/assets/17481466/24738666/d4855fb6-1ab4-11e7-8864-35bd25bc8a53.PNG)

here total looks is sum of all the values recieved in that section by the student

**Comment by AnaghHegde** [comment]
@damithc Like @shrut1996 said we need to add a extra column right ?.

**Comment by damithc** [comment]
> @damithc Like @shrut1996 said we need to add a extra column right ?.

Yes.

**Comment by shrut1996** [comment]
@AnaghHegde @nikiforosbotis Anyone working on this?

**Comment by AnaghHegde** [comment]
Yes. I am working on this.

**Comment by shubham49** [comment]
@AnaghHegde  if you are not working on this, can I do this?

**Comment by shubham49** [comment]
@damithc  Received points are now present in the csv file. But their order doesn't seems to be fine.

![image](https://user-images.githubusercontent.com/10528953/27478912-3c3b009a-582f-11e7-9995-06af26b7c033.png)

In this screenshot, received points are displayed in different columns rather than same column.
I think it should look something like this
![image](https://user-images.githubusercontent.com/10528953/27478997-8926c678-582f-11e7-916e-f68108c2ee0e.png)

Any suggestions?

**Comment by damithc** [comment]
> @damithc Received points are now present in the csv file. But their order doesn't seems to be fine.

It was a deliberate decision to put one value per cell. It's easier to do further processing that way e.g. apply excel formulas.

**Comment by shubham49** [comment]
okay. So should this issue be closed or something needs to be done?

**Comment by damithc** [comment]
> okay. So should this issue be closed or something needs to be done?

Thanks for investigating this issue @shubham49 Yes, it should be closed.
