### ISSUE TITLE
adminActivityLog: instructorStudentRecordsPage links shown in the activity log loads an unformatted page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2834]
When I click on such a link it goes to a pages such as this `https://teammatesv4.appspot.com/page/instructorStudentRecordsPage?courseid=FMIB2&studentemail=skusumo2015@student.hult.edu&user=abc&fsname=efg` but the loaded page is not formatted. Just black text with white background.

**Comment by xpdavid** [comment]
@damithc I am not sure whether the issue is still valid (I have checked the current version, it returned a formatted page). Maybe you mean `instructorStudentRecordsAjaxPage` rather than `instructorStudentRecordsPage `? (For the previous one, as it uses Ajax to get data from server, the response will be unformatted page)
![screen shot 2017-02-03 at 8 22 53 pm](https://cloud.githubusercontent.com/assets/13977235/22591260/942eb9ee-ea4e-11e6-9047-43435f2db03b.png)

Maybe previously `InstructorStudentRecordsPage` responses ajax request **and** also creates showPageResult.

**Comment by damithc** [comment]
Good catch @xpdavid Thanks for investigating. 
Yes, you are right. Closing.
