### ISSUE TITLE
Instructor: view results: improve display format for questions with no specific recipient

### ISSUE THREAD

**Issue by ryancyq** [TEAMMATES/teammates#2844]
When general is the recipient, recipient name and team name are "-".

![untitled](https://cloud.githubusercontent.com/assets/6453214/5641120/e3aef106-966c-11e4-9835-34883623b1d8.png)

The following pic is even more confusing for "- Received Response.." and "- Detailed Response"
![untitled2](https://cloud.githubusercontent.com/assets/6453214/5641143/5f3c291a-966d-11e4-9884-edcce98ddf99.png)

**Comment by yj-soh** [comment]
The "-" comes from `Const.USER_NOBODY_TEXT` which is used in `FeedbackSessionResultsBundle` as a replacement for empty email addresses, names, and team names. It's also used in other two files for questions involving anonymity.

I believe it might be a good idea to separate the constants used for an empty person name and an empty team name, at least, due to the difference in representation on the UI.
Alternatively, it can be dealt with on the JSP side with an if statement.

Would "No Team" do? "Anonymous" seems viable too. On a side note, we have no reversed keywords for the team field as far as I've searched.

**Comment by damithc** [comment]
"No Team" and "Anonymous" can be chosen by students as team names. We
should choose a constant that is unlikely to be a real team/student name.
e.g. %noteam%

**Comment by kanghj** [comment]
Changing the value of Const.USER_NOBODY_TEXT might not be the best fix for this issue as this issue is only concerned with responses to "Nobody specific(for general class feedback)". For these responses, the value of the recipient is already stored as a constant "%GENERAL%", and not as "-" or an empty name. It's displaying "-" as the team name because in <code>FeedbackSessionResultsBundle</code>, <code>getTeamNameForEmail </code> returns "-" if "%GENERAL%" is passed in.

**Comment by yj-soh** [comment]
Yes, changing `USER_NOBODY_TEXT` is definitely not the best solution considering its variety of usage. I can think of two feasible methods.

The first would be to change `getTeamNameForEmail` (perhaps with `getTeamNameFromRoster` too) which will propagate the change in team name to the `Feedback*Details` classes, including the .csv downloads. Making it return a different string for `general`-type questions is trivial. A possible problem is that it might cause sorting issues as the sorting will be done based on the altered team name, but this can be averted by using a first character with roughly the same priority as "-". Thus, I would personally recommend this choice.

The second would be to handle the checking in the .jsp files. This will reduce any side-effects to only the UI, but it involves hardcoding the variables (or referencing `Const`) which isn't good for extensibility as it assumes such questions will remain in a certain format. I honestly don't believe in placing too much checking on that layer in any case.

I've considered changing it in the logic package, but the changes will be too widespread and likely disrupt other subcomponents.

On another note, regarding what to change it to, I believe any string beginning with a non-alphanumerical character would do fine as team names cannot be set to start with one. I threw together [a simple mockup](http://codepen.io/anon/pen/gbEdqa) for ease of reference and think "[NoTeam]" works best from the PoV of a user (in terms of aesthetics and accessibility).

**Comment by damithc** [comment]
An overall comment: The string we use internally to identify something need not be the same as what we display. The internal string should be chosen to eliminate collisions with strings chosen by users. The external string should read well as normal English and self explanatory. Something like "[noteam] Received Responses Statistics" doesn't read well.

**Comment by jayasting98** [comment]
Hi I think this issue has already been solved in PR #10762.

**Comment by wkurniawan07** [comment]
Closing as issue has been resolved
