### ISSUE TITLE
Instructor: session results: contribution questions: show 'Not Sure' as 'Not Sure' instead of 'N/A'

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#2908]
As per title

**Comment by damithc** [comment]
Example:
Submission:
![image](https://cloud.githubusercontent.com/assets/1673303/25885302/50529eb6-358a-11e7-83c3-48dd7c30f917.png)

Current (when instructor view results):
![image](https://cloud.githubusercontent.com/assets/1673303/25885332/742d1b4a-358a-11e7-8b5d-42510bb9e2c1.png)

Expected:
Show 'Not Sure' instead of 'N/A'

**Comment by ahsanbagwan** [comment]
I will look at this as soon as I'm done with this [issue](https://github.com/TEAMMATES/teammates/issues/7934)

**Comment by damithc** [comment]
> @damithc Sir, Can I work on this issue?

Sure, you can give it a try. But note that we have marked this as `d.Committers` because the fix might not be easy.

**Comment by nidhi98gupta** [comment]
@damithc Apologies for the delay. I made changes to this function
`private static boolean isSanitized(int i) {`
`   return i != NSB && i != NSU;`
`}`
which is in `src/main/java/teammates/common/datatransfer/TeamEvalResult.java`
by changing it to `return i != NSB;` and making other related changes. It is working as expected.
Currently we are assigning `NA` to all the cases where response is either "Not Sure" or "Not Submitted".
Before making a pull request, I wanted to confirm if there is a reason for checking isSanitized() that I have overlooked.
