### ISSUE TITLE
Instructor: can add a message to the 'results published' email message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#2988]
This allows instructors to specify instructions on how to use the published results

**Comment by karan173** [comment]
@damithc Can you clarify whether my understanding of the issue is correct?
We want to give the instructors the ability to add a custom message to the results published email. The instructor will click on publish, and then they will be asked to add a custom message optionally. Then this message will be appended to the results published email.

**Comment by damithc** [comment]
Yes, that's the idea.

**Comment by damithc** [comment]
In general, we can allow users to add content to different emails sent by TEAMMATES. This may be useful for non-English speaking users. The instructor can add stuff using their own language.
