### ISSUE TITLE
User must be alerted about being logged out while requesting the TEAMMATES Homepage

### ISSUE THREAD

**Issue by dg711** [TEAMMATES/teammates#3049]
There is no alert message that tells the user that he/she would be logged out when visiting the TEAMMATES homepage . 
For eg. , When a user requests the TEAMMATES homepage to watch the video tour video he/she is logged out automatically without any alert message .

**Comment by damithc** [comment]
I don't think the user is logged out. The user can go back to the app by clicking on 'Student login' or 'Instructor Login' links, without having to login again. The back button should do too. However, the user might mistakenly thing that he/she has been logged out. We can do something to avoid that.

**Comment by thyageshm** [comment]
shoud we consider modifying the homepage to become a jsp so that we can keep the login information there too?

**Comment by drunken-saint** [comment]
:+1:  to that .

**Comment by MrFool** [comment]
Always felt this button to be confusing when I was using Teammates during my 2103 semester, the reason is because on most website the top left most button defaults to "home page" and less of "index page" which is meant for introduction to non signed up users, I'd expect clicking that button to bring me to "Student Home Page" back then. Not sure what the best solution for this is though, perhaps when we migrate the non logged in pages to bootstrap we can also tackle this issue along with that.
