### ISSUE TITLE
The warning says 'view by section', although there are no sections in the course

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3152]
This can happen when the course is small but the session has lot of questions and lot of responses.

**Comment by damithc** [comment]
Actually, it's just the status message that is slightly incorrect. The functionality is not broken. Lowering the priority.

**Comment by NisalaNiroshana** [comment]
Hi,
I am willing to fix this issue.Can you assign it to me and give me a description about the implementation of it ?? 
Thanks,
Nisala

**Comment by kanghj** [comment]
@NisalaNiroshana, you have completed a few issues already and you are at step 6 of the [instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true), so from this point on, you can just submit pull requests although we no longer promise to review or merge your changes.

**Comment by NisalaNiroshana** [comment]
@kanghj , Thanks for the information. I am really interested in your project and willing to work with you in the future. Since I am very much like to contribute to open-source projects , I like to contribute to your project further more.So If you do not mind , Please provide me with little description about this issue. I am willing to fix it. Then you can review it and merge it ,If my implementations are up to your standards.

Thanks,
Nisala

**Comment by kanghj** [comment]
@NisalaNiroshana, this issue is about the error message "This session seems to have a large number of responses. It is recommended to view the results one section at at time" appearing when there are no sections in the course.

**Comment by NisalaNiroshana** [comment]
I just completed my intership programme. Now I can fully contribute to the project.I went throgh your comments.but i did not find error message..Can you help me ?? thanks

**Comment by kanghj** [comment]
You can look for another issue to try if you cannot figure out what to do for this issue
