### ISSUE TITLE
Instructor: edit student data: fix typo in error message for team/section name

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#3436]
...All a team name must ...

Should either be: A team name must ...
or: All team names must ...

![image](https://cloud.githubusercontent.com/assets/3910365/7699253/3113aba0-fe49-11e4-8fa2-f40206fad319.png)

**Comment by MrFool** [comment]
Fixing this can cause "typos" in other error messages such as ->

![screen shot 2015-06-08 at 5 21 07 pm](https://cloud.githubusercontent.com/assets/6291947/8031671/eb0ac124-0e02-11e5-910d-be782010a8e9.png)

because the field validator messages concatenates strings and uses it for all name field validations.

**Comment by damithc** [comment]
@YongJieYongJie this issue must be fixed now, am I right?

**Comment by YongJieYongJie** [comment]
@damithc Now that `FieldValidator` is slightly tidier, we can rephrase the error message to avoid such problems, something like:

"|" is not acceptable to TEAMMATES as a/an team name because it starts with a non-alphanumeric character. Every team name must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).

**Comment by damithc** [comment]
Sure, we should improve the error message if we can.

**Comment by amarlearning** [comment]
@damithc Is this issue still open?

**Comment by damithc** [comment]
Yes. I think it is easier to phrase it as `A team name must start with` etc.

**Comment by amarlearning** [comment]
working on this

**Comment by amarlearning** [comment]
@damithc Looked in the `FieldValidator.java` file and found out that " _Every field which contains (%) and (|) as input will be considered as invalid input_ ".

The general error message for such input is `All ${fieldName} must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).`

Solution:

1. If I change `All` -> `A`, it will then be applied to all input field.
2. Rephrase the invalid message just for the team name. (`A team name must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).`)

Any suggestions?

**Comment by damithc** [comment]
Option 1 is better, as long as it works for all fields.

**Comment by LiHaoTan** [comment]
@damithc can we change `All` to `The` instead because some of the field names have vowel sounds, 
Example:
> "Institute|" is not acceptable to TEAMMATES as a/an institute name because it contains invalid characters. **The** institute name must start with an alphanumeric character, and cannot contain any vertical bar (|) or percent sign (%).

**Comment by whipermr5** [comment]
@LiHaoTan `The` doesn't sound right; maybe we can use `A/an` like in the previous sentence (though it's ugly)? Ideally we should do vowel sound detection.
