### ISSUE TITLE
Typical data bundle wrong question Id (Grace Period response)

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3570]
Will fix as part of #3568 , was using that to test and found the error

**Comment by MrFool** [comment]
![screen shot 2015-05-29 at 6 42 21 pm](https://cloud.githubusercontent.com/assets/6291947/7881160/76868ee6-0632-11e5-9dbe-3f4a70e87efc.png)
![screen shot 2015-05-29 at 6 42 10 pm](https://cloud.githubusercontent.com/assets/6291947/7881161/76af9a70-0632-11e5-9a8b-30deafbc3531.png)
![screen shot 2015-05-29 at 6 41 49 pm](https://cloud.githubusercontent.com/assets/6291947/7881162/76b54eca-0632-11e5-9e81-f255574ecd7e.png)

**Comment by MrFool** [comment]
Once I finish the refining I'll ask run the entire test suite to ensure that this fix did not cascade and affect the other tests that uses typical data bundle

**Comment by MrFool** [comment]
Been digging into this for awhile now, but haven't been able to get a proper solution.

![screen shot 2015-05-29 at 10 49 30 pm](https://cloud.githubusercontent.com/assets/6291947/7885182/09b0b85a-0655-11e5-9889-e5862622876f.png)
![screen shot 2015-05-29 at 10 49 06 pm](https://cloud.githubusercontent.com/assets/6291947/7885183/09b469e6-0655-11e5-83b8-ee32f8d35b4d.png)
![screen shot 2015-05-29 at 10 48 49 pm](https://cloud.githubusercontent.com/assets/6291947/7885185/09b91d9c-0655-11e5-81b2-2debd165a9a1.png)
![screen shot 2015-05-29 at 10 48 44 pm](https://cloud.githubusercontent.com/assets/6291947/7885184/09b7e09e-0655-11e5-95fb-8759e0a0e140.png)
![screen shot 2015-05-29 at 10 48 27 pm](https://cloud.githubusercontent.com/assets/6291947/7885186/09bc27d0-0655-11e5-8b47-2532a91b86f1.png)

**Comment by MrFool** [comment]
Then now, this is the next problem because of the above ->

In #3568 I'm trying to test a student saving a grace period response.

![screen shot 2015-05-29 at 10 57 36 pm](https://cloud.githubusercontent.com/assets/6291947/7885388/2980d0a6-0656-11e5-9963-2dcc62892a19.png)

Using the typical data above and the code above, we try to access question 2's response as per the original typical data bundle which labels the response of student 4 -> team 1.2 as with qn id 2.

This results in an error because if we look at question 2 of grace period session, it says it's for the instructor to self and so doesn't go through.

However, if we change the json bundle to the correct id (aka labelling the response of student 4 -> team 1.2 as with qn id 1), this test pass as expected because it is now truly trying to save the grace question as in the right question.

**Comment by MrFool** [comment]
So, if we change it to the right id, one test fails, if we change it to the right id, one of the branch is not covered as in

![screen shot 2015-05-29 at 11 03 16 pm](https://cloud.githubusercontent.com/assets/6291947/7885523/ec6eda4a-0656-11e5-879d-e0df8fdbe798.png)
