### ISSUE TITLE
Sample course: fine tune session status

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3590]
When we create a new instructor, we create a sample course in his/her account.
The open session in that course should be set to 'publish manually' (i.e. not published yet) because it is not usual for open sessions to be 'published'.
![image](https://cloud.githubusercontent.com/assets/1673303/25890414/f1566620-359f-11e7-96ec-ecf081a3eb47.png)

**Comment by huai99** [comment]
@damithc  Hi, I would like to solve this issue, but first I would like to clarify something from you. Because from my local machine, I could not see the button that allows me to perform any action at the Actions column. Below attached the image that I saw:
![image](https://user-images.githubusercontent.com/26456025/28321642-5722db5e-6c06-11e7-8496-d871dd684e53.png)
So, can you let me know what steps should I take to go to the page that you shown? Thanks !

**Comment by damithc** [comment]
@huai99 that action now appears under the `Results` button.

**Comment by huai99** [comment]
@damithc  Ok, thanks for the clarification, so what you hope to see is that the initial status for the feedback session should be unpublished when we create a new instructor ? Am I right ?

**Comment by damithc** [comment]
Yes. It should not be published yet.
