### ISSUE TITLE
InstructorHomePageUiTest failing on the live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3641]
failing at 
`258: homePage.verifyStatus(Const.StatusMessages.FEEDBACK_SESSION_REMINDERSEMPTYRECIPIENT);`

**Comment by damithc** [comment]
Failed after repeated attempts. Not a recent failure. Have been failing for a while.

**Comment by MrFool** [comment]
What's the failure cause for this? Wrong status or?

**Comment by damithc** [comment]
Try running against your staging server and see if it can pass. -damith
(sent from my iPhone)
>
>

-- 
Sent from a mobile device.

**Comment by MrFool** [comment]
So, I found the cause for this but I can't exactly show how to replicate it with pictures due to the nature of this bug, we need to fix this via 2 different issues, I'll explain.

![screen shot 2015-06-09 at 9 34 35 am](https://cloud.githubusercontent.com/assets/6291947/8048957/c89f4906-0e8a-11e5-8d0a-87a21b05355c.png)
![screen shot 2015-06-09 at 9 34 28 am](https://cloud.githubusercontent.com/assets/6291947/8048958/c8a00aa8-0e8a-11e5-988e-f20ce530f9b8.png)
![screen shot 2015-06-09 at 9 34 21 am](https://cloud.githubusercontent.com/assets/6291947/8048960/c8a44406-0e8a-11e5-9cf3-941e95f02fac.png)
![screen shot 2015-06-09 at 9 34 13 am](https://cloud.githubusercontent.com/assets/6291947/8048959/c8a43632-0e8a-11e5-938b-ec38c42d6484.png)


Following the normal flow and not selecting any students, we get the desired response.

However, try this, instead of waiting for the students list to load, go ahead and click "remind" while the server is still loading the student list. It will trigger and result in this page.

![screen shot 2015-06-09 at 9 36 05 am](https://cloud.githubusercontent.com/assets/6291947/8048970/f7cc017e-0e8a-11e5-8b5e-2c1550079390.png)

Might take a few tries, you have to be REALLY fast - the problem is that Selenium is REALLY FAST.

And this is the code snippet made to do this test.

![screen shot 2015-06-09 at 9 36 41 am](https://cloud.githubusercontent.com/assets/6291947/8048978/0e9d199c-0e8b-11e5-825f-a256265a6148.png)

It looks for the button and clicks it without waiting for the student list to load via AJAX.

On staging / live server, the list might take awhile to be loaded because staging / live doesn't respond as fast as dev server on localhost.

And that is why we always fail this test.

I propose we fix this sequentially, first by disallowing the form from being submitted before the student list is loaded via AJAX, i.e. disable the button and only enable it upon completion of AJAX. It is entirely possible that a user might actually click remind (by accident or what not) without having waited for the student list to appear (due to some slowness or something else) and it would be not so nice to show an error page. This fix will also help us to fix this the test.

In that, we can then tell Selenium to look for the button that is not disabled (before AJAX is completed, Selenium will not find it and we can tell it to look for it up to 10 seconds), once it finds it, the student list would have been loaded and we will not meet this situation again.

**Comment by damithc** [comment]
We have to make sure the user is aware that the button will eventually becomes enabled (use some sort of 'loading ...' indicator?). Otherwise users with a slow connection might think the button is disabled permanently.

**Comment by MrFool** [comment]
I opened an issue #3660, we could just let the button text be 'loading...' and change it to 'Submit' once AJAX has completed?

**Comment by MrFool** [comment]
or rather 'Remind' as it originally is.

**Comment by damithc** [comment]
Yes, that sounds good.

**Comment by MrFool** [comment]
I'll keep the two issues hanging first, work on the JSTL stuff first

**Comment by damithc** [comment]
Didn't fail at V5.72. Closing.
