### ISSUE TITLE
Student: submit feedback: give an explanatory message when there are no recipients for any questions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3659]
Steps:
1. Add a session with only one question. Feedback path of the question: for students to give feedback to 'other team members'
2. Add a student with no team members.
3. Try to submit responses as the student.

Actual: Submission page is empty with a disabled submission button, which is confusing to the user.

Suggested: Give an explanatory message. We give a similar message when there are no questions in the session.

**Comment by tarun14110** [comment]
It was solved is some of the PR.
![screenshot from 2016-07-15 01 27 56](https://cloud.githubusercontent.com/assets/12219700/16853759/6c1098d8-4a2b-11e6-9b56-424e5ad2f509.png)

**Comment by tarun14110** [comment]
Found the issue. The below UI is, when there is question for students, but the specific students don't have that recipient ex- Reciepent is `Team members` and student don't have any team memberas described in #3661.
![screenshot from 2016-07-15 03 30 23](https://cloud.githubusercontent.com/assets/12219700/16857393/094c725a-4a3d-11e6-99e6-7c8b1d7ee38d.png)

**Comment by tanhengyeow** [comment]
Hi Prof @damithc 

This issue seems like it has been fixed.

**Instructor preview as student**:
![image](https://user-images.githubusercontent.com/25320782/38471075-a930fc88-3b9e-11e8-820a-274f83ed0354.png)

**Student view**:
![image](https://user-images.githubusercontent.com/25320782/38471070-9c0be3c4-3b9e-11e8-84eb-adca1db8900a.png)

However, the `Submit Feedback` button is not greyed out for the student and I can click on it to submit my feedback:
![image](https://user-images.githubusercontent.com/25320782/38471099-0b483828-3b9f-11e8-9fe6-77300e71824b.png)

May I know if this is intended?

**Comment by damithc** [comment]
@tanhengyeow Ideally, it should be greyed out, although it is not a big issue. See if it can be fixed without too much work.

**Comment by tanhengyeow** [comment]
Suggesting to close this issue since it has been fixed :smile:

**Comment by tshradheya** [comment]
Closing issue since its already fixed
