### ISSUE TITLE
Resolve conflict between tooltips from jquery UI and bootstrap

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#3673]
On instructorFeedbacks.jsp, jquery ui needs to be loaded before bootstrap for the correct tooltip function to be used. In our jstl template, the jsIncludes fragment is loaded after bootstrap, which has conflicting function name. This causes the jquery ui tooltip function to take precedence over bootstrap's tooltip function. 

I got around this temporarily by including jquery ui in page.tag, but this will cause jquery ui to be loaded on every page, so we need a better way of doing this

**Comment by yj-soh** [comment]
JQueryUI is used only in instructorFeedbacks, instructorFeedbackEdit, and studentProfilePage.

There are multiple methods to solve this.

First is to use the [bridge plugin in jquery (pre-included)](http://www.ryadel.com/2015/01/03/using-jquery-ui-bootstrap-togheter-web-page/). This will have to be included wherever the conflict happens.

Next, we can customise a version of JQueryUI without the conflicting method as we are not using it.

Lastly, we can slot the includes fragment in between the rest of the JavaScript script tags instead, so that the Bootstrap function can take precedence. We can also include multiple places to slot it in, but this will probably get messy in the long run (and reduces the purpose of templating).

**Comment by kanghj** [comment]
The bridge plugin still requires us to load jquery UI before bootstrap, and then execute the commands to fix the name collision before including bootstrap. So we will still need to have an additional include fragment before bootstrap if we choose to do this.

**Comment by wkurniawan07** [comment]
No longer applicable in V7 (no more jQuery-ui).
