### ISSUE TITLE
Give different <title> tag for each page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3694]
For example, all instructor pages currently have the same `<title>` tag `TEAMMATES - Instructor`. It can be made specific for each page.

**Comment by MrFool** [comment]
This bodes the same for admin pages, many occurrences of Teammates Administrator

**Comment by amarlearning** [comment]
@damithc I think we should change the page title to `<heading> | Teammates Instructor`.

Example if we are on:

1. Course Details Page: -  the title could be something like `Course | Teammates - Instructor`
2. New Feedback Session Page: -  the title could be something like `New Feedback Session | Teammates - Instructor`
3. Instructor Home Page: -  the title could be something like `Home | Teammates - Instructor`

and so on.

Let me know what you think.

**Comment by damithc** [comment]
How about
`Instructor | <heading>`
Or
`<heading> [Instructor]` ?

**Comment by amarlearning** [comment]
If we use format `Instructor | <heading>`, then the `<heading>` won't be visible in the chrome tab only `Instructor` will be visible.

I think better would be to go with `<heading> | Instructor`

**Comment by damithc** [comment]
BTW, my second option is `<heading> [Instructor]`, not `<heading> | Instructor`

**Comment by amarlearning** [comment]
_[screenshot of browser tabs]_
![screenshot from 2017-07-19 07-00-15](https://user-images.githubusercontent.com/9383897/28346656-050da7aa-6c50-11e7-951a-ad87419c1414.png)

The titles on the browser tabs really help me in navigating between different page. so the point of sharing that image is only the `<heading>` part will be visible to Instructor/Students. With that, I think we have left with these two options `<heading> | Instructor` OR `<heading> [Instructor]`.
***
I would prefer `<heading> | Instructor` over `<heading> [Instructor]` because 

`Course | Instructor` makes more sense than `Course Jhon Doe` 
OR
`Student List | Instructor` is better than `Student List Jhon Doe`

Let me know what you think

**Comment by damithc** [comment]
I agree, we should have the `<heading>` first.
No, I didn't mean we should use the actual name of the instructor. Rather, I wanted to use square brackets instead of the pipe symbol. e.g. `Student List [Instructor]`. `Student List | Instructor` can be mistaken for _bread crumbs_ indicating `instructor` is a sub feature of `Student List`

**Comment by amarlearning** [comment]
`<heading> [Instructor]` look good then. 
opening a PR.
