### ISSUE TITLE
Distribute point among options: Layout can be improved

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3705]
Here's an example:
first column (option description) is squashed while there is lot of empty space on the right.
![image](https://cloud.githubusercontent.com/assets/1673303/8132946/c458000c-1157-11e5-9da3-d1697a774cb2.png)

**Comment by tarun14110** [comment]
We are using template to generate options. So all the options are independent of each other.
So, I am not able to group all labels and find out a way to automatically increase the width of all the labels, whenever we have even a single large option. @YongJieYongJie Can you help me with this ?

@damithc Can we just increase the width of labels.
For long options
![screenshot from 2016-07-19 13 31 17](https://cloud.githubusercontent.com/assets/12219700/16942764/7db7607a-4db5-11e6-8e95-ba7f02b7edf4.png)

For short options
![screenshot from 2016-07-19 13 33 51](https://cloud.githubusercontent.com/assets/12219700/16942765/7dbcc88a-4db5-11e6-895a-f025c91fd9b8.png)

**Comment by YongJieYongJie** [comment]
@tarun
I think the problem with the above approach is that the elements may not be aligned to the left when labels are short.

If we want to keep the elements left aligned, keep input boxes aligned and make full use of empty spaces before wrapping line, we can try using flexbox instead of the `col-md-2` that we are currently using for the labels.

https://css-tricks.com/snippets/css/a-guide-to-flexbox/
