### ISSUE TITLE
Team name should be trimmed of leading/trailing spaces

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3706]
A user ended up creating two teams `Team 1` and 'Team 1 ` by mistake. The code should be intelligent enough to correct such user mistakes.

**Comment by damithc** [comment]
Not sure what to do with extra white spaces in the middle though. e.g. 
```
Team    1
```
vs 
```
Team 1
```

**Comment by MrFool** [comment]
Might add bulk to the code but we can design a string util helper to do that if it's really needed.

**Comment by taniach** [comment]
I think we should remove extra spaces within the string too. The team name is still the same. The user may have typed an extra space by mistake.

**Comment by damithc** [comment]
We already have a `StringHelper` class. We can add the method there.

**Comment by YongJieYongJie** [comment]
@damithc 
#### already implemented before date of issue
the [`StudentAttributesFactory`][SAF] currently already performs `.trim()`:

        String paramTeam = columns[teamColumnIndex].trim();
        String paramName = columns[nameColumnIndex].trim();
        String paramEmail = columns[emailColumnIndex].trim();

The `.trim()` function is implemented on Aug 11, 2014 in [this commit][commit], 10 months before this issue is opened.

[SAF]: https://github.com/TEAMMATES/teammates/blob/22050942ce21c44d26120a74f3e935723d42e8fd/src/main/java/teammates/common/datatransfer/StudentAttributesFactory.java#L93
[commit]: https://github.com/TEAMMATES/teammates/commit/4dbac532d9e0cc5326c7e92aab190720d0595827

#### possible reasons for bug
Perhaps the instructor added the student before the commit.
Alternatively, perhaps the space at the end of "Team 1 " is actually a non-breaking-space (i.e.,  ASCII value of 160, and not in the 0-32 range of usual whitespaces).
   
I can implement a method to trim duplicate internal spaces to close this issue.

**Comment by damithc** [comment]
Yes, we can remove duplicate inner spaces. Also make sure the leading/trailing space is not introduced during an edit operation.
