### ISSUE TITLE
Submit responses: session not open: prevent status message getting added twice

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/teammates#3853]
When someone submits responses after the session is closed (e.g. the deadline expired while the user was filling the form), the error message gets added twice. [EDITED by damith]
![screen shot 2015-06-29 at 5 10 06 pm](https://cloud.githubusercontent.com/assets/7547452/8404711/bfbc5d36-1e81-11e5-909b-211b5362e79a.png)

**Comment by kanghj** [comment]
Getting added twice since when the feedback responses are submitted, the Save action adds a status message, and a RedirectResult to the Submission Page is returned, which adds the same status message.

This only happens on FeedbackQuestionSubmission because the redirection returns the user back to the Submission page. One way of fixing this is to make the feedbackQuestionSubmission redirect to the home page if there's an error. Alternatively we can update the status messages to not contain duplicates.

**Comment by damithc** [comment]
It is better to return to the submission page when there is an error.

**Comment by LiHaoTan** [comment]
This has been fixed as part of #8367.
