### ISSUE TITLE
Rename appPage0.html to appVerifyTablePatternTestPage.html

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3870]
From a quick dig through, it seems that it is not used anywhere. @kanghj can confirm? Any ideas where this could be used?

**Comment by wkurniawan07** [comment]
I am 99% sure this is used because I have removed unused HTMLs some time back and don't recall any addition/removal of HTML files since then. I couldn't remember where it is used though.

**Comment by junhaoyap** [comment]
I did a case insensitive string search on the whole repo and couldn't find anything related, perhaps it is used for some legacy stuff that we don't know about?

**Comment by kanghj** [comment]
AppPageUiTest.java uses it maybe?

**Comment by yj-soh** [comment]
`return "file:///"+workingDirectory+"/src/test/resources/pages/appPage" + pageNumber + ".html";`
Commit that made them: https://github.com/TEAMMATES/repo/commit/6bb29ccb9eee64737b8b70f9359c8e375ea037d0

**Comment by junhaoyap** [comment]
Indeed it is used in AppPageUiTest.java, perhaps we could rename the issue to improve on that?

**Comment by damithc** [comment]
For a first timer to be able to do this, the task should be clearly specified. What's the suggested new name?

**Comment by myang310** [comment]
Hi. I am interested in contributing to my first OSS project. I'd love to tackle this, but what should the new name be?

**Comment by junhaoyap** [comment]
Hi @myang310! Thank you for your interest! It's also suggested you introduce yourself to us in the issue page when you get the chance to!

In the mean time, I'm going to suggest that we change both ```AppPageUiTest.java``` to what it does ```AppTableSortingTest.java``` and ```appPage0.html``` should be correspondingly named as ```AppTableSortingTestPage.html```

Is that ok @damithc and any suggestions from @wkurniawan07, @kanghj or @yj-soh?

**Comment by wkurniawan07** [comment]
Looks like I enter the party quite late :p

Anyway, renaming to table sort is inaccurate because it is **not** what is being tested. The said test intends to test various functions in `AppPage.java`, but the only function that is tested is `verifyTablePattern` so if there is anything to rename, it should be from `appPage0.html` to `appVerifyTablePatternTestPage.html`. `AppPageUiTest` should not be renamed, otherwise the intention of the test (albeit its fulfilment is very little) is gone. I will rename the issue as such.

Besides, table sorting already has its own test in `TableSortTest.java`.
