### ISSUE TITLE
The current date format can be misleading to US users.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#3873]
e.g. 08.06.2015 can be interpreted as Aug 6th.

**Comment by junhaoyap** [comment]
This is because some Americans tend to read it as DDMMYYYY and some as MMDDYYYY at high proportions. I recently had to fill in 2 forms during my NOC procedure by 2 big entities and one of them wanted dates as DDMMYYYY and the other MMDDYYYY, very confusing :/

Lower cost solution: at date fields / inputs, clearly state at the label DDMMYYYY

Higher cost solution: allow instructors to set DDMMYYYY/MMDDYYYY etc in a 'profile' page

**Comment by damithc** [comment]
May be use a more universal format such as '08 Aug 2015' ?

**Comment by yj-soh** [comment]
They would write it as "Aug 08 2015".
Well, even if it's not what they're used to, it would still work to make it non-misleading.

**Comment by junhaoyap** [comment]
That would be another solution for sure but higher cost perhaps, need to change display and input in that case? So that when they click on the date picker we have to show say '03 Aug 2015' instead of what we show now.

**Comment by samsontmr** [comment]
how about YYYYMMDD? I don't think anyone uses YYYYDDMM

**Comment by damithc** [comment]
closing in favor of #1701
