### ISSUE TITLE
StudentProfilePageUITest frequently fails at line 130 

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#3959]
![studentprofile](https://cloud.githubusercontent.com/assets/8078323/8617392/50160480-273e-11e5-8957-f24625d36a0f.png)

**Comment by wkurniawan07** [comment]
I've actually managed to discover why.
1. What actually happened was the picture edit failed and 295 is the size of the previous picture.
2 The reason the picture failed was a caught RuntimeException. If you managed to see how the page looked like, you'll see "The photo that was edited did not belong to the user. Please upload another picture to begin editing" as the status message.
3. Digging the activity log page, I found out that the reason is "The API call images.Transform() took too long to respond and was cancelled".
I'll be happy to be proven wrong but I think fixing this is beyond our capability :p

**Comment by thyageshm** [comment]
@ashrayjain I think this was the one you got right?

**Comment by damithc** [comment]
old issue. closing.
