### ISSUE TITLE
USER_IS_TEAM is wrongly used in FeedbackSessionResultsBundle

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4018]
Currently in FeedbackSessionResultsBundle, the constant Const.USER_IS_TEAM, %TEAM%, and Const.USER_IS_NOBODY, %NOBODY%, is checked for in a few branches related to names. %TEAM% appears to be related to handling orphaned responses in FeedbackSessionsLogic, this seems wrong. We can check if these constants are actually used, and remove/rename them if neccessary.

**Comment by thyageshm** [comment]
@wkurniawan07 any updates on this one?

**Comment by wkurniawan07** [comment]
I'll start investigating this tomorrow, but to get a thorough result I might need more time than the next release, so taking this off the milestone for now.

**Comment by wkurniawan07** [comment]
To trace its usage, let's go to `FeedbackSessionsLogic`:
![image](https://cloud.githubusercontent.com/assets/7261051/13108647/5db2e2dc-d5af-11e5-9d2e-e137a63a9664.png)
![image](https://cloud.githubusercontent.com/assets/7261051/13108658/779c98dc-d5af-11e5-86cd-0e1cef5f6bb3.png)
The `Const.USER_IS_TEAM` is assigned whenever there is no `StudentAttributes` or `InstructorAttributes` associated to the email can be found, and if the question is not a general question.

It seems reasonable to assume that if `Const.USER_IS_TEAM` is the assigned value, then the question type is either `TEAMS` or `OWN_TEAM` (i.e the first branch) so that the value never actually reaches the bundle. Either that, or the `*Attributes` associated to the email has been deleted but the response somehow remains.

Thus when it reaches the bundle:
![image](https://cloud.githubusercontent.com/assets/7261051/13108747/fcdb1a5a-d5af-11e5-8c9b-d02f311bd5db.png)
The assumption is there should not be `Const.USER_IS_TEAM` and if there is, it's an orphaned response. So the usage is not wrong, but it's confusing alright.

**Comment by thyageshm** [comment]
@wkurniawan07 would you be able to complete this in this milestone?

**Comment by wkurniawan07** [comment]
I think it's not likely to finish in this milestone, although I could try and open a PR by today.

**Comment by thyageshm** [comment]
ok no prob, we will reassign this to V5.71, but no more extensions I am afraid
