### ISSUE TITLE
Wrong Status Message in AdminAccountDetailsPage

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#4021]
When deleting a student in Admin Account Details, `Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE` is used instead of `Const.StatusMessages.STUDENT_DELETED`

**Comment by VamsiSangam** [comment]
Is this issue still active? A search for [``Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE``](https://github.com/search?utf8=%E2%9C%93&q=Const.StatusMessages.INSTRUCTOR_REMOVED_FROM_COURSE+repo%3Ateammates%2Fteammates&type=Code&ref=searchresults) gives occurences which are not in the master branch. I am a noob. Please guide me on how I can help.

**Comment by wkurniawan07** [comment]
@VamsiSangam the issue is still valid, but since you have done another `d.FirstTimers` issue before, it is not open for you anymore. You can find other issues, particularly those labelled `d.Contributors`.

That aside, GitHub's search result brings you to the tree where the file is last indexed, i.e. it will never bring you to the `master` branch. You have to confirm by changing the branch to `master` on the search result, or just do the search via Eclipse (or any other file search methods) in your own local copy.

**Comment by VamsiSangam** [comment]
Ok, thanks a lot for the pointers and the advice about GitHub! 😄

**Comment by damithc** [comment]
@AnaghHegde you can see for yourself if the issue is open and if there are other ongoing PRs for it (if there are PRs for an issue, they are mentioned in the issue thread).

**Comment by AnaghHegde** [comment]
@damithc can you please guide me how to proceed as this is my first contribution

**Comment by damithc** [comment]
@AnaghHegde 

This is the best place to start https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md
If you have specific questions, you can post them in the issue tracker if you cannot find the answer yourself. To a great extent we expect contributors to figure things out by themselves, which is a necessary skill for OSS developers.
