### ISSUE TITLE
Run TestDriver test cases before the full test suite

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4034]
I've been having this thought after the last episode on `test.timeout`.
The SUT (TestDriver) consists of the set of tools we used in testing. Logically speaking, we need to ensure that they work well before we proceed with our testing.
By running the TestDriver test cases before everything else, we can:
1. Catch any defect in the TestDriver before they are propagated to the real tests.
2. Find out missing test properties, such as `test.timeout` some time back.
3. Log the test properties values to the developer to see if there are changes needed. Also, we can point out things such as whether the test accounts are God mode-compatible or not.

Dr @damithc any thoughts on this?

**Comment by damithc** [comment]
Yes it is a good idea if it can be done without lot of effort. Breaking the test driver is supposed to be rare though, so as long as we find it out it is not a big deal whether it is at the beginning of the test run or at the end. Still, it is good to find earlier if it can be done.

**Comment by wkurniawan07** [comment]
Indeed, breaking the TestDriver is rare. However, based on the last episode on `test.timeout`, I believe it's better to be found out earlier, or else it'd only be halfway in the test run that you realized something is wrong and by that time you've failed so many tests miserably and wasted your time. If TestDriver is tested before everything else, such failures can be caught and fixed early.
The approach I have in mind is giving the TestDriver cases its own testng file, which should be straightforward.

**Comment by tshradheya** [comment]
@wkurniawan07 Would want your input on this.
Would this task involve running `teammates.test.cases.testdriver` tests at the very start(can be done using priority) and then adding more assertion checks to `TestPropertiesTest` ?

> giving the TestDriver cases its own testng file
I am not quite sure what you mean by this. I assume its a way to make the `testdriver` directory tests to run first.

> Catch any defect in the TestDriver before they are propagated to the real tests.
What kind of defects exactly? Would passing of all `testdriver` directory tests mean that there are most likely no defects ( I can understand that some defects like checking browser version and stuff cant be ensured, but otherwise are these tests sufficient?)
