### ISSUE TITLE
InstructorSubmissionAdjustmentUiTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4157]
failing on line `99 assertEquals(0, numberOfNewResponses);`
Actual is 1. May be a eventual consistency issue.

**Comment by kanghj** [comment]
Adjustment of submissions is done on the task queue, so it might be that there were other tasks on the queue at the time of the test and the adjustment task hasn't been executed. Not sure how to make this test pass consistently because the live server may have different number of items in the task queue at different times?

**Comment by damithc** [comment]
Check in a loop for several times?

**Comment by damithc** [comment]
Managed to pass once, so lowering priority.

**Comment by damithc** [comment]
failing at V5.71 after a few tries.

**Comment by damithc** [comment]
did not fail at V5.80

**Comment by damithc** [comment]
did not fail at V5.83. Actually, as other times, failed initially and passed when run on its own.

**Comment by damithc** [comment]
failed at V5.87

**Comment by damithc** [comment]
still failing at v5.95

**Comment by damithc** [comment]
Passed at v5.98
