### ISSUE TITLE
Add a CONTRIBUTING.md to the repo

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4242]
see https://github.com/blog/1184-contributing-guidelines

For an example, see hubturbo repo

**Comment by sidd23** [comment]
Hi, I would like to work  on this issue. Can I?

**Comment by YongJieYongJie** [comment]
Since *contributing.md* is shown when an issue is opened and when a pull request is submitted,
I suggest we keep it **short and scannable** to serves as a quick reminder.
(This will be in line with GitHub's [blog post][blog] on suggested usage, and also similar to HubTurbo's [contributing.md][con]).

[blog]: https://github.com/blog/1184-contributing-guidelines
[con]: https://github.com/HubTurbo/HubTurbo/blob/master/CONTRIBUTING.md

Also, since *readme.md* already contains a comprehensive directory listing,
I propose that we **avoid duplication** between *contributing.md* and *readme.md* (which also avoids risk of the two going out of sync).

something like this:

### Contributing to TEAMMATES

Contributions are very welcomed.
But do ensure that you have conformed to the following:
- Best practices for: [UI design][ui], [Coding][code], [Testing][test]
- Coding standards for: [Java][java], [JSP][jsp], [JavaScript][js], [CSS][css], [HTML][html]
- [TEAMMATES Development Process][dev] (including naming conventions for commits and pull request, etc.)

### Other Resources
If you are just starting out, do refer to the [Contributor's Orientation Guide][COG].
For a comprehensive directory of resources, please refer to [README.md][readme].

[ui]: https://docs.google.com/document/d/1Vj59--sCYUfxgg-iLI53hMfc6YY1gguATTN_KXTQVUo/pub?embedded=true
[code]: https://docs.google.com/document/d/14EFJzdhp10qQ9iZ-FwsS1FAf42voe4exrlbefo_zYaU/pub?embedded=true
[test]: https://docs.google.com/document/d/1aK-1ubIA59fbNsEujwvWKqx7itwLPTD6mzFo4F_oEoI/pub?embedded=true

[java]: https://docs.google.com/document/pub?id=1iAESIXM0zSxEa5OY7dFURam_SgLiSMhPQtU0drQagrs&embedded=true
[jsp]:https://docs.google.com/document/d/14bXfdveXvoIaPBYpL19m4PK6oPabSnnoawj6OGjOzD4/pub?embedded=true
[js]: https://docs.google.com/document/d/1gZ6WG6HBTJYHAtVkz9kzi_SUuzfXqzO-SvFnLuag2xM/pub?embedded=true
[css]: https://docs.google.com/document/d/1wA9paRA9cS7ByStGbhRRUZLEzEzimrNQjIDPVqy1ScI/pub
[html]: https://docs.google.com/document/d/12PJYbQoqjK-0LzaUuguQ4kGE--eikCcHfwzZDGwFOJ0/pub?embedded=true

[dev]: https://github.com/TEAMMATES/teammates/blob/master/devdocs/process.md

[cog]: https://docs.google.com/document/d/1cY9pmEmw4dC6Z4LjN1WUTsynJ0jVPgbWsFhdyBy_wCU/pub?embedded=true
[readme]: https://github.com/TEAMMATES/teammates/blob/master/README.md
