### ISSUE TITLE
Instructor: enroll students: prevent 'Entity already exists' exception due to eventual consistency

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4312]
`Error Message: teammates.ui.controller.InstructorCourseEnrollSaveAction execute: Entity already exists exception occurred when updating student: Trying to create a Student that exists:`

I guess this is related to eventual consistency. See if there is a way to mitigate it (try several times in a loop?)

**Comment by mayralgr** [comment]
@madanalogy is this still open? can I work on it?

**Comment by madanalogy** [comment]
> @madanalogy is this still open? can I work on it?

The specified controller class actually no longer exists. The functionality / feature might still be present somewhere however since the migration of v7. @wkurniawan07 any chance you know if this is still an issue? If no then I'll likely close the issue

**Comment by wkurniawan07** [comment]
"Eventual consistency" is a lingering matter due to the nature of the DB we used. Although for this specific problem, even the error message `Entity already exists exception occurred when updating student: Trying to create a Student that exists:` doesn't really make sense. I guess it's becoming a wild goose chase if we keep this issue around.
