### ISSUE TITLE
Allow users to give feedback when they encounter an error page

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#4315]
We can show a stack trace, ask the users what they were doing to trigger the error.
This will help us in replicating the errors.

**Comment by HirdayGupta** [comment]
@damithc (not sure if I'm using the tag correctly here 😛) Would it be ok for this form to be a Google Form?

**Comment by damithc** [comment]
> @damithc (not sure if I'm using the tag correctly here 😅)

No need for the tag. Your comment is applicable to all devs :-)

> Would it be ok for this form to be a Google Form?

Initially, a Google form may be enough. In future, our own submission system can be considered because we could like to capture some information from the system when the problem is reported.

**Comment by HirdayGupta** [comment]
Understood @damithc. So right now, would you like me to add a Google Form to all the error pages? Or should I work on implementing our own submission system?

**Comment by damithc** [comment]
Perhaps we can give `report error` button in the error pages and open an email client when they click on it (i.e. `mailto` link). Then, we can try to autofill some of the relevant info into the body of the email. I'm not sure if we can autofill Google forms. BTW, we can add the same option under the `Help` menu because users might encounter errors without seeing an error page.

**Comment by HirdayGupta** [comment]
I've found a way to autofill google forms with URL parameters. This can be done by creating a pre-filled form. For instance, if you access this form:https://docs.google.com/forms/d/e/1FAIpQLSfvYsR3jrcGDUXlnAXGIXILyOjW_Q4ngoSdah6-LIed4UXouA/viewform?usp=pp_url&entry.772346127=UserName&entry.1220253264=UserEmail&entry.824237481=Instructor&entry.1725895013=%3C%3CPrint+Stack+trace+here%3E%3E&entry.1267495136

You will see that some of the fields are prefilled. These fields are prefilled using the URL parameters in the link above. The values of this field can be dynamically filled in the URL for the iFrame that displays this form. 

I feel this would be preferable to the `mailto:` link because not all users may have an email client set up. Or may not prefer using their desktop client.

**Comment by damithc** [comment]
Will it work with a couple of pages worth of stack traces and log entries? I think there is a limit to how long a URL can be. On the other hand I think support for mailto links are also limited. As a user I personally feel it is more user friendly to send emails (more personal and more flexible) rather than fill long forms. We may have to give a web-based email interface after all.

**Comment by HirdayGupta** [comment]
@damithc we can use something like the Google Docs API to upload the stack trace to a document and only pass the link to this form. The only field the user would need to fill would be the *"How did you get here"* field.

However, the web-based email interface works too. Can make use of some code from the Admin Email sender.

**Comment by damithc** [comment]
Yes, let's use our own email composer for it. No need to get Google docs/forms involved.

**Comment by HirdayGupta** [comment]
Sounds good @damithc.
Working on this.

**Comment by HirdayGupta** [comment]
@damithc In trying to emulate the behaviour of the Admin Email composer stack, I find that I may have to create a new Task Queue, Worker URL and Database for this feature. Am I moving in the correct direction? And if so, I will need some assistance in creating the same as I am extremely new to this. Another option is to use the existing queue, url and Database for the admin emails (something that may be manageable with a little tweaking).

As of now, I have created an Action (a stripped down version of the `AdminEmailComposeSendAction` that receives that parameters from the form (screenshot below). The form appears in all error pages through the error tag. (note: the to field has my email address because that was what I configured the Config.SUPPORT_EMAIL field to in build.properties)

![screen shot 2017-06-13 at 2 01 15 pm](https://user-images.githubusercontent.com/18088721/27073252-d1c47d22-5040-11e7-9719-ff161ff0ac52.png)

**Comment by damithc** [comment]
@HirdayGupta perhaps we leave this alone for a while until you are more familiar with the code base? To make matters worse, admin features are the least tested part of the app. In fact, admin email sending feature is rarely used. So, if you dive into this area and run into difficulties, help from current devs may not be as readily available as for other areas.

**Comment by damithc** [comment]
I just realized there is an easier way to do this. Instead of sending an email directly, simply log a message at `severe` level. We already have a mechanism to email `severe` level log messages to the admin.

**Comment by HirdayGupta** [comment]
@damithc I was unaware of such mechanism that is a lot simpler! 😅 Will implement this and carry on further discussion in the PR. 😀
