### ISSUE TITLE
The 'expand students' button disappear after expanding panel

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4352]
![image](https://cloud.githubusercontent.com/assets/1673303/10035479/46f7cde2-61cd-11e5-9f5a-662251f22bd0.png)

**Comment by damithc** [comment]
The button doesn't even work. Raising priority.
![image](https://cloud.githubusercontent.com/assets/1673303/10408641/11778ba0-6f36-11e5-8a75-f8cdaa58cc76.png)

**Comment by junhaoyap** [comment]
I just tested expansion locally and it seems to be working, is there any other steps I have to do to reproduce the error state?

<img width="1214" alt="screen shot 2015-10-11 at 3 01 11 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419329/2659cbd4-7029-11e5-9c56-982d0522e0de.png">
<img width="1211" alt="screen shot 2015-10-11 at 3 01 17 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419330/265a46c2-7029-11e5-8fcb-5d6cc309d005.png">
<img width="1193" alt="screen shot 2015-10-11 at 3 01 24 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419328/2659d2f0-7029-11e5-9176-f198f6681e17.png">
<img width="1190" alt="screen shot 2015-10-11 at 3 01 30 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419331/265b7fe2-7029-11e5-906e-cfe89e3a2870.png">

**Comment by junhaoyap** [comment]
Perhaps, this is not a bug but a confusing UX.

From what I understand, in your second screenshot, there are two sections with the green button, but notice that their arrows are pointed downwards meaning that they are expanded therefore there is an option to "Expand Teams".

However, the section without the green button, notice that the arrow is pointing upwards meaning that everything is collapsed and hence there is no option to "Expand Teams".

**Comment by junhaoyap** [comment]
<img width="1184" alt="screen shot 2015-10-11 at 3 07 41 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419351/cf7ade9c-7029-11e5-8aeb-9c8bfb29a8c8.png">

In the above screenshot, also notice that there are indeed some sections that can have their arrows point downwards and have no yellow "Expand Students" team, perhaps the logic behind whether or not to show buttons here is the root problem, aka confusing UX?

**Comment by damithc** [comment]
This feature is badly broken. Need to fix soon.

**Comment by damithc** [comment]
The button is not working at all. The panel can be expanded by clicking on the bar instead, but users may not realize that. Need to fix.

**Comment by junhaoyap** [comment]
Didn't notice it's been urgent for awhile, will take a look again soon, ping me with "@" next time if I miss something that is urgent

There is need for more details regarding this though, what exactly needs to be fixed? It was too vague the previous time I looked into it, seems to be two different issues rather than one, the issue title says 'Expand X' buttons disappear but I have previously looked into it and it's not that they disappear, there is a slew of logic behind whether they should be shown or not and should be a whole issue by itself which tells us exactly how the logic should be instead of it's current state. The second issue is that the buttons do not work, from my previous investigation, it's not that they don't work, they do work as per the screenshots I have provided, they did not work in the screenshots you provided because they are in a 'corrupted' format ->

First screenshot: Some yellow bars do not have 'Expand Students', I don't think any of the bars should have 'Expand Students', notice that all of the arrows are pointing downwards, meaning none of the bars are expanded and none of the "Student information"'s HTML is appended yet

Second screenshot: Notice that the bars with arrows pointing down has no "Expand Team" but only those with the arrows pointing downwards. However, also notice that those with the "Expand Team" option have no "Team information" HTML appended yet

What I'm trying to say is that it might not be that the buttons don't work, but there is flawed logic as to why the buttons are there even though the tabs are not being displayed and / or the tab hasn't even been expanded?

**Comment by junhaoyap** [comment]
<img width="1214" alt="screen shot 2015-10-11 at 3 01 11 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419329/2659cbd4-7029-11e5-9c56-982d0522e0de.png">

Initial state

<img width="1211" alt="screen shot 2015-10-11 at 3 01 17 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419330/265a46c2-7029-11e5-8fcb-5d6cc309d005.png">

After clicking on the bar to expand it, notice now the button to "Expand Team" appears which is logical, now there is a "Team"'s HTML to be expanded now

<img width="1193" alt="screen shot 2015-10-11 at 3 01 24 pm" src="https://cloud.githubusercontent.com/assets/6291947/10419328/2659d2f0-7029-11e5-9176-f198f6681e17.png">

After clicking on "Expand Team", it works

**Comment by junhaoyap** [comment]
Let's put it this way, what is the expected behavior? Are the buttons meant to expand the tab and the inner tabs, or just inner tabs?

![image](https://cloud.githubusercontent.com/assets/1673303/10035479/46f7cde2-61cd-11e5-9f5a-662251f22bd0.png)

Let's reference the first screenshot provided, assume the buttons work and assume each team has students, why is it that some of the teams have "Expand Students" whereas some do not? That looks like a bug to me.

Assume the buttons both expand the tab and the students, then we have BOTH a logic problem behind when to display the button and when not to AND an implementation error of the buttons

Assume the buttons is only meant to expand the inner tabs (which, as far as I can tell, is the current implementation, look for inner tabs and expand them), then we have a logic problem behind when to display the button and when not to

**Comment by damithc** [comment]
Let's fix this problem first (rename issue if necessary, and create new issues for remaining problems):
When the page is first loaded, clicking this button is the logical thing for the user to do. However, it doesn't do anything except toggle the text.
![image](https://cloud.githubusercontent.com/assets/1673303/11465670/9f1118ca-9775-11e5-8a1c-9ce0cffa71a3.png)

**Comment by junhaoyap** [comment]
I’ll mark this email so I won’t miss it again, I’ll get back to you

**Comment by damithc** [comment]
Let's fix the 'button not working' (my most recent comment) problem first, here or as separate issue. That's the most urgent problem. 
The issue of 'button disappearing' can be tackled later, with a revisit to what should be the expected behavior. Apparently, the current behavior also goes against our policy of 'disable rather than hide' policy.

**Comment by junhaoyap** [comment]
Will do, it’s pretty late here now so I’ll have to look at it tomorrow to look into it and get back to you, understand it’s urgent so I’ll look at it once time present itself

**Comment by junhaoyap** [comment]
<img width="1181" alt="screen shot 2015-12-01 at 2 06 43 am" src="https://cloud.githubusercontent.com/assets/6291947/11497786/3679da62-97d0-11e5-809e-a5b79e1b0a97.png">
<img width="1169" alt="screen shot 2015-12-01 at 2 06 36 am" src="https://cloud.githubusercontent.com/assets/6291947/11497787/3689cec2-97d0-11e5-84d8-f763f49a7627.png">
<img width="1186" alt="screen shot 2015-12-01 at 2 06 29 am" src="https://cloud.githubusercontent.com/assets/6291947/11497789/3694b742-97d0-11e5-9c88-7941e5e875a8.png">
<img width="1215" alt="screen shot 2015-12-01 at 2 06 22 am" src="https://cloud.githubusercontent.com/assets/6291947/11497788/36929cfa-97d0-11e5-854a-436caaf6cc89.png">

**Comment by junhaoyap** [comment]
<img width="1169" alt="screen shot 2015-12-01 at 2 06 36 am" src="https://cloud.githubusercontent.com/assets/6291947/11497787/3689cec2-97d0-11e5-84d8-f763f49a7627.png">

Initial state

<img width="1181" alt="screen shot 2015-12-01 at 2 06 43 am" src="https://cloud.githubusercontent.com/assets/6291947/11497786/3679da62-97d0-11e5-809e-a5b79e1b0a97.png">

After clicking on expand

Works as expected

**Comment by junhaoyap** [comment]
I looked into the JavaScript code, it iterates over by looking for "panel-collapsed" classes and expanding each panel only if they are found, the buttons are working as intended:

![image](https://cloud.githubusercontent.com/assets/1673303/10408641/11778ba0-6f36-11e5-8a75-f8cdaa58cc76.png)

In this case, the buttons do not work but toggle the text anyway (the text gets toggled on and off from collapse to expand and vice versa regardless of success or failure of the function) but notice that the panels in which the buttons are there do not have a single inner panel that is of class panel-collapsed so nothing gets toggled when the buttons are pressed

**Comment by junhaoyap** [comment]
It seems we have a deeper bug, looking at the screenshot below:

![image](https://cloud.githubusercontent.com/assets/1673303/10408641/11778ba0-6f36-11e5-8a75-f8cdaa58cc76.png)

F09 -> Correct state, the button should not be there while it has the downward-chevron, there are currently no inner panels with the panel-collapsed class and thus the button will fail even if it exists and is clicked

F10 & F11 -> Incorrect state, the button should be there because it has the upward-chevron meaning that the panel should currently be expanded, but note that they are not expanded, if they are, they should look something similar to ->

<img width="1169" alt="screen shot 2015-12-01 at 2 06 36 am" src="https://cloud.githubusercontent.com/assets/6291947/11497787/3689cec2-97d0-11e5-84d8-f763f49a7627.png">

**Comment by junhaoyap** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/10408641/11778ba0-6f36-11e5-8a75-f8cdaa58cc76.png)

I haven't been able to reproduce the incorrect state of F10 and / or F11, any help on reproducing it so I can debug it?

**Comment by junhaoyap** [comment]
If it's still unclear what I'm trying to explain, we can set up a time to hangouts and then it might be clearer

**Comment by damithc** [comment]
Here's my initial state.
![image](https://cloud.githubusercontent.com/assets/1673303/11465670/9f1118ca-9775-11e5-8a1c-9ce0cffa71a3.png)
Note that the panel is completely collapsed at the beginning. And the button does not work. May be the button does not auto-expand if there are many students? May be that's the condition under which the bug occurs.
I realize this bug is different from the one you are trying to describe. May be open a separate issue for this 'button does not work' bug as it does not match the current issue title?

**Comment by junhaoyap** [comment]
It is the same bug, the button only works if there are inner panels to expand because that's what the button does, the button looks for inner panels to expand and since it is not auto-expanded as you mentioned, it doesn't work because there is nothing for it to work on

I think the root of this issue and therefore what the title should be changed to is the fact that the buttons are there despite the panels not having been expanded?

Because that seems to be the problem you're currently experiencing, the fact that the button is there gives us the thought that it should expand the teams as it says it should but doesn't work when we click it, yet it doesn't

However, if you look at my screenshots, clicking on the buttons while the panels are expanded does work, which means that the problem that we're trying to solve in this issue is the fact that panels that aren't expanded have the button, if they aren't expanded and the buttons aren't there (as they should behave), that solves the problem, right?

**Comment by damithc** [comment]
Yes, that can be the fix.

**Comment by junhaoyap** [comment]
I apologize about the delay on this, I have a grant pitch for a startup and NOC's mid-term presentation coming up within the next few days so I've been focusing on them, if this is too urgent and cannot wait I suggest we move it to someone else -- however, if it's not that urgent, I will definitely look into it after the pitch and mid-term presentation is over

**Comment by yj-soh** [comment]
I'll probably take over the issue?

From some basic analysis, this appears to be caused by the `RESPONSE_LIMIT_FOR_COLLAPSING_PANEL` variable in `InstructorFeedbackResultsPageData` which determines whether the panels are collapsed or not (based on a "max" number of responses). This causes the panels to be collapsed resulting in the image 4 posts above.

One simple solution would be to just expand the panels upon clicking "Expand Teams".  
The other (more complicated) way would remove this behaviour of collapsing the panels based on the number of responses.

It's a UX matter, so I'm not too sure which should be done. Is there any benefit from having the panels collapsed at the start? It is possible by clicking on the "Collapse Section" button either way.

**Comment by damithc** [comment]
Go ahead @yj-soh 
Yes, your proposed simpler solution seems fine.

**Comment by yj-soh** [comment]
After playing around with it, I realised that current behaviour is wrong on a different aspect instead.
![image](https://cloud.githubusercontent.com/assets/1673303/10408641/11778ba0-6f36-11e5-8a75-f8cdaa58cc76.png)
On the image above, the expected behaviour is to have the "Expand Teams" button hidden on page load. Furthermore, the chevrons should all be pointing down to denote that they are collapsed.

So a fix would consist of hiding the button and making the chevrons point down when the panels are collapsed on page load.
After loading, clicking on each panel will show its content along with revealing the "Expand ____" button.
Click on the panel header again will hide the button and collapse the panel.
That fix should allow the behaviour to be consistent with the usual flow.
