### ISSUE TITLE
AdminEmailLogPage and AdminActivityLogPage fails when there is a patch version

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#4417]
Due to line 119 in `AdminEmailLogPageAction`:
`double curVersionAsDouble = Double.parseDouble(currentVersion);`
If the current version is in the format `major.minor.patch`, the parsing function will fail.

Two reasons I didn't resolve this in #4409:
- This is not a testing defect but an app defect
- The above is part of a function `getDefaultVersionIdsForQuery()`. I (or whoever's going to fix this) need to know the policy to use if there are patch versions.

Background: the currently used policy is like this:
- current version is an `rc` version: only include that version
- current version is a `major.minor` version: that version, along with 3 other before, e.g if the current version is 5.01, will include 5.00, 4.99, 4.98. This also I think is problematic because of bad assumptions that the minor version won't reach 3 digits (we have 4.100) and the last minor version before reaching a new major version is 99.
- current version is a `major.minor.patch` version: unhandled!

**Comment by wkurniawan07** [comment]
Two possible ways to handle this (there can be other ways):
1. Follow the `rc` version policy: only include that version
2. Follow the `major.minor` version policy: that version, along with 3 minor versions before, e.g if the current version is 5.01.01, will include 5.00, 4.99, 4.98.

**Comment by damithc** [comment]
First, we can change the version numbering rules from now on: Always have 5 digits x.xx.xx
Next, we can have a method to find the previous 3 versions by cross checking the existence of logs.
If the current version is 5.50.01, check for 5.50.00, 5.49.01. If any logs for 5.49.01 is found, then also check if 5.49.02. If 5.49.02 is found, also check for 5.49.03, and so on.

Also explore if it is possible to query GAE for deployed versions. There may be an API for it.

**Comment by damithc** [comment]
Need to be fixed by next version.

**Comment by ashrayjain** [comment]
Could consider looking at this library https://github.com/zafarkhaja/jsemver

**Comment by bamboo3250** [comment]
https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/log/LogQuery
@wkurniawan07 @damithc I just took a look at the LogQuery API and realized there is a little difference between the way we interpret version strings and the way GAE sees them. 
For example the version `4.18.01`, according to our format, `4` is the major verion, `18` is minor version and `01` is patch version. Meanwhile, GAE takes entire `4.18` as the major version and `01` as minor version. 

Currently, we are only using `query.majorVersionIds()` to search for the logs. So one way to solve this issue is that we will treat all `4.18.xx` as `4.18`, meaning ignoring everything behind the second dot and finding next three most recent versions `4.17`, `4.16` and `4.15`. However, this method still relies on the assumption that our minor version never exceed 2-digit numbers. 

To make sure everything will work later, a convention for our version format is necessary. Otherwise, we would have to give up on "finding next three most recent versions" part.

**Comment by damithc** [comment]
Yes, you can assume that our minor version will not exceed two digits. You can assume that each component is an integer and are in sequence.

**Comment by bamboo3250** [comment]
![image](https://cloud.githubusercontent.com/assets/8078323/13031956/726d7304-d31b-11e5-93f3-b6d5437de887.png)

@damithc Do you remember why we need to go back for three preceding versions? What is the user story behind? Since now we restrict the query by the time (24h), I guess we may not need to specify the versions by default anymore.

**Comment by damithc** [comment]
Actually, as long as activity log queries give me results of past versions, we don't need to query logs of specific versions. This feature was implemented because we thought the queries returned logs from the current version only. If that's not the case, we don't have to bother with the version numbers.

**Comment by bamboo3250** [comment]
I see. Actually it is the case as you said.
https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/log/LogService#fetch-com.google.appengine.api.log.LogQuery-
`If versions and majorVersionIds are both empty, fetch will retrieve logs for the current running version.`

So in the end we still need to iterate back to the past versions if we want to include them in the log result. Fortunately, I just found this gem. It helps us get the list of all supported versions of the application.
https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/modules/ModulesService.html#getVersions-java.lang.String- 

I deployed 4 versions in total: 4.18, 4.19, 4.39 and 4.02 to the staging server in that order and it returns the most recent version first, no matter what the current version is. So I think we can use this method to solve this issue.

![image](https://cloud.githubusercontent.com/assets/8078323/13032807/6ce4581e-d33c-11e5-8096-f15b651bf748.png)

**Comment by damithc** [comment]
While you are at it, can you find what happens to logs when we delete a specific version? Are the logs deleted too?

**Comment by bamboo3250** [comment]
@damithc after we delete a version, the logs of that version will not be deleted immediately. I tried delete some versions and still could find their logs via both AdminActivityLogPage and the Google Cloud Platform.

**Comment by damithc** [comment]
Oh, that's good to hear.

**Comment by damithc** [comment]
Another thing: will your current technique find logs from deleted versions?

**Comment by bamboo3250** [comment]
My technique relies on what ModulesService returns and it cannot return deleted versions. Hence, if you want to retrieve logs from deleted versions, you need to specify them in the query.

**Comment by damithc** [comment]
That's probably why we used the previous technique. We need to query logs irrespective of whether the version is currently deployed. Trying to deduce previous version numbers based on current version number is one option. BTW, it shouldn't limit to 3 previous versions. If we limit to 3, we usually cannot go no more than 3-4 weeks in to the past.

**Comment by bamboo3250** [comment]
If we go for the previous technique,we have to use up all minor version before changing the major version.
For example: it has to be `4.98`, `4.99` then `5.00`. Is it all the case like that? Otherwise, if we jump like from `4.67` to `5.00`, the previous versions cannot be access again. Unless we set the limit by a big value (it could be 100).

**Comment by damithc** [comment]
You can assume that the past 5 versions exists in the server. In fact, I keep the past 8-9 versions (GAE allowed up to 10 past versions). For anything beyond 5 versions, we can use the query to specify which versions?

**Comment by bamboo3250** [comment]
So I will use my method and extend it to query within the current version and its 5 preceding versions. This should cover at least 1 month and a half so I think it would be fine.

**Comment by damithc** [comment]
Sure. Go ahead.
