### ISSUE TITLE
Comments in session: show user's name (not email)

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4522]
We should show the name of the user (or at least provide a way to retrieve the name) in comments. Currently, only the email is shown. The reader may not be able to connect the email to the name.

**Comment by mukesh14149** [comment]
@damithc I looked over the comments , but they seems fine (that is they have name instead of email ) . Could you please help me regarding this ?

Instructor end comments:-
![instructor_end](https://cloud.githubusercontent.com/assets/10887629/13259426/53997cf2-da7d-11e5-9fb2-04c04baf4496.png)

Student end comments:-
![student_end](https://cloud.githubusercontent.com/assets/10887629/13259455/6cd5d77e-da7d-11e5-82f5-7b80d2acdfb9.png)

**Comment by damithc** [comment]
This may have been fixed along the way. @JosephineKwa can confirm?

**Comment by JosephineKwa** [comment]
For Comments in session, only the giver's email is shown, as seen in the screenshot below:
![comments1](https://cloud.githubusercontent.com/assets/9999077/13281503/2d065f68-db1f-11e5-915a-6a939660b6bf.PNG)

**Comment by Mynk96** [comment]
Should I add a new attribute (like commentGiverName) to FeedbackResponseComment Entity or just extract the name of the instructor using his/her email?
