### ISSUE TITLE
instructorFeedbackResults: In table format, show a divider between teams

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4589]
When showing results in table format, it can be useful to see some sort of divider between teams.

**Comment by paradite** [comment]
I think this would only work if the table is sorted by teams and assuming that the order within each team remains the same. 
Once you sort by other attributes, the dividers between teams would not make sense. So in order to implement this properly, we need to use some JavaScript for detection of sorting method and dynamically add the dividers if sorted by team.

**Comment by damithc** [comment]
True. In fact we can add the divider based on whichever the column being sorted. But I don't think it will be easy to do.

**Comment by paradite** [comment]
Yes. So I will look for other issues first.
