### ISSUE TITLE
InstructorFeedbackQuestionEditAction: Condition of if-statement is always true

### ISSUE THREAD

**Issue by unyoungwax** [TEAMMATES/teammates#4723]
In `InstructorFeedbackQuestionEditAction.java` around line 84, it seems that the condition of the if-statement is always true even if the question number is not edited.

**Comment by damithc** [comment]
Does it affects the functionality? How bad is it?

**Comment by unyoungwax** [comment]
Question numbers are adjusted even if it results in no change in the question numbers. Besides that, the response rate is not updated accordingly if the feedback path is changed.

**Comment by damithc** [comment]
@kanghj, this breaks the functionality? How soon we should fix this?

**Comment by kanghj** [comment]
Editing questions still work, even though it causes unnecessary database reads (<code>adjustQuestionNumbers</code> does not update anything if the question number didn't actually change). The missing response rate check should be yet another separate issue then. This 2 errors might have been here for a very long time (even before introducing jstl) already, but since its effects are minimal (only a missing response rate update), we never noticed it. It is not particularly urgent for this to be fixed right away, but an inconsistent response rate may eventually cause problems so we should still fix this one day.
