### ISSUE TITLE
Make comments panel collapsible 

### ISSUE THREAD

**Issue by kennho** [TEAMMATES/teammates#4794]
Currently, the panel that contains general comments for students can't be collapsed. Make it expandable / collapsible. Pages affected are instructorComments.jsp, instructorSearch.jsp, instructorStudentRecords.jsp and studentComments.jsp.

**Comment by tarun14110** [comment]
@thyageshm ,I had implemented this functionality for intructorComments file.
Can I send PR now, so that someone can review my approach and helps in improving. And then I can do same for the remaining ones.
Or should I complete the issue and then send PR ?

![screenshot from 2016-02-18 21 54 28](https://cloud.githubusercontent.com/assets/12219700/13150707/f062d668-d68c-11e5-8998-fd940625934c.png)
![screenshot from 2016-02-18 21 54 57](https://cloud.githubusercontent.com/assets/12219700/13150708/f06bb7ba-d68c-11e5-9560-af79d9cb947f.png)

**Comment by thyageshm** [comment]
its good that you opened the pr. you can always add more after opening the pr.
