### ISSUE TITLE
Some tests cannot pass from 7AM to 8AM

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/teammates#4814]
InstructorFeedbacksPageDataTest
InstructorFeedbackEditCopyUiTest
InstructorFeedbackEditPageUiTest
InstructorFeedbackPageUiTest

If we run those tests from 7AM to 8AM (i.e. from 11PM to 12AM in UTC), they always fail because the start time in FeedbackSessionsForm is adjusted to the next hour so the date in UTC timezone is also increased by 1. Consequently, all test check for the current date will fail.

**Comment by YongJieYongJie** [comment]
I managed to recreate the failures by:
1. Disabling Internet syncing of system time, 
2. Setting system time to 7:05am,
3. Running the 4 tests specified above 

Failure is due to the fact that expected results (i.e., the html for assertion) uses `${today}` placeholder for both exact current date and date corresponding to `getNextHour()`. 

I propose we introduce a new placeholder for dates corresponding to `getNextHour()`.

**Comment by wkurniawan07** [comment]
That's not what placeholders are for; `getNextHour()` is not something that's not unpredictable (on the contrary, it's 100% predictable). This problem can be fixed simply by shifting the hours used in those files forward by one (11:xx pm -> 10:xx pm), so reducing this to `forContributors`.

**Comment by YongJieYongJie** [comment]
@wkurniawan07 may I just seek some further clarification:

**In gist,**
just so that we are on the same page,
am I right that the **placeholders here are used in the opposite manner** – i.e., actual variable values (e.g., `13/03/2016`) in the generated actual HTML are replaced with placeholders (e.g., `${today}`) before comparison with expected HTML

**Specifically, and for instance,**
the `InstructorFeedbackPageUiTest` fails at `verifyHtmlMainContent()`
* expected: `<input class... value="${today}">`
* actual: `<input class... value="13/03/2016">`
* // date of test (in UTC) is 12/03/2016

this is because the html source pre-processing function `processPageSourceForHtmlComparison()` --> `replaceUnpredictableValuesWithPlaceholders()` only does the following:
* `.replace(TimeHelper.formatDate(now), "${today}")`
* and since `TimeHelper.formatDate()` outputs the format in dd//MM/yyyy, i.e., 12/03/2016
* it'll not replace dates reflecting `([between 11pm to 12 am]).getNextHour()`, i.e., 13/03/2016

**Comment by wkurniawan07** [comment]
@YongJieYongJie you're absolutely right :+1:
