### ISSUE TITLE
InstructorCommentsPage: page not updated after adding, editing or deleting a comment

### ISSUE THREAD

**Issue by unyoungwax** [TEAMMATES/teammates#5081]
After adding, editing or deleting a comment, the loading animation on the save/delete button is shown but the page is not updated to reflect the changes (even after a long time). Reloading the page shows the changes correctly. This means that the user needs to refresh the page every time he/she make a change to a comment.

**Comment by damithc** [comment]
@JosephineKwa can confirm this bug?

**Comment by JosephineKwa** [comment]
Yup, it is a confirmed bug. After the add button is clicked, the javascript code clicks the panel heading in order to reload the results upon ajax success. However, I believe PR #3276 removed the reloading of results upon clicking of the panel-heading, after it has been clicked once. The execution of the adding, editing and deleting of comments was not updated to work with the new behavior of the panel-heading when clicked.

**Comment by jkt001** [comment]
This is related to #4697 

A fix to this might have implications on that Issue as well.
