### ISSUE TITLE
Student names not showing up in submission form

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5122]
User reported problem:
The submission form of one team is showing up weirdly:
![image](https://cloud.githubusercontent.com/assets/1673303/13990747/616bf406-f150-11e5-8314-d3ce7e55b5cb.png)

Here's how it shows in V5.72
![image](https://cloud.githubusercontent.com/assets/1673303/13990732/4f2dae9c-f150-11e5-87d3-68ffdeddcdea.png)

Team name `TEAM 1: Demographic Diversity & Socioeconomic Status`. Note that all teams in this course has an `&` in it but only this team is showing this behavior.

**Comment by damithc** [comment]
@kanghj @bamboo3250 anything to do with sanitation?

**Comment by damithc** [comment]
BTW, the two screenshots are from the submission form of `Alex Jones`.

**Comment by damithc** [comment]
The student treated specially seems to be `Jeronimo`. In his own submission page only his name shows up (no team members at all), for current version as well as V5.72

**Comment by kanghj** [comment]
On the student treated specially, there are no team members at all (no answer box)? Or are the team members showing up as empty strings (but with the answer box)?

**Comment by damithc** [comment]
No answer box at all.
Here is a screenshot of student data.
![image](https://cloud.githubusercontent.com/assets/1673303/13991390/f2170b4c-f152-11e5-9d68-4e1f08bbeef6.png)

**Comment by damithc** [comment]
Here's a screenshot of that student's submission page. Not only team members are missing, 2 questions are missing too.
![image](https://cloud.githubusercontent.com/assets/1673303/13991468/47742b24-f153-11e5-8d3a-c425d975ccbf.png)

**Comment by damithc** [comment]
The two missing questions are the ones in which user is giving feedback to team members but not self. So as there are no team members for this student, the two questions have been omitted (I suspect).

**Comment by kanghj** [comment]
Will it be possible to check if there are additional spaces between the words in the team name for the different members in the team? That seems to be a possible cause of this

**Comment by damithc** [comment]
Emailed student list and submission page html to you. No I can't find extra spaces.

**Comment by damithc** [comment]
Although all teams have `&`, this team has `& S`. Would that mess up santization/regex processing?

**Comment by bamboo3250** [comment]
I tried enrolling entire class but that behaviour doesn't happen on current master.
@kanghj Could you verify this as well?

![image](https://cloud.githubusercontent.com/assets/8078323/14005810/0192137e-f1a2-11e5-81f2-0ed8eba55a57.png)

**Comment by damithc** [comment]
Looks like I can fix the problem by simply going to 'edit' function of TEAMMATES and saving each student again. As I did that for each student in the team, they start appearing in the submission form.

**Comment by damithc** [comment]
@LowWeiLin here's another funny thing. The updatedAt time doesn't change when I edit students. It remains as same as created time. This `n/a` was added just now, but the updated time remains the same.
![image](https://cloud.githubusercontent.com/assets/1673303/14006601/e1fbcda4-f1a9-11e5-9151-56ea6b53f0ec.png)

**Comment by damithc** [comment]
When I do an entity search for the team name, only the ones I re-saved comes up in the results. Even when I copy the team name from a student that hasn't been re-saved yet, the search result does not include the student I copy-pasted it from. May be these entities did not get indexed by team name for some reason?

**Comment by LowWeiLin** [comment]
Does the updatedAt time update for other courses? Or is it not working at all?

**Comment by damithc** [comment]
@LowWeiLin let's open a separate issue for that. Unlikely related to this issue.

**Comment by damithc** [comment]
After re-saving each student in that team, now the submission forms show names of all team members. However, the team name does not appear for question 4 for some team members.
![image](https://cloud.githubusercontent.com/assets/1673303/14006760/9a843f5e-f1ab-11e5-9d4d-e74bf1f104a7.png)

![image](https://cloud.githubusercontent.com/assets/1673303/14006774/af7e3c2a-f1ab-11e5-8764-e8e07a0ea202.png)

**Comment by damithc** [comment]
Although the team name is not shown in the submission form, the response shows up correctly in the results.

**Comment by kanghj** [comment]
For those blank team name in the submission page, are those existing responses?

**Comment by bamboo3250** [comment]
@damithc as I mentioned yesterday in the meeting, the reason team name doesn't appear in the search result is probably related to sanitization of team name in document for searching because there are 2 different versions (sanitized and unsanitized).

For the submission form, I'm still investigating it.

**Comment by damithc** [comment]
Yes @kanghj , there are existing responses.

**Comment by kanghj** [comment]
I'm still thinking that this is caused by extra spaces in the team name. We can't trust the csv spreadsheet, because when StudentAttributes are made from Student, sanitizeTitle is already called on the team name, so StudentAttributes doesn't accurately show we have in the database (and therefore the csv file doesn't as well). 

Google App Engine's datastore viewer or html handles this too, so we couldn't have just eyeballed the value of the database to verify if there are spaces:
![gaeconsole](https://cloud.githubusercontent.com/assets/2216119/14023673/67ec1966-f220-11e5-981b-d8cb65373a92.PNG)
![htmlinspect](https://cloud.githubusercontent.com/assets/2216119/14023677/6d6d46c6-f220-11e5-8e64-a033fe79a51e.PNG)

(Notice how the html of the gae datastore viewer actually has spaces in the name, but it's shown without extra spaces on the rendered html)

**Comment by damithc** [comment]
@bamboo3250 Our policy is to sanitize before storing, or sanitize before showing? It can't be both.

**Comment by bamboo3250** [comment]
Somehow I still feel having extra spaces in the team name is infeasible.
@kanghj is there any other way to edit student's team name besides enrolling or editing student's details? I tried both but still cannot replicate this bug.
@damithc It's supposed to be sanitize before showing but the current code is sanitizing before saving (except StudentAttributes). If we know the exact reason, we can write a script to double check and "clean" all affected data in the database. 
At the moment, team names in Student Attributes are fixed but team names as recipient of responses are not. So I think we should write a client script to retrieve data of those responses first (to double check the reason behind this weird behaviour). Then we can discuss the next course of action after that.

**Comment by kanghj** [comment]
@bamboo3250, try editing the team name in a version before the latest one. E.g. Student A with team "Team  1", and Student B with "Team 1", and submit responses for both students. Then checkout to latest master. 

In this case, the issue is that we perform some sanitization (removing duplicate spaces) right after retrieving from the database. So it affects the logic-layer code where we try to retrieve team members of the team (and the team members have spaces in their team names) and fails.

**Comment by bamboo3250** [comment]
@damithc problem solved. After discussing with @kanghj, we decided to write a script to fix this issue for now. Also just a note, next time if someone change code in `Sanitizer`, we need to be careful and check if it will affect the logic or not (for example, comparing old version of data in the database with new version or retrieve entities from the database by sanitized data) then write a script to clean all existing data sanitized by the old version of `Sanitizer`.

**Comment by damithc** [comment]
Yes, in general, any change to how we pre-process data before we save them could require a migration.
