### ISSUE TITLE
Review pull request merging process

### ISSUE THREAD

**Issue by ashrayjain** [TEAMMATES/teammates#5170]
So Github just added this feature! https://github.com/blog/2141-squash-your-commits

Notice that it now supports **custom messages** while merging from Github UI as well as options between merging using `--no-ff`, which we do currently OR squash and merge, which squashes the changes from the PR into one commit and merges that in!

I tested it on a test repo as well and it works beautifully!

Really excited about how this will simplify our process!! :)

@thyageshm @damithc

**Comment by damithc** [comment]
Adding @LowWeiLin @kanghj @wkurniawan07

**Comment by damithc** [comment]
I guess it's 'squash all commits in the branch' i.e. no selective squashing?
Comment history is erased when a branch is squashed?

**Comment by ashrayjain** [comment]
Nope, the comments on the diff as well normal comments in the PR are left intact. I tested it on a test repo here https://github.com/ashrayjain/test/pull/2.

**Comment by ashrayjain** [comment]
Also, yeah, only squash all commits. no option for selective squashing.

**Comment by damithc** [comment]
Before merging online, we should have some confidence that the change is not related to any unstable tests that are omitted in travis. The better solution of course is not to have such unstable tests at all

**Comment by ashrayjain** [comment]
Definitely. In fact, we may want to keep the extra check of the reviewers running the "local tests" on their machines to be completely confident.

**Comment by wkurniawan07** [comment]
Jumping on the bandwagon!

Merging online seems to be safe; we only need to ensure green light from Travis because it treats the PR as if it's going to be merged to the master (despite the fact that the PR may not be up-to-date), and at present we don't have any unstable tests (doesn't mean we won't have any in the future though).

Also, squash-and-merge is a really great tool (been using it for 4 PRs now) because it keeps the commit history to `master` clean (only one commit per PR instead of many) while keeping the actual commits and comments from the PR track-able. It should be the way to go. The only downside is, as mentioned, we cannot do selective squashing, but I think such cases should be very rare.

**Comment by damithc** [comment]
I'm ok with online merging and squashing. 
Although we don't have unstable tests, we should add a few representative tests to smoke tests so that devs can run them before pushing code to ensure nothing major is broken.

**Comment by wkurniawan07** [comment]
Now that we have protected branch and reasonably stable test in CI, the risk of merging online is minimum to none. I'm going to update the docs.
