### ISSUE TITLE
Anonymous feedback not exactly anonymous

### ISSUE THREAD

**Issue by kennho** [TEAMMATES/teammates#5228]
![screen shot 2016-04-15 at 9 50 03 pm](https://cloud.githubusercontent.com/assets/10682388/14563373/2b28537e-0354-11e6-99b2-eaada3e714db.png)

In the case above, student A logs in to view his comments received from his team members. So according to the comments he sees from other team members, he is able to identify **Anonymous student 30999422** is the Team Leader and **Anonymous student 30999423** is a female team member. 

From this, student A is able to deduce the comment to him from **Anonymous student 30999422** which commented "Do your work please" is from the Team Leader and comment from **Anonymous student 30999423** which commented "good" is from a female team member and if there is only one female team member in his team, he will then also be able to identify that too.

PS: A friend taking CS2103T told me this after he received his feedback from his team members. This data is simulated. Not real data from my friend.

**Comment by damithc** [comment]
The reason we keep the same id for all answers from the same person is because it is useful to know which responses came from the same person. e.g. if one person rated me very low in Q1, it is useful to know what comments that person gave about me in Q2. 
To prevent the problem pointed out in this issue, may be can show the same id for *from* side, but not on the *to* side?

**Comment by wkurniawan07** [comment]
Copying what I wrote in #4597, there's more problem than _not exactly_ anonymous: it is _not anonymous_ at all for those who know the algorithm (very easy to reverse-engineer).

**Comment by kanghj** [comment]
Made an issue #5230.
