### ISSUE TITLE
Cannot publish session with '#' in name

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5241]
A user has a session named `Peer Evaluation #1` which gives an 'unauthorized access' when trying to publish. Need a quick fix.

**Comment by bamboo3250** [comment]
![image](https://cloud.githubusercontent.com/assets/8078323/14674374/a1d91964-0736-11e6-8e0f-9ea095d68e30.png)

This is due to the feedback session name is sanitized for javascript but in Java side, we never clean the sanitization and do `verifyAccessible()` on the sanitized feedback session name, which never exists.

I'll find a way to resolve this.

**Comment by damithc** [comment]
Ok. Let's make it quick. The user is waiting to publish the session.
