### ISSUE TITLE
New Contributor Self intro [Gable Heng]

### ISSUE THREAD

**Issue by gableh** [TEAMMATES/teammates#5398]
a) Link to the app: http://4-18-dot-teammates-gableh.appspot.com/
b) Link to the fork: https://github.com/gableh/teammates
c) 
![tinker](https://cloud.githubusercontent.com/assets/5687953/15383057/7eb9ddf4-1dc2-11e6-8cf0-c46accd0586e.png)

Made navbar text pop out on hover
d) Hi, Im Gable Heng, a soon to be year 3 student and im here to help contribute!

**Comment by junhaoyap** [comment]
Hi @gableh, welcome to the TEAMMATES developer community!

Good job in setting up the dev environment! Now that you're done with that and the introductions, the first thing to do to help contribute would be to look for ```d.firstTimers``` issues and solve one of them (try to stick to one so that future contributors can have a chance to solve first timer issues as well) - Looking forward to your contributions - it'll be a great learning journey!

**Comment by junhaoyap** [comment]
@gableh my bad! It seems you have already opened a PR with regards to a first timer issue! Go ahead and fix up the PR based on your reviewer's / others' comments and we'll see your first contribution be in TEAMMATES soon. 

After your first timer issue is done, look for ```d.contributors``` issues :) Look forward to your continued contributions! And great job on taking the initiative to start the issue even before we got to notice it!
