### ISSUE TITLE
New Contributor Self intro [PS Narayanan] 

### ISSUE THREAD

**Issue by PSNAppz** [TEAMMATES/teammates#5464]
a) Link to the app: http://4-18-dot-teammates-psn.appspot.com/
b) Link to the fork: https://github.com/psnappz/teammates
c) 
![image](https://cloud.githubusercontent.com/assets/4481429/15537457/270b11f0-2294-11e6-8ad7-30948325f8e2.png)

Navbar links will get highlighted on hover.
d)Hello Teammates, Myself PSN from India.Third Year BCA student @ Amrita University.
I'm here to contribute to the Teammates community.

Thank you.

**Comment by junhaoyap** [comment]
Hi @PSNAppz, welcome to the TEAMMATES developer community!

Good job in setting up the dev environment! Now that you're done with that and the introductions, the first thing to do to help contribute would be to look for d.firstTimers issues and solve one of them (try to stick to one so that future contributors can have a chance to solve first timer issues as well) - Looking forward to your contributions - it'll be a great learning journey!
