### ISSUE TITLE
Feedback question edit: cancel takes too long

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5468]
Canceling a question edit seems to take a long time. Shouldn't it be a client-side thing?

**Comment by YongJieYongJie** [comment]
Indeed, right now, cancelling an edit just reloads the page using `location.reload();` perhaps this was done to fetch the original question from the server.

**Comment by damithc** [comment]
If the question is a new one, we can just discard it easily. When editing an existing question, it will take some extra work to revert to the original on the client side itself.

**Comment by YongJieYongJie** [comment]
We can
 - make a copy of the DOM sub tree containing the original question when user clicks on "edit",
  - substitute the copy back on when edit is cancelled, and
  - delete the copy on save, before sending the request

**Comment by chowyb** [comment]
Seems to be a possible fix, thankfully the functions use the onclick property; otherwise jQuery event delegation may have to be used.

Noted that the `location.reload()` method presently does not seem to do what it is supposed to do (reload the question) on Firefox, as changes to the DOM are not reverted, although it works fine with Chrome.
