### ISSUE TITLE
Sample course: add sample comments for some feedback responses

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/teammates#5485]
EDITED (by damith)
The sample course (that we create when we add a new instructor account) currently has some comments on students.
Suggested:  Add some sample comments for feedback responses too

**Comment by Mynk96** [comment]
@damithc we currently have one feedbackResponseComment in our sample course.On a rough estimate how many more sample FRC should I add?

**Comment by damithc** [comment]
@Mynk96 can you give a screenshot of the feedbackResponseComment  as shown in the sample course? Which session?

**Comment by Mynk96** [comment]
![response](https://cloud.githubusercontent.com/assets/17481466/26750142/3cd42a14-4839-11e7-8543-e5b1b0269ada.PNG)
@damithc Well, the problem is that this comment is only visible in student record of Alice Betsy, not visible in the feedback session results.
I think it is due to the absence of feedbackResponseCommentId in InstructorSampleData.json for this comment.

**Comment by damithc** [comment]
I see. We have to figure out how to make it visible in responses. @TEAMMATES/activedevs any help?
