### ISSUE TITLE
Many Test cases are failing after deploying the app to staging server

### ISSUE THREAD

**Issue by pragin** [TEAMMATES/teammates#5499]
Successfully deployed the app to the staging server. But when I run the tests after deploying, altogether 23 test cases are failing. Many test cases failed because of this exception "java.lang.RuntimeException: java.lang.reflect.InvocationTargetException". Am I good to proceed?

**Comment by kanghj** [comment]
Can you tell us a few of the tests that are failing? I think you can proceed without passing all the tests on your staging server. Some tests may require more setup on the staging server for them to pass, but are not necessarily required for development.

**Comment by wkurniawan07** [comment]
@pragin if you're testing against the staging server, you'll be unable to test about half of the browser tests because the GAE daily quota will be busted well before that (the devdocs has not been updated to reflect this, sorry about that). You can proceed to fixing issues without getting staging green.
