### ISSUE TITLE
Session reminder emails: fix inconsistency in emails sent to instructor

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5697]
For feedback session opening, closing, and published, only one email is sent to the instructors which is telling that the students of the course have received the email.

However, for feedback session reminder, two emails are sent to the instructors: one telling that the students of the course have received the email, and another one reminding the instructors themselves about the feedback session.

Whichever way we're going for, this is an inconsistency that should be fixed.

**Comment by damithc** [comment]
As the two emails have different but legit purposes, at best we can combine both into one email.

**Comment by HirdayGupta** [comment]
@damithc Sir, this is currently what the notification to instructors looks like:

<img width="1138" alt="screen shot 2017-08-22 at 1 14 58 pm" src="https://user-images.githubusercontent.com/18088721/29554221-ef49c5e6-873b-11e7-9c08-60de11fcbe8f.png">

I was thinking of changing the first line to `The email below has been sent to students of course [id] name **and is also to remind you to make your submissions for the feedback session**.` And then, the instructors who have to be both notified and reminded will only receive this email, not both.

Do you think that would be an acceptable solution? How would you suggest wording the one combined email?

**Comment by damithc** [comment]
How about this? 

Keeping in mind the purpose of the 'copy' is to keep instructors informed of what's being emailed to students, ...

1. At session open, pre-close (24 hours before deadline) and close: send students an email informing them about the session. Also email instructors a similar email, but only if they have a question to submit.

2. In all cases above, send a copy to instructors of **emails sent to students**. If the sessions has no questions for students, there will be no emails sent to students and hence there is no need to send a copy to instructor. If the session has questions for students as well as instructors, we end up sending two emails to instructors but that's ok because each email has a different purpose. 

3. When an instructor send a reminder manually (using the `remind` feature), we send a copy to the instructor to reassure that the email went out. In a future PR, we can add a checkbox 'send a copy to me' in the `remind` feature so that the instructor can opt out of that copy.
