### ISSUE TITLE
Remove unused atomic classes in HTML elements

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5766]
Some elements in HTML pages seem to serve the purpose of atomic classes, however these classes are not present in teammatesCommon.css. An example of this is shown below, but there may be others:

![classes](https://cloud.githubusercontent.com/assets/7546744/16475450/42558c36-3eb1-11e6-9345-2500a2cee7d8.png)

These should be removed where possible.

**Comment by LiHaoTan** [comment]
@goodengrish you should try to figure out on your own. Otherwise, it would be someone else doing the work for you. 😃 

If you are finding this issue a little hard to handle, you could start by looking at our [orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) if you haven't yet already.

**Comment by goodengrish** [comment]
Alright, I will share you my progress then :)

**Comment by goodengrish** [comment]
Hello again,

Here is the link to my fork: https://github.com/goodengrish/teammates

I made changes on the HTML files in the path: src/main/ressources.
I took my time to delete the unnecessary classes in these files but I might forgot some or delete useful ones inadvertently.

**Comment by LiHaoTan** [comment]
@goodengrish I'm afraid I don't get what you want to achieve by showing your fork.

In any case, you need to remove all invalid CSS used in all HTML that is not declared in any of TEAMMATES stylesheets. You should figure out how to verify this.

**Comment by wkurniawan07** [comment]
Fixed in V7.
