### ISSUE TITLE
Feedback session results download should support richer format than csv

### ISSUE THREAD

**Issue by rclakmal** [TEAMMATES/teammates#5801]
The idea of this issue is to explore whether we can support richer format such as xls (excel) in feedback session results download. Alternatively, we should look in to the option of opening the file as GDoc.

**Comment by rclakmal** [comment]
@damithc Changing the download type from csv to excel doesn't seem to be hard. It's just a matter of changing response contentType via `setContentType`. 

But the question is why do we need to do that ? Right now, we only have raw data in our downloads and no formatting or additional stuff like charts. CSV files can be opened even by text editors where excel format would introduce tool restrictions. 

Should we keep the original download and introduce excel download as an alternative option. If so how should we indicate this in the UI ? 
![snip20160707_17](https://cloud.githubusercontent.com/assets/794011/16670955/1e54c6de-449d-11e6-8d65-4e554d4931c8.png)

**Comment by damithc** [comment]
The reason to introduce xls format is so that we can introduce more formatting. For example wider columns for columns with more text. We can also improve the readability by adding text formatting etc. But we should still keep csv format as a fall back in case a user does not have a way to open xls files. 
Yes, a button dropdown sounds suitable. We should find better layman-friendly wording for the options though, as most people don't know csv format or the difference.
