### ISSUE TITLE
New Question entity

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#5839]
To enable #5505, we need to migrate FeedbackQuestions to a new entity type. This will be the start of a long-lived feature branch and I will make further issues for this branch. 

At the end of this branch, the code should be able to support both question types. A migration script should then be prepared next, and the support for the old question type removed.  We will have to deploy the code supporting both question types. After deploying, we can run the migration.

**Comment by whipermr5** [comment]
I plan to explore using entity groups over the summer. Looks like it has been tried and reverted before. Flagging this so I can read up more what has been tried before and what has and hasn't worked (maximum number of entity groups in one transaction exceeded due to legacy data not being in the same entity group?), once I'm done with exams.
