### ISSUE TITLE
Richer set of filter functionalities is needed for Session Results Download

### ISSUE THREAD

**Issue by rclakmal** [TEAMMATES/teammates#5859]
Currently, we have a 'search by question text' as a filter. 

![snip20160717_23](https://cloud.githubusercontent.com/assets/794011/16903148/f6c168f8-4c75-11e6-9da8-4e4b2062bec3.png)

The idea of this item is to introduce an extra filter panel (similar to student filter panel) where we can filter by 
1. Question
2. Receiver
3. Giver

Student filter panel
![snip20160717_24](https://cloud.githubusercontent.com/assets/794011/16903163/8919db0e-4c76-11e6-88e9-001cc1718397.png)

@damithc and all
Few questions to start with,
1. these new filters should these be included in a panel which is visible all the time or when should it be visible ?
2. Should we follow a similar approach as in Student filter panel (checkboxes?) ? 
3. If we bring all the data for a give session(without applying any filter) on the first load, doesn't it make sense to do the filtering in the frontend ?

**Comment by damithc** [comment]
We can actually start this as a new `Reports` feature.  i.e. separate tab
We can add these features incrementally.
1. Filter by question (same session)
2. Filter by question (multiple sessions from same course)
3. Filter by giver/receiver

**Comment by rclakmal** [comment]
@damithc for the same session filters (such as Filter By Question) wouldn't it make sense to have them in the current `instructorFeedbackResultsPage` view rather than in a new tab.

**Comment by damithc** [comment]
This new feature is actually a 'custom report' feature that is mainly for creating cross-session results. e.g.  Might as well keep it in a separate tab rather than cram more things into the a session's results page which can never go beyond a single session. Keeping it separate reduces the risk of breaking the results page that is vital to all users. It will take a few years before the custom reports feature is mature and widely used. At that point we can replicate some of its features in the results page itself.
But perhaps it may be too big for you to attempt at this late stage of the summer.

Coming back to filtering within a session, may be use a modal dialog to select which questions/sections/givers/receivers to show? I still think the filtering should be done at backend as we cannot afford to fetch all results of big courses to the front end. I'm not sure how much work needs to be done in the backend for that kind of filtering though. @kanghj any thoughts?

**Comment by kanghj** [comment]
If we extend or reuse `instructorFeedbackResultsPage` for this new page, it should be relatively smaller to get that new feature functional.
For the filtering on the backend, it shouldn't be hard to filter based on any of questions/sections/givers/receivers since responses are indexed on those fields.

**Comment by rclakmal** [comment]
@damithc @kanghj Had a rough look at the feasibility of both features suggested (modal dialog for filtering within a single session and extending IFRP class to come up with a new page). Second work item looks to be bigger than the first. Which one I should focus on implementing ?

**Comment by kanghj** [comment]
@damithc, ping on this.

**Comment by damithc** [comment]
It's fine to do the smaller one and leave the bigger one for the future.
