### ISSUE TITLE
Student: submit using submission link: give clearer indication of success

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5979]
Some students say they are not sure if the submission went through. Perhaps we should use a modal dialog to inform the user of the submission status?

**Comment by wkurniawan07** [comment]
Hmmmm how is this different from sending confirmation email?

**Comment by damithc** [comment]
Confirmation email helps, but it is not immediate. Unlike us, some people don't have their email open all the time :-p Also, email is not completely reliable. Some get trapped in spam filters.

**Comment by damithc** [comment]
It is also a UX flaw. If the user is not sure if the submission went through, our UX is not good.

**Comment by HirdayGupta** [comment]
<img width="1278" alt="screen shot 2017-07-06 at 5 14 26 am" src="https://user-images.githubusercontent.com/18088721/27889434-11c9839c-620a-11e7-844f-f1d10c2bf33c.png">

This success status message is currently shown to users. Would a modal really be required to replace this? If so, since the modal will presumably display after the student hits submit, should the modal's `ok` button make the Student stay in the FS Submission page only? Or back to Student Home page?

**Comment by damithc** [comment]
> This success status message is currently shown to users. Would a modal really be required to replace this? If so, since the modal will presumably display after the student hits submit, should the modal's ok button make the Student stay in the FS Submission page only? Or back to Student Home page?

We can stay in the same page. In fact, that is the case even now if the student is not registered (and therefore has no 'home page') and also those are the students this issue apply to more. They are not sure if the submission was successful because the page remains the same.

**Comment by HirdayGupta** [comment]
Understood @damithc.

Working on this.
