### ISSUE TITLE
Instructor: edit question visibility: warn user against increasing visibility 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5991]
When an instructor is increasing visibility of a question by editing visibility settings and the question already has responses, warn instructor that increasing visibility is not recommended because the responses were submit under the promise of a lower visibility.

**Comment by VamsiSangam** [comment]
Currently, when the instructor edits the visibility field, all existing responses are getting deleted, and this warning comes before saving changes to visibility field -

![1](https://user-images.githubusercontent.com/11662001/26968089-5f4e1f02-4d1e-11e7-890d-ea185c333551.JPG)

So I guess, in theory this issue is solved.

**Comment by damithc** [comment]
> So I guess, in theory this issue is solved.

Not really. We don't want to delete the responses. Instead, just warn. Therefore this requires both backend and frontend changes.

**Comment by HirdayGupta** [comment]
@damithc Would the behaviour and warnings from PR #7642 and PR #7453 lead to the closure of this issue?

**Comment by damithc** [comment]
yes, I think this can be closed.
