### ISSUE TITLE
instructor view results by recipient, question, giver : wrong section expands

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6048]
Clicking on the first panel results in expanding a different section.
![image](https://cloud.githubusercontent.com/assets/1673303/18221686/66be3ec0-71b4-11e6-99d1-6df4b3baa015.png)

**Comment by junhaoyap** [comment]
Clicking on the first panel results in expanding a different section -> Can we have more information?

1. Clicking on the first panel results in only an entirely different section expanding
2. Clicking on the first panel results in both the section expanding as well as an entirely different section expanding

**Comment by junhaoyap** [comment]
In any case, if this is a recent thing - my guess on the issue is the recent AJAX auto changes:

![screen shot 2016-09-05 at 5 20 36 pm](https://cloud.githubusercontent.com/assets/6291947/18243299/19896b5e-738d-11e6-846f-631133cc9664.png)

particularly the ```return``` statement and something like ```section-0``` will result in us hitting the return statement, clicking on that row might trigger some event that is looking for the ```closest something``` which isn't in itself since it's insides has been removed

**Comment by damithc** [comment]
Seems to be fixed.
