### ISSUE TITLE
One-member teams cannot submit MCQ (multiple choice) questions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6154]
There is an error upon submission for the student who is the only team member. In the session that surfaced this bug, there are multiple questions and only the response to the first question (which happens to be a self-evaluation question) is saved.

**Comment by damithc** [comment]
Have another case of this.

**Comment by leelunn** [comment]
@damithc Can you steer me in the right direction on how to add a student account without a valid email for testing?  

For example, I tried to create a course using dev instance with alice.tmms.LeeLunn test account but I cannot access the course when I log in as that user; and, I cannot enter alice.tmms.LeeLunn as a valid email when enrolling a student.

I have also tried to enroll a student in a course on my staging server, but sending an invitation fails, and logging into staging server with a valid gmail address also does not provide access to the course that I created.

**Comment by damithc** [comment]
@leelunn Did you try point 10 of [this section](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md#setting-up-the-dev-server)?

**Comment by leelunn** [comment]
@damithc Thank you, this got me going.

The issue to this problem is in FeedbackSubmissionEditSaveAction.execute().  The offending code is at line 96: 

`int numOfResponsesToGet = Integer.parseInt(totalResponsesForQuestion);`
`String qnId = "";`

The problem occurs when the number of responses is zero.  In this case, the qnId is never set from response.feedbackQuestionId, which causes a null pointer exception following the for loop that aggregates the responses for this question.

i believe the best solution for this problem is to prempt any further execution of code in the current iteration of question processing by including a continue if numOfResponsesToGet == 0.  However, since I am still very unfamiliar with this code I would like some commentary if further action is necessary in the case of no responses for the question.

**Comment by damithc** [comment]
@kanghj can help?

**Comment by kanghj** [comment]
OK, I'll have a look at this

**Comment by kanghj** [comment]
@leelunn, looks right. Caused by #5865 when we started displaying questions on the submit page even when there are no valid recipients.
