### ISSUE TITLE
Student names missing from submission form

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6221]
One user cannot see student names in the submission form. She has tried IE and Chrome. She even sent me the page source and the names are indeed missing. However, when I tried the same page (masquerading as the same user), I can see the names.

**Comment by damithc** [comment]
![image](https://cloud.githubusercontent.com/assets/1673303/21127949/c497850c-c131-11e6-8014-45a1bb3cb854.png)

![image](https://cloud.githubusercontent.com/assets/1673303/21127961/d435a26e-c131-11e6-9191-2aa20b600278.png)

**Comment by damithc** [comment]
@kanghj we had a similar problem sometime back right?

**Comment by kanghj** [comment]
Yes, it happened maybe once or twice before (such as #6020), when a student already submitted responses made to his/her teammates, but members of the team were moved to another team. It could be a different issue this time though, since it doesn't look like there are responses in that screenshot. Is this happening for every question or just for one?

**Comment by damithc** [comment]
Seems to be happening to every question (based on the page source she sent).  
She was able to submit another previous session in the same course.
Here's what the code looks like in the page source she sent:
```html
<div class="col-sm-2 form-inline mobile-align-left"
style="text-align:right">
<label for="input">To: </label>
<select class="participantSelect middlealign newResponse form-control"
name="responserecipient-1-2"
style="display:none;max-width:125px"
disabled>
<option value="" selected></option>
<option value="aaa@mymail.sutd.edu.sg">AAA</option>
<option value="bbb@mymail.sutd.edu.sg">BBB</option>
<option value="ccc@mymail.sutd.edu.sg">CCC</option>
<option value="ddd@mymail.sutd.edu.sg">DDD</option>
<option value="eee@mymail.sutd.edu.sg">EEE</option>
</select>
</div>
```

**Comment by kanghj** [comment]
I am currently not able to replicate this problem. It is strange if this student is experiencing this issue, but not any of her teammates/the admin in masquarade mode.

However, since the displaying of recipient is currently done in a `$(document).ready(...)`, one possible explanation is a slow network. We recently moved the scripts to the bottom of the page, so if `feedbackSubmissionsEdit.js` hasn't executed its `$(document).ready(...)` function, the student would see what she saw in the above screenshot.

**Comment by damithc** [comment]
Let's wait to see if this happens again. Given that 20-30 thousands of students submitted feedback these few months, a systemic error is likely show up more than once. Perhaps we should load the page with a 'loading. please wait...' message which will be removed by the `$(document).ready(...)` function?

**Comment by damithc** [comment]
We have another case of this. Team members have submitted, but one student says he cannot choose rubric options. The screenshot shows that names are missing too. When I access the same page, everything works.
![image](https://cloud.githubusercontent.com/assets/1673303/21967466/de79b07a-dbc2-11e6-90aa-8bd515b10db9.png)

**Comment by damithc** [comment]
We have another case, from the same course. @wkurniawan07 can you investigate if the moving of js file to the bottom could be the cause?

**Comment by damithc** [comment]
One of the affected students say even trying with different browsers did not help.

**Comment by damithc** [comment]
No recent recurrences. closing.
