### ISSUE TITLE
TestNG misconfiguration does not cause build failure

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6269]
Suppose the TestNG config contains a test class that is non-existent:
```xml
<class name="teammates.test.cases.ui.browsertests.NonExistentUiTest" />
```
The test run will definitely fail, but the failure is not captured by Travis CI (it will instead skip the entire test run and mark the build as "passed"). [Example](https://travis-ci.org/TEAMMATES/teammates/builds/186961876).

**Comment by whipermr5** [comment]
I can reproduce the problem locally; when running `./gradlew travisTests` the first test try fails but the second and third are skipped. Upon further investigation, it's due to [this line](https://github.com/TEAMMATES/teammates/blob/c809d91c597124ff2e64d6f30c6a07fe6d566581/build.gradle#L458) in the `onlyIf` clause; the xml report `build/reports/test-try-${id - 1}/testng-failed.xml` is somehow not generated. This causes the rest of the retries to skip and the whole thing to report success. I'm trying to investigate why the report isn't generated now.

**Comment by wkurniawan07** [comment]
@whipermr5 I can [make your life easier](https://issues.gradle.org/browse/GRADLE-1822) here. Bad news is it's something that looks beyond our reach :/

**Comment by whipermr5** [comment]
It fails nicely when `numOfTestRetries` is 0. Looks like the problem lies with the failure not propagating through the skips.
