### ISSUE TITLE
New contributor self intro [Abhishek]

### ISSUE THREAD

**Issue by ovshake** [TEAMMATES/teammates#6417]
App : http://teammates-abhishek.appspot.com/
fork : https://github.com/ovshake/teammates
 I changed the icon of the videotour to a colorful one.  
Before
![image](https://cloud.githubusercontent.com/assets/22028532/22174878/3ca518ec-e00f-11e6-9e79-92d690626e8e.png)

After
![videotour1_ink_li](https://cloud.githubusercontent.com/assets/22028532/22174885/70238ed8-e00f-11e6-80e8-56c3b48f87e5.jpg)

Hi! I am Abhishek from IIIT Delhi. I am new to open source and it fascinates me a lot. It took me 18 attempts to set up the dev environment which has fueled my enthusiasm to contribute to this repo all the more.

**Comment by junhaoyap** [comment]
@ovshake, Welcome to TEAMMATES! Good job on setting up your own version and going through the introduction, especially since you persisted through 18 attempts to set it up, don't be dismayed since not all open source projects are as huge, the larger a project, the more complex the setting up process may be, stark difference from projects in schools!

I will recommend that you start with a first timer issue that you can find to get your feet wet and after wards if the enthusiasm still fires, work on challenging yourself with the higher difficulty issues!
