### ISSUE TITLE
Instructor view session results: numeric scale question: sorting is incorrect

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6437]
See screenshot

![image](https://cloud.githubusercontent.com/assets/1673303/22273321/ff889028-e2da-11e6-8bca-4040d2e001b4.png)

**Comment by xpdavid** [comment]
This is caused by the comparator `sortByPoint` in `common.js`. It use `parseInt()` instead of `parseFloat()`. It can be easily solved by changing `parseInt()` to `parseFloat()`. But more importantly, I have checked that there is not unit js test case for this comparator, therefore, it is also necessary to add test case for this.

**Comment by damithc** [comment]
Yes, we should add tests as well.
