### ISSUE TITLE
Refactor some duplicated methods in InstructorFeedback*Action classes

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#6448]
InstructorFeedbackAddAction and InstructorFeedbackEditSaveAction have implementations of extractFeedbackSessionData() which are almost completely identical with small difference (e.g, error handling, setting 1-2 fields differently).

Similarly for extractFeedbackQuestionData(String) for InstructorFeedbackQuestionAddAction and InstructorFeedbackQuestionVisibilityMessageAction.

**Comment by AnaghHegde** [comment]
@Neurrone 

>Similarly for extractFeedbackQuestionData(String) for InstructorFeedbackQuestionAddAction and InstructorFeedbackQuestionVisibilityMessageAction.

I think `getParticipantListFromParams` method in theses two class is also similar. Not just similar i think they are same (in function and the method definition). Its better if we remove this also and add it to `Action` class.

**Comment by jimmyshephard** [comment]
Will start looking into this

**Comment by thejosharcher** [comment]
@jimmyshephard Are you still working on this?

**Comment by jimmyshephard** [comment]
No. Please go ahead, haven't had time to dig in


On Apr 20, 2017 8:30 PM, "Josh Archer" <notifications@github.com> wrote:

@jimmyshephard <https://github.com/jimmyshephard> Are you still working on
this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TEAMMATES/teammates/issues/6448#issuecomment-296004117>,
or mute the thread

**Comment by thejosharcher** [comment]
Looking at the code, I do not even see a usuage of the method extractFeedbackSessionData() for either class. Testing does not use them, it uses preset data. I believe this code is not needed. Can someone double check this?

**Comment by thejosharcher** [comment]
Opening PR for this.
