### ISSUE TITLE
instructorFeedbackEdit.js: decouple from HTML DOM structure

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6472]
There are many instances where elements are selected using `.eq` instead of by ID. This assumes a certain HTML DOM structure and is easily broken if the HTML structure is updated in future, adding an unnecessary burden on the HTML maintainers to update these references.

Point for discussion: should all elements be selected by ID or is there a place for them to be selected via class followed by `.eq`? Discussion from #6411 carries on here.

**Comment by damithc** [comment]
@junhaoyap @li-kai your inputs?

**Comment by junhaoyap** [comment]
@whipermr5 @damithc @li-kai - roping in those relevant to this discussion

It is not just ```.eq``` that assumes certain structure, whenever we do things like ```div[class=~~~]``` and so on, we also assume that they will always be divs, or when we select tables, what if we change them to divs?

There has always been a problem with changing HTML on TEAMMATES due to the nature of our selectors usage - too many selection depend on certain structures, remember when we had the selector that looks like ```$(something).next().next().next().next()```? cc @wkurniawan07 I'm sure you remember that.. That's an ultimate level of assuming that the HTML DOM structure will remain as it is

Pulling the discussion backwards to whether there are time we want to use things like ```.next()``` or things like ```.eq``` versus always selecting by ID - Yes there are places where we should select things via ```.eq``` and things like ```.next()```, we are just not using it at the right times, let me illustrate with a few examples on how using these things can be semantical and will not assume that the HTML DOM structure is in a certain way

1. Say if we are in a situation where we want to remove the 7th element of a list of items (because the end user clicks on a X that removes that), we can do something like 

```JavaScript
if (7th item exists) {
  $(selectTheParentThatHostsTheLists).eq(7).remove()
}
```

(something like that) and that makes semantical sense whilst not assuming any kind of structure

Compare that with https://github.com/TEAMMATES/teammates/pull/6411/files#diff-d93ba8999a7d5b9053a2638cc49c3cd5R704 - the way it is written assumes that the previous radio buttons will always be ```.eq(-2)```

Hoping this makes a good distinction between how it can be correctly used versus when it assumes a certain kind of structure

2. Let us use back the same example for when .next() is useful and does not assume any structure, say when the end user clicks on the X, and the lists of items are somehow linked, maybe every 2 items are paired and when one of them is "X-ed", the next or previous one should also be removed, we can do something like

```JavaScript
$(thatThing).(next() or prev()).remove()
```

and that is valid and does not assume a fixed HTML DOM structure, it also feels semantically valid

Generally, whenever selectors are used in a way that assumes that something must be a certain type of HTML element or must be embedded somewhere and it feels like that thing can be moved in the future, we are not using the selector correctly, there are always exceptions and when we encounter these exceptions we can discuss about them

Whenever we use selectors, we must be very careful to think, can it move in the future? Is this something that deserves it's own ID? There are many more questions that we should think of and that comes with experience and making mistakes and feeling the pain of doing it in the not so good ways

**Comment by whipermr5** [comment]
Thanks for the detailed explanation! Understand and agree :)

However the reason I said `.eq(-2)` makes sense in this case is because it's selecting the question (not the radio button), and the last existing question is indeed always the second last element in the set of questions (with the last element being the new question). This seems to me quite a permanent structure, unless we're changing the position of the new question frame to be at the top or something. The `.eq(-2)` does not assume where the radio button is within the question - it's the `.find('input[name="numofrecipientstype"]')` part that selects the radio button from within the question.

**Comment by junhaoyap** [comment]
True, I would think it is unlikely to change that drastically at least in the near future, perhaps we could introduce names to help -> ```lastExistingQuestion =...``` because ```.eq(-2)``` can make sense code wise and not to the person reading the code

**Comment by li-kai** [comment]
Naming is a good idea, though probably the best solution would be to decouple the logic with the view.

We are walking through the path of developers during 2008, which triggered the development and rise of javascript frameworks. In fact, [this article](http://beletsky.net/2012/09/why-use-backbonejs.html) says 
> "After some time spend of development jQuery based application you will realize many fundamental issues, like: data does not belong to DOM, events are not limited on jQuery and so on. But the main issue is jQuery apps usually violates the “Single Responsibility Principle”, mixing and manipulation with data and views in the same time. Experienced developers, tries to eliminate SRP issues as soon as possible, almost naturally coming to MVC pattern."

**Comment by wkurniawan07** [comment]
> We are walking through the path of developers during 2008

Precisely my sentiments about the JavaScript code in the entire code base (and it doesn't help that I'm guilty of some of them :face_with_head_bandage:).

**Comment by wkurniawan07** [comment]
Resolved in V7.
