### ISSUE TITLE
InstructorFeedbackEditPage uses -1 as question number of the new question

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6473]
As per title; this convention is not easily understandable from the outside.

Suggestion: use "new" as question identifier and dispense with the integer requirement? Discussion from #6411 carries on here.

Involves code in `instructorFeedbackEdit.js` too.

**Comment by junhaoyap** [comment]
Passing in a negative number can be confusing without any kind of naming cues at the minimum, if due to the amount of effort necessary as this seems to be very legacy stuff, we could abstract it into another method that passes it the ```-1```, just that now this time we call that method rather than pass in -1 directly so it allows the API end-user to understand the effect of calling said method rather than think "What does passing in -1 do?"
