### ISSUE TITLE
Upgrade instance class to F2

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6501]
To improve performance, we can upgrade the [instance class](https://cloud.google.com/appengine/docs/about-the-standard-environment#instance_classes) to F2. However, I'm unable to do that using the GAE admin console any more http://stackoverflow.com/questions/29295703/why-i-cant-see-instance-class-on-application-settings

I think we need to upgrade our config files. I suspect our files follow a legacy format that existed when we started.

**Comment by damithc** [comment]
@whipermr5 as you have an interest in GAE, may be take a look at this one? No hurry.

**Comment by whipermr5** [comment]
Turns out that instance class is now set in `appengine-web.xml` rather than the web console ([doc](https://cloud.google.com/appengine/docs/java/config/appref#instance_class)). Adding a single line `<instance-class>F2</instance-class>` to my `appengine-web.xml` and deploying indeed results in an F2 instance class:

![screen shot 2017-02-01 at 12 40 37 am](https://cloud.githubusercontent.com/assets/6811428/22474549/14dd3abe-e817-11e6-9b23-0ff0b4b7725e.png)
To navigate to the above screen, from the web console go to App Engine -> Versions -> More Columns -> Instance Class

**Comment by damithc** [comment]
Thanks for the investigation @whipermr5
