### ISSUE TITLE
Add more checkstyle rules

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6519]
[Checkstyle](http://checkstyle.sourceforge.net/index.html) is a powerful tool for static analysis. Most of the rules in the [java coding standard](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html) are reflected in the configuration. There are still several rules that can be applied and I want to bring them here for discussion.

For existing checkstyle rule: 

Rules appear in java coding standard (Format : Checkstyle rule name : Summary in the java coding standard)
- `VisibilityModifier` : Class variables should never be declared public
- `FallThrough` : For fall through in `switch` statement, there is a need to write `// fall through` as comment
- `VarableDeclarationUsageDistance` : Variables should be initialized where they are declared and they should be declared in the smallest scope possible. 
- `ImportOrder` : The import statements must follow the package statement. import statements should be sorted with the most fundamental packages first, and grouped with associated packages together and one blank line between groups.
- `JavaDocStyle` : Enforce the java docs style specified in the coding standard
- `CommentsIndentation` : Comments should be indented relative to their position in the code.

Rules that can be considered:
- `MissingOverride` : forcing annotation `@override` for method overriding.
- `DesignForExtension` : if the class is designed for extension, there are several rules to follow.
- `HideUtilityClassConstructor` : enforce private constructor for utility class
- `EqualHashCode` : when `equal` method is there, there must be `hashCode` method
- `IllegalCatch` : to prohibit illegal catch of some exception.
- `IllegalInstantiation` : to prohibit illegal instantiation of class
- `HiddenField` : checks that a local variable or a parameter does not shadow a field that is defined in the same class.
- `MissingSwitchDefault` : force `default:` in switch statement
- `MultipleStringLiterals` : same string literals should be extract to common variable
- `NestedForDepth` : force max depth of nested `for` loop (related to SLAP)
- `NestedIfDepth` : force max depth of nested `if` (related to SLAP)
- `NestedTryDepth` : force max depth of nested `try` statement (related to SLAP)
- `OverloadMethodDeclarationOrder` : The overloading method should be grouped toghther
- `ReturnCount` : Force the number of `return` statement in one method
- `ImportControl` : Force constrain on imported class (e.g. `AccountLogic` should only access `AccountStorage`) 
- `ImportOrder` : The order of import.
- `SummaryJavadoc` : Checks that Javadoc summary sentence does not contain phrases that are not recommended to use.
- `ClassDataAbstractionCoupling` : force the number of instantiations of other classes within the given class. 
- `ClassFanOutComplexity` : force the number of dependency of a class.
- `UniqueProperties` : check the uniqueness of properties in `.properties` files

For none existing checkstyle rule (appear in the coding standard) (could write our own check):
- Naming conversion: boolean variables should be prefixed with `is` .
- Naming conversion: plural form should be used on names representing a collection of objects.
- The missing of `break` in `switch` statement
- Naming conversion: underscores may be used in test method, but not in normal method name (`MethodName`)
- Method length : a method should do only thing and do that well (e.g. the length of one method cannot excess 40 lines)

**Comment by damithc** [comment]
w.r.t. non existent checkstyle rules, some of them may be covered by other tools such as findbugs and PMD which we can add.

Perhaps @wkurniawan07 can give some inputs as he was working on this area sometime back.

**Comment by wkurniawan07** [comment]
I'll do a proper writeup on this tomorrow.

**Comment by wkurniawan07** [comment]
Here's the promised writeup.

Before applying those rules, check for these:
- We use PMD on top of Checkstyle for Java coding practices. The boundary was hoped to be clear, e.g. Checkstyle for style issues and PMD for coding/design issues, but as it happens Checkstyle has ventured to coding/design as well. Nevertheless, try to keep the boundary clear, but in the event of PMD not having the rule that Checkstyle has, and the rule is good to be included, feel free to include it.
  - Many of the rules you listed as "can be considered" have been enforced by PMD.
  - You may think of "Can we move everything to Checkstyle?" right about now. The answer is no; in terms of coding/design-related rules, Checkstyle still trails PMD by quite a long shot.
- I did add FindBugs some time back, but we only enforce one rule and thus it is as good as non-existent. Powerful as it may (Checkstyle and PMD cannot lint at bytecode level as FindBugs can), it lacks a critical feature: ability to print violations in the build log. For a CI environment, this is a must-have.
- The rule should either be reasonable to have or documented in our coding standards (particularly for style-related rules). Do not include a rule just because "I like this rule and want it to be included".

I will talk about more rule-specific issues on a separate comment.

**Comment by wkurniawan07** [comment]
Rule-specific issues:
- `NestedForDepth`, `NestedIfDepth`, `NestedTryDepth`, `ReturnCount`, `ClassDataAbstractionCoupling`, `ClassFanOutComplexity`: these are related to code quality metrics (my lightning talk topic on Monday!). Powerful as they may, I was concerned that these rules are too domain-specific (i.e. more beginner developers may not be able to grasp the concept of "fan out complexity") to be applied to the project, and if the benefits brought by them are worth it (this is the kind of trade-off you need to consider when managing a software project of this scale 😅).
  - Having said that, you could try to enforce the easier-to-grasp ones like the `Nested*Depth`.
- `ImportControl`: I use Macker for this purpose, although admittedly it has not progressed beyond the two rules I added when setting it up initially. You can try experimenting this rule and if it works as good as Macker, we can get rid of it.
- `JavadocStyle`, `SummaryJavadoc`: basically, any Javadoc-related rules was not in the radar back then (when these tools are introduced) because Javadoc is a huge technical debt, perhaps the biggest in the project. Most attempts to enforce any Javadoc-related rule will result in "Curse it, 1000 violations? I can't do this alone." If you encounter rules with little amount of violations or if you feel you can fix all of them yourself, go ahead. :smirk:

**Comment by damithc** [comment]
@xpdavid @wkurniawan07 can/should this be done by new contributors, one rule at a time?

**Comment by xpdavid** [comment]
I don't think new contributors can handle the analysis and changes for adding new rules. However, they can contribute to eliminating suppressions in CheckStyle (see `teammates-checkstyle-suppressions.xml`, almost all of them are suppressions to Javadocs and they are easy to be fixed). 

Regarding adding new rules (not only to CheckStyle, but also to any static analysis tool we used like Macker, FindBugs and PMD), I agree with @wkurniawan07's comments as it is not like `I like this rule and want it to be included`. To implement the rules and make the necessary changes, a careful analysis of benefits and trade-off should be done in the existing codebase. This task will be more suitable for any CS3281's student or CS2103R's student.
