### ISSUE TITLE
Enrolling a new student deletes previous student in the list

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6534]
Environment : live server at V5.94

A user has reported that adding a new student to the course deletes the student immediately above the new student (in alphabetical order). I tried using the same course and the behavior is confirmed for the student user wanted to add.
However, I was able to add an entirely new student to the same course without a problem. So I wonder if the problem is related to the fact that the student was already in the course before and was deleted but some of his responses were left over (should have been deleted, but wasn't).

**Comment by damithc** [comment]
@whipermr5 perhaps your troubleshooting magic can reproduce this error? No pressure :-)

**Comment by damithc** [comment]
I'm awaiting some more info from the affected user. Will update when I receive.

**Comment by damithc** [comment]
Apparently, halfway into the feedback session, the instructor realized that 9 students were having the wrong email address (email address column shifted by one row). So she edited those 9 students to fix the email address. Somehow that created this situation.

**Comment by damithc** [comment]
Lowering priority slightly because the bug affects only a limited usage scenarios.

**Comment by whipermr5** [comment]
Were the wrong email addresses due to wrong user input or a bug in teammates?

**Comment by damithc** [comment]
user error. It's a common user error
-- 
Sent from a mobile device.

**Comment by damithc** [comment]
I suspect this is a result of using the email address to construct the key of the object and later the key is going out of sync with the actual email because an update to the email was not carried out correctly (due to a bug in the code or a database operation failing halfway - most likely the former because the user said it happened many times). 

Let's say X's email is later assigned to Y.
Now, there is an update to X which is translated to `delete existing X and create a new X with new data`. However, `delete existing X` part is mishandled and become `delete existing Y` because of a mismatch in the key.

The above is speculation based on external behavior (I didn't look at the the code).

**Comment by boxin-yang** [comment]
Hi, prof, would you please elaborate more on the bug? So the bug is when you are updating the email the old student rows are deleted?

I looked through the code. When adding the students, for each student, the StudentLogic::enrollStudent(StudentAttributes, Boolean ) would first check whether there is an email registered in this course . If true, the class updates the students info in the database. 

Would you please elaborate on what is the unexpected behaviours here and what is expected to be done for this issue. I am interested to fix this bug :)

**Comment by damithc** [comment]
@boxin-yang 

Steps that might potentially reproduce the error (based on user feedback):
1. Enroll student Adam with betsy@email.com and Betsy with charlie@email.com
2. Edit Adam's email to be adam@email.com
3. Edit Betsy's email to be betsy@email.com (which previously belonged to Adam).
4. Bug: Adam is deleted while Betsy's email is updated as requested.

Try the above and let us know what happened.

**Comment by boxin-yang** [comment]
Hi Prof, I cannot reproduce the error. 

I enrolled the students twice each with content:

Section | Team | Name | Email | Comments 
Tut Group 1 | Team 1 | A | B@email.com 
Tut Group 1 | Team 1 | B | C@email.com | Exchange Student

Section | Team | Name | Email | Comments 
Tut Group 1 | Team 1 | A | A@email.com 
Tut Group 1 | Team 1 | B | B@email.com | Exchange Student

And i got 3 students with:
    A | A@email.com 
    B | B@email.com 
    B | C@email.com 

Then I cleared students and enroll with:

Section | Team | Name | Email | Comments 
Tut Group 1 | Team 1 | A | B@email.com 
Tut Group 1 | Team 1 | B | C@email.com | Exchange Student

Then I used edit page instructorCourseStudentDetailsEdit to edit A and change his email to A@email.com and edit B and change his email to B@email.com, as a result I have 2 students with:
A | A@email.com 
B | B@email.com 

I cannot reproduce the error on both my dev server and staging server ( commit number: eb92e6ad5526fb0d739681643200ee071537a6ab)

**Comment by whipermr5** [comment]
I found the problem! Turns out `updateStudent` in `StudentsDb` does not update the primary key _at all_ upon updating the email address of the target student. The primary key of `CourseStudent` is a generated ID: `private String makeId() {
    return getEmail() + '%' + getCourseId();
}`. Editing the email changes the `email` property but not the `id`.

Steps to reproduce:

1. Add student B with email `a@host` to course `ABCDE`
2. Observe in the Datastore viewer ([dev server link](http://localhost:8888/_ah/admin/datastore?&kind=CourseStudent)) the created entity has ID `a@host%ABCDE`
2. Edit student B's email to `b@host`
3. Observe in the Datastore viewer that the entity still has ID `a@host%ABCDE`, though the `email` property was updated correctly
4. Add student A with email `a@host`
5. Student B is deleted as the entire existing entity was updated with the details of student A.

**Comment by damithc** [comment]
> I found the problem!

Good work @whipermr5 👍 
@boxin-yang there must be a slight difference between the steps you tried and the steps @whipermr5 tried, which means the bug is in a specific path of the code.

**Comment by whipermr5** [comment]
Must include an add step where a student is added with email address already in the database due to the bug.

**Comment by damithc** [comment]
> Must include an add step where a student is added with email address already in the database due to the bug. The bug is always there but only manifests in the add step.

My bad. I should have included that in the steps I gave.

**Comment by damithc** [comment]
> Outline of likely solution:
> 1. Upon email address update, delete the entity and create a new one with the new id. Hopefully CourseStudent does not have any child entities in the current implementation?
>2. Perform any necessary cascades. Is there anywhere else that references the id?

There's a chance that recreating a student object will invalidate all access links sent to that student previously (access link is tied to the object key), which may be ok because they went to the wrong email address anyway. ID is a private field (right?) so by right other classes should not be referencing it.
