### ISSUE TITLE
Instructor: copy session: allow observers to copy sessions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6594]
A user reported that an instructor having 'observer' level permission encounter an error when trying to copy a session from the course.

v5.95

EDIT: An observer should be able to copy sessions, **as long as the instructor has edit permissions for the destination course.**

**Comment by wkurniawan07** [comment]
Changing the label. "User reported" unfortunately means it needs investigation.

**Comment by wkurniawan07** [comment]
@boxin-yang can try and troubleshoot this?

**Comment by boxin-yang** [comment]
Will look into this

**Comment by wkurniawan07** [comment]
@chowyb can you look into this?

**Comment by chowyb** [comment]
Currently, observers are not actually able to copy feedback sessions. When using the "Copy from previous feedback sessions" button at the top, the sessions in the course where the instructor is an observer will not be displayed.
![copy1](https://cloud.githubusercontent.com/assets/7546744/26292366/efafe048-3ee7-11e7-91c5-e6feaecd60b2.png)

However, for the list of sessions at the bottom of the page, the "Copy" button is enabled:
![copy2](https://cloud.githubusercontent.com/assets/7546744/26292368/f22ba15e-3ee7-11e7-9597-626c783b0dc7.png)

Attempting to copy from the resulting modal however results in an error:
![copy3](https://cloud.githubusercontent.com/assets/7546744/26292371/f4f8d29e-3ee7-11e7-87dc-818079f5d2d9.png)
The backend throws an exception as follows in this example: `teammates.common.exception.UnauthorizedAccessException: Course [insta.exa-demo] is not accessible to instructor [instb@example.com] for privilege [canmodifysession]`

To fix this, it might be possible to do one of the following:

1. Simply disable the "Copy" button.
2. Tie in the permission to copy feedback sessions to a different one instead of "Create/Edit/Delete Sessions". However, no other suitable permission level seems to exist.
3. Allow any instructor registered in the course to click on "edit" for a feedback session in the course, but disallow the instructor from actually editing anything on that page if he or she does not have the permission to do so. This is already in use when viewing course details, and the list of instructors for a course:
![copy4](https://cloud.githubusercontent.com/assets/7546744/26292372/f6b306fe-3ee7-11e7-9570-e776613e3863.png)
Then, the ability to copy sessions can be granted to any registered instructor, instead of requiring a certain permission level to do so, since no hidden information can be obtained by copying an existing session (eg. an instructor could copy an existing session and then view the details of the copied session to figure out what the original session looked like, if the ability to copy but not view sessions was given).

**Comment by damithc** [comment]
Allowing the 'copy' operation for any instructor in the course (irrespective of permissions) seems to a good option.

**Comment by HirdayGupta** [comment]
> Allowing the 'copy' operation for any instructor in the course (irrespective of permissions) seems to a good option.

@damithc I'm not sure I fully understand what you mean here sir. The reason I am having trouble is that since Observers and below do not have permission to create/edit/delete the session, wouldn't it be useless to them to be able to copy sessions? What would they be able to do once they have copied the session? They can't publish it, right? If the goal is to enable them to view the session, just to see what the session looked like, then we can always follow the 3rd suggestion by @chowyb in a separate issue. (And in fact, to make it even clearer, we can not only enable the edit button but also change the text to 'view questions' or something of the sort instead of 'edit)' But giving the ability to "copy" a feedback session, gives the wrong impression to an observer (or below).

In fact, I agree with @chowyb's first suggestion, which was to disable the copy button for observers and below.

**Comment by damithc** [comment]
You missed the point of this feature. If I'm observing a course run by a colleague, I should be able to copy a session from their course to my course. Once the session is in my course, I am no longer an observer for that session and should be able to edit it.
Sorry the initial description is not clear about this.

**Comment by bqnguyen94** [comment]
May I ask, what instructor type does `PRIVILEGES_CUSTOM` represent in `InstructorPrivilege` ? I'm going about allowing 'copy' for all instructor type in the course by adding a new privilege type, so should `PRIVILEGES_CUSTOM` be allowed to 'copy' sessions as well?

**Comment by damithc** [comment]
I'm guessing (without looking at the code) it pertains to this option:
![image](https://user-images.githubusercontent.com/1673303/35835823-e7c76f16-0b17-11e8-8819-c2e82a1f275f.png)
I could be wrong though.

**Comment by bqnguyen94** [comment]
Right now the 'copy' action requires `canmodifysession` privilege. I have tried to replace it with `canviewsessioninsection`. Is this recommended or should I add a new permission, e.g. `canviewsession`?
