### ISSUE TITLE
About page: Use data object to contain name of contributors

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#6731]
**Description of feature/enhancement**

Use data object such as JSON or POJO to contain the name of contributors, committers (less likely), and core team members (highly unlikely due to the variations in formatting), and use JS or JSP processes to display them to the about page.

**Justification**

By decoupling data from view, we can more easily manage changes and do processing such as adding new names or counting.

Refer to the last few posts in #6588.

**Comment by wkurniawan07** [comment]
[First variant](https://teammates-wkurniawan07.appspot.com/about.jsp): JSON does not contain core team members.
[Second variant](http://5-97-alt-dot-teammates-wkurniawan07.appspot.com/about.jsp): JSON contains core team members.

Essentially, when the data is fed through a JSON, we cannot do much customization without making the JS file that presents the data complicated. This will not be too much problem for contributors and committers since there are not much information about them, but may be so for core team members.

**Comment by wkurniawan07** [comment]
@damithc any preference on the above two variants?

**Comment by damithc** [comment]
No preference, but I would like to give more information on current/past core members. i.e. all positions held and durations.
Is the order always alphabetical?

**Comment by wkurniawan07** [comment]
Order can be made custom. Alphabetical is just the easiest for adding new members but it's not done often anyway.

For more info on current/past members: what value would they have? Anyone visiting will most probably only care who's maintaining the project now and perhaps current positions, not what happened in the past and all those details. In this aspect, I feel like [PowerPoint Labs](http://www.comp.nus.edu.sg/~pptlabs/contact.html) do it right.

Also, the earliest of core members lack such information (they even lack photos!) and personally I feel we do not do justice for them by providing more information for later members "just because we have them".

**Comment by damithc** [comment]
> For more info on current/past members: what value would they have? Anyone visiting will most probably only care who's maintaining the project now and perhaps current positions, not what happened in the past and all those details. In this aspect, I feel like PowerPoint Labs do it right.

I would like to provide this additional info because recent graduates who are ex-devs can benefit from it during their early career. i.e. there is a public acknowledgement from the project what exactly they contributed in what role. Also, it distinguishes those who do more for the project from those who don't do as much. Two core members who were with the project for the exact same period could have contributed at very different levels and I don't want the two to appear the same in this page. It indirectly  motivate current and future devs to do more for the project. So, the page is not just for the public to know who is maintaining the project (that's only one of the objectives).

It's fine if we don't have this info for earlier devs who graduated long ago; it doesn't help them much anyway. But we need to order committer and above in chronological order so that recent devs appear at the top.

**Comment by damithc** [comment]
Closing to focus on higher priority issues. Will be reopened later.
