### ISSUE TITLE
Separate the UI and logic for EmailLogEntry

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#6753]
Currently, `EmailLogEntry.java` is used to generate html code to display the email log table. We should separate the logic and UI thing and only leave the HTML tag to JSP file.

**Comment by Neurrone** [comment]
@xpdavid was also about to raise an issue about EmailLogEntry, since the HTML it generates includes inline javascript e.g onclick="submitLocalTimeAjaxRequest('1488798668752', Admin',this);">`; the parameters the javascript function requires should be provided by data-* attributes instead, and binding done in the js. Will you be fixing that as well? Or should I open a new issue for it?

**Comment by Neurrone** [comment]
Oops, sorry I just realized this is EmailLogEntry, not AdminLogEntry.

**Comment by xpdavid** [comment]
@Neurrone No, I was doing the more high-level thing in #6524. Will do more after this.
