### ISSUE TITLE
Intellij setup: git error reported at start up

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6787]
This error is shown at start up
![image](https://cloud.githubusercontent.com/assets/1673303/23821808/ac14a668-0678-11e7-9ee9-9538f649cab1.png)

More details:
![image](https://cloud.githubusercontent.com/assets/1673303/23821812/e3dd914a-0678-11e7-8a1a-35464b4c4a56.png)

**Comment by samsontmr** [comment]
It seems that they are tracked so that they can be distributed to new users, but ignored so that changes they make to the files (e.g. IDE Preferences) don't get pushed to the repo.

**Comment by damithc** [comment]
I see. So not a problem? In that case, we might want to mention that it in the docs. i.e. tell users why it appears and ask them to ignore it.

**Comment by wkurniawan07** [comment]
This is a common issue in Git, where `.gitignore`-d files (I'll refer to these as "ignored files") are still tracked. It can happen due to reasons such as:
- Ignored files are forced to be tracked (`git add -f`).
- `.gitignore` is updated but the ignored files are already tracked.

This is not wrong/error-causing per se (IntelliJ just being picky about this), but not a good practice either. Rather than sweeping the problem under the rug, the more correct way to handle this problem is to find out why those ignored files are still committed, and tell `.gitignore` to be silent about those files if really needed.

**Comment by samsontmr** [comment]
@damithc yep, it's not a problem, at least for the IntelliJ run configurations.


> why those ignored files are still committed, and tell .gitignore to be silent about those files if really needed.

For the run configs, they are tracked but located in `.idea` which is a ignored folder, hence the warning. In any case, it is good for them to be ignored--contributors won't accidentally push their modified run configurations. We can do a force add when intentionally modifying them.
