### ISSUE TITLE
Add instructions for restoring IntelliJ run configurations

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#6818]
**Problem**: IntelliJ run configurations are removed by IntelliJ upon importing the project.

**Solution**: Add instructions to restore run configurations using git after importing the project.

**Comment by nashmia-riaz** [comment]
Hello. I am a first time contributor working on the code for GSoC 2017 and would like to fix this issue.

**Comment by Malkone** [comment]
Hi, I'm first timer and would like to contribute this issue since it's urgent. Please confirm correct understanding of the task: as I found run configurations for the project are located in folder .idea/runConfigurations, does IntelliJ removes these files when it imports this project ? Should they all be restored from git repository as after latest commint before they were deleted? Thanks
