### ISSUE TITLE
Instructor: edit question: new question after cancel: fix discrepancy between visibility option button label and actual selected visibility option

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#6838]
**Environment**

`master` branch at commit 9168d13

**Steps to reproduce**

1. Start to add a new question in an empty session (no previous existing questions).
1. Set visibility to "Visible to instructors only".
1. Cancel out of adding this question.
1. Attempt to add a new contribution question (without refreshing the page).

**Expected behaviour**

<img width="1108" alt="screen shot 2017-03-17 at 11 32 23 am" src="https://cloud.githubusercontent.com/assets/6811428/24027875/9992bbce-0b05-11e7-8a29-690b2cebb3fe.png">

**Actual behaviour**

<img width="1108" alt="screen shot 2017-03-17 at 11 32 13 am" src="https://cloud.githubusercontent.com/assets/6811428/24027877/9db69b26-0b05-11e7-8b33-1f81600f1983.png">

**Comment by VamsiSangam** [comment]
Working on this.

**Comment by VamsiSangam** [comment]
I managed to fix this bug, but `FeedbackContributionQuestionUiTest` fails due to an assertion fail -

![capture](https://cloud.githubusercontent.com/assets/11662001/26760935/39003a4a-4942-11e7-877b-bc57cdf4421d.JPG)

It says the input `showresponsesto` is expected to be `RECEIVER,OWN_TEAM_MEMBERS,RECEIVER_TEAM_MEMBERS,INSTRUCTORS` but is found to be `RECEIVER,RECEIVER_TEAM_MEMBERS,INSTRUCTORS`. Can anyone explain what the `OWN_TEAM_MEMBERS` means? Intuitively, `RECEIVER,RECEIVER_TEAM_MEMBERS,INSTRUCTORS` seems to be correct for a team contribution question. Can I modify this assertion?

**Comment by chowyb** [comment]
`OWN_TEAM_MEMBERS` refers to the team members of the student that is giving the response. In the general case where the student giving the response and the student receiving the response are in different teams, `OWN_TEAM_MEMBERS` and `RECEIVER_TEAM_MEMBERS` would refer to different students. However, in the case of team contribution questions, these should refer to the same group of students.

Changing the assertion however is not recommended, unless it can be shown that this does not affect the correctness of the code (ie. students/instructors who are allowed to see the responses can see them, and students/instructors who are not allowed to see the responses cannot).

**Comment by VamsiSangam** [comment]
Thanks @chowyb :+1: . Will work on it.
