### ISSUE TITLE
New contributor self intro LIU JIAHAO

### ISSUE THREAD

**Issue by LIUJIAHAOCS** [TEAMMATES/teammates#6854]
a) link to your app - https://teammates-liujiahao.appspot.com
b) link to your fork - https://github.com/LIUJIAHAOCS/teammates
c) a screenshot of the change you did (as seen on the UI)
![screen shot 2017-03-18 at 10 03 33 pm](https://cloud.githubusercontent.com/assets/14244291/24072800/8c3a0bf8-0c27-11e7-8379-b5739c838826.png)
I add in a welcome message with the picture which can link to feature page, this can be further improved to show the latest news for users to view.
d) your real name and a short self-intro
Hi all, my name is LIU JIAHAO, currently a 3rd-year computer science student from NUS. I found teammates is a really useful peer evaluation tool for students to provide feedbacks. I would like to contribute to this project as much as I can and learn along the way. Thanks.

**Comment by samsontmr** [comment]
Hi @LIUJIAHAOCS, welcome to TEAMMATES! You can start by fixing a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aopen+is%3Aissue+label%3Ad.FirstTimers) issue, then those labelled `d.Contributors`.

Are you planning to apply for GSoC? If you are, please read [our instructions for GSoC applicants](https://docs.google.com/document/d/1Iu63WRIw8uz8liEW089IQHDQTRbh-QoOLMyfTPXNOa0/pub?embedded=true).

**Comment by amarlearning** [comment]
@LIUJIAHAOCS I like the change that you made :+1: 
But there is one thing that I would like to share with you is that there should also be the button to close to close that because it's hiding some of the content on its back, which is hard to read! [Image attached for example]

![screenshot from 2017-03-19 04-43-02](https://cloud.githubusercontent.com/assets/9383897/24076743/a1abe402-0c5e-11e7-914d-16d61ff784c0.png)

Let me know what are your views on that! @samsontmr

**Comment by junhaoyap** [comment]
@LIUJIAHAOCS, welcome to the TEAMMATES community!
