### ISSUE TITLE
InstructorCourseDetailsPageUiTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6934]
v5.100

Failing at line 246

![image](https://cloud.githubusercontent.com/assets/1673303/24280989/1a26be90-1090-11e7-8597-2c5383ab7ddc.png)

![image](https://cloud.githubusercontent.com/assets/1673303/24281034/5c08d9ce-1090-11e7-9bf3-be17b47d5565.png)

**Comment by damithc** [comment]
Failing after multiple tries.

**Comment by damithc** [comment]
Seems like we have a case of status messages leaking between requests.

**Comment by wkurniawan07** [comment]
Related to #2620?

**Comment by damithc** [comment]
> Related to #2620?

Could be. This test case seem to be able to reproduce it reliably.

**Comment by whipermr5** [comment]
Could be due to #6695

**Comment by whipermr5** [comment]
Due to changes in #6695, the request to remind a single student is sent via ajax. My suspicion is that due to the slowness of the live server (slower than dev server or staging server), the ajax request does not reach the browser in time - the browser continues with the test suite without waiting for the request to succeed (there is no code in the test that waits for the ajax request to succeed). When that ajax request eventually succeeds, it adds the status message to the session object, however this status message is not cleared yet until the next page load. The next page load after this request finally succeeds happens to be the subsequent delete action test. In this page load, the status message finally gets displayed (unexpectedly), resulting in the failed test.

**Comment by whipermr5** [comment]
Implication to users: not much, as most users, after clicking on the button to email a student, would not click on anything else until they see the success message (which is only shown after the ajax request succeeds). Even if they do, the only negative effect is that they will see the status message later on in another page - the first page that loads after the remind action succeeds.

**Comment by damithc** [comment]
Good work @whipermr5 👍 
So it is not a new system-wide problem; I can go ahead with the deployment.
However, it is still a slight worsening of an existing problem that might need fixing anyway. Any ideas on a fix?

**Comment by whipermr5** [comment]
To solve the symptoms - add a wait in the test code; also include a loading animation when the user clicks on the button to remind as a visual cue that something is happening. To solve the root issue - we may need to attach some sort of request ID to status messages and only display/clear them from page requests that match that ID. Though I don't think we have such an ID implemented right now.

**Comment by damithc** [comment]
Can we reset the session at the beginning of a request?

**Comment by whipermr5** [comment]
That would prevent the original intention of using the session object, which I believe is to pass parameters securely from a redirect result to other kinds of results?

**Comment by damithc** [comment]
We can mitigate the ill effects by making the status messages more informative and self-explanatory. i.e. they still make sense even if they appear in the wrong page. One of the messages in the screenshot is too generic.
