### ISSUE TITLE
Update: After Updating to the last version of TEAMMATES in Github, my dev server cannot read ES6 files

### ISSUE THREAD

**Issue by nikiforosbotis** [TEAMMATES/teammates#6958]
**Environment**
Dev Server V4.18

**Steps to reproduce**
Log in as an instructor --> 
Courses (Add New Course) --> 
Fill the given form

**Expected behaviour**
In the "Time Zone" section, either the dropdown sections should include some possible choices or the time zone is automatically detected based on my device settings, as stated in the note below.

**Actual behaviour**
Neither of the previous expected behaviors is present:
![a](https://cloud.githubusercontent.com/assets/9116253/24371174/b4537252-1332-11e7-8c95-3bc2e4855173.png)

Until past Wednesday (22/3), I could create a course without facing this difficulty. Thus, the transfer to ES6 has probably caused this problem. Do you have any idea of how can I solve that?

**Comment by wkurniawan07** [comment]
@nikiforosbotis when reporting something against dev server, version number is not meaningful. Use the latest commit hash instead. I will assume you report against the latest `master` branch which is at commit c450c5f.
Based on the report, I am confident that this is due to the ES6 migration done just few days ago. What you need to do is running `npm run build` from the project root folder and it should be fixed.

**Comment by nikiforosbotis** [comment]
@wkurniawan07 you are right, this is the fault. Sorry for not including the version number. Thank you!
