### ISSUE TITLE
Intellij: output directory setting does not persist 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6971]
OS: Windows
Problem: this setting get reset to the `.war` file after a while (screenshot shows the correct setting). I'm not sure what exactly causes the change of the setting (may be restarting the IDE). When not set correctly, it can cause '... does not seem to be enhanced` error.

![image](https://cloud.githubusercontent.com/assets/1673303/24438736/11b0accc-147c-11e7-9e06-db6d7c880b9c.png)

**Comment by leeyimin** [comment]
@samsontmr and I discussed this a while back. Refreshing the Gradle project seems to be one way to reset the output directory. It seems that IntelliJ does not give the correct output folder by default for some of us, thus the need for #6919. 
The appengine gradle plugin produces the exploded app in build/exploded-app by default, so one way is to manually add an artifact that points to build/exploded-app.
We were investigating whether we could just add build or build artifact to the run configuration which will produce the exploded app in whatever directory the settings point to. This seems to work for @samsontmr but not for me.

**Comment by samsontmr** [comment]
Adding `build` to the run configuration causes an occasional error in some tests, which was why we removed it. However, it seems that removing it causes other issues like this one (you'll need to change the folder manually each time). If it turns out that there's no solution that works in all cases for everyone, we'll have to decide which trade-off we're willing to accept.

**Comment by LiHaoTan** [comment]
I think the issue here might not be completely accurate. It seems that IntelliJ's default settings with Gradle is to use a directory with `$ProjectName$.war`.

The enhancement issue might be a separate problem. By using a "different" way of enhancing using IntelliJ's Google App Engine facet, Run enhancer for the following classes and packages on make, I was able to use the "wrong settings" and got it to work.

**Comment by damithc** [comment]
Good work investigating this issue @LiHaoTan. Do propose a solution when you reach one.
