### ISSUE TITLE
Fix typo in header comments for searchStudentsInWholeSystem method in StudentDb

### ISSUE THREAD

**Issue by ablyx** [TEAMMATES/teammates#6975]
Header comment for `searchStudentsInWholeSystem` has a typo. `amdin` should be changed to `admin`

**Comment by HirdayGupta** [comment]
Hello! I haven't made a 'd.FirstTimers' contribution yet. However, I have _begun_ work on changing the Instructor Request Form from a Google Form in [this issue](https://github.com/TEAMMATES/teammates/issues/6976). I would like to sort out this issue just so that I know I am following the correct convention for issue resolution as outlined in the [development workflow guide](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#fixing-issues). Thank you.
