### ISSUE TITLE
Login buttons on homepage can use bootstrap style instead

### ISSUE THREAD

**Issue by dingliheng** [TEAMMATES/teammates#7030]
**Description of feature/enhancement**
Improve the UI of login buttons on home page (i.e., "student login" $ "instructor login").

**Justification**
Not only can the buttons be more attractive and highlighted, but be consistent with other buttons' style which is also using bootstrap.

Before:
<img width="1280" alt="screen shot 2017-04-03 at 3 41 28 pm" src="https://cloud.githubusercontent.com/assets/14024451/24630906/0867a0d8-1884-11e7-88da-9804b805f993.png">

After:
<img width="1280" alt="screen shot 2017-04-03 at 3 41 01 pm" src="https://cloud.githubusercontent.com/assets/14024451/24630911/0d3ce186-1884-11e7-84ef-3d1352a8b709.png">

**Comment by damithc** [comment]
@dingliheng indeed the updated buttons stand out more. The original however, stands out enough (due to the luminous green text) and consistent with the rest of the nav bar. It's not common to have this kind of buttons in the nav bar.
So I'm inclined to keep the current one. Thanks for bringing this up and the suggestion. It's always good to see what the alternative looks like before deciding.
