### ISSUE TITLE
Failed loading JavaScript error

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7050]
In my local server, I am getting `Failed loading JavaScript error` [Screenshot Added]
![screenshot from 2017-04-06 22-42-10](https://cloud.githubusercontent.com/assets/9383897/24767280/1977bfb2-1b1c-11e7-94f9-4685349fed09.png)

**Comment by HirdayGupta** [comment]
Check if you ran the `npm run build` command as mentioned in [this set-up documentation](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#building-javascript-files) to transpile the es6 files into es5 syntax.

**Comment by mshehrozsajjad** [comment]
` npm run  build ` returned following error. Can someone help rearding this?

![Screenshot](https://cloud.githubusercontent.com/assets/19376792/24792954/7d677d0a-1b99-11e7-88da-ec55ef2b607f.PNG)

**Comment by mshehrozsajjad** [comment]
Getting this error on `npm run build` Any help would be appreciated.

![Error](https://cloud.githubusercontent.com/assets/19376792/24795342/7c1f109e-1ba2-11e7-9c84-10904a3f73fa.PNG)

**Comment by amarlearning** [comment]
@HirdayGupta earlier it was working fine! how come it's not working now ?

**Comment by wkurniawan07** [comment]
To everyone who encounters this issue,

On behalf of the team working on the JavaScript code of the repository, I'd like to first apologize. No doubt this is caused by the recent migration to ES6 done only few weeks back.

To resolve this error, you need to do the following:
1. Before proceeding, you need to have Node.js installed in your machine.
1. `npm install` to download necessary tools such as Babel for transpiling.
1. `npm run build` to get `.js` files from the `.es6` counterparts.

**Comment by amarlearning** [comment]
@wkurniawan07 Getting this error!
![screenshot from 2017-04-07 23-47-33](https://cloud.githubusercontent.com/assets/9383897/24815118/b550e00a-1bf1-11e7-8979-f92d44dd41ef.png)
