### ISSUE TITLE
Make statusToAdmin in *Action classes a List

### ISSUE THREAD

**Issue by Neurrone** [TEAMMATES/teammates#7112]
Right now, statusToAdmin is a String, which is annoying whenever multiple statuses needs to be sent, more so if it happens inside separate ifs. 

Changing it into a List would make this much more convenient. However, this is a large-scale refactoring, that will touch all *Action classes.

**Comment by shrut1996** [comment]
I'll work on this

**Comment by sujeet14108** [comment]
@shrut1996  Will you be working on this or should i take this?

**Comment by wkurniawan07** [comment]
@sujeet14108 feel free to take this one

**Comment by arjunsuri** [comment]
Is this issue still open?

**Comment by sujeet14108** [comment]
A PR is already open. Give me a few days to complete it. You can take any other issue

**Comment by arjunsuri** [comment]
Could you please suggest any issue related to Java programming?I will take
it.

On Jul 14, 2017 2:13 PM, "Sujeet" <notifications@github.com> wrote:

A PR is already open. Give me a few days to complete it. You can take any
other issue

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/TEAMMATES/teammates/issues/7112#issuecomment-315306005>,
or mute the thread

**Comment by vandy56** [comment]
@sujeet14108 are you still working on this?

@neurrone @wkurniawan07 can I take a stab at this one?

**Comment by sujeet14108** [comment]
@vandy56 yes

**Comment by shaharyar-shamshi** [comment]
@sujeet14108  @wkurniawan07 Sir  Is this issue still open can I work on this ?

**Comment by sujeet14108** [comment]
@shaharyar-shamshi  You can take this :)

**Comment by nidhi98gupta** [comment]
@shaharyar-shamshi Are you still working on this?

**Comment by shaharyar-shamshi** [comment]
@nidhi98gupta yup I am working on it and half way to open the PR

**Comment by RonakLakhotia** [comment]
I would like to work on this issue.

**Comment by wkurniawan07** [comment]
@RonakLakhotia this issue is no longer valid in V7.
