### ISSUE TITLE
ide-usage.md: add a link to development.md

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#7135]
There is no hyper link to `development.md` page from `ide-usage.md` page. 

![capture](https://cloud.githubusercontent.com/assets/12005551/25066321/46a686f0-2240-11e7-9d49-79211af8e6d4.PNG)

May the link can be given before in the step 6 instead of the link to `static-analysis.md` page.

**Comment by wkurniawan07** [comment]
There is no need for such. The said document is meant for setting up IDE only, which has been made entirely optional by #6980.

**Comment by AnaghHegde** [comment]
@wkurniawan07 I know its optional but its recommended right?. So i thought its better to give a link to development page instead of giving the link directly to the analysis page.

**Comment by whipermr5** [comment]
@wkurniawan07 I actually agree with @AnaghHegde, especially since `development.md` contains further instructions to set up the IDE e.g. creating the IntelliJ Dev Server run configuration; setting the VM arg `-Duser.timezone=UTC` for testing etc. It is also quite strange that the link to `development.md` from `settingUp.md` comes before the link to `ide-usage.md` - even though the IDE step is optional, it can still be placed before the link to `development.md`, as the instructions in `development.md` for running the dev server and tests via the IDE depends on the IDE already being set up.

**Comment by AnaghHegde** [comment]
@whipermr5 I think it can be a first timer issue if we give the proper step of what should be done.

**Comment by wkurniawan07** [comment]
There's always room for improvement, but the rationale for this kind of organization was that the file `ide-usage.md` should contain information that is skippable by anyone who doesn't want to set up IDE.

Perhaps I did not give attention to anyone who actually want to use IDE. 😅 I agree with the following:
> - Even though the IDE step is optional, it should still come before development.md, as the instructions in development.md for running the dev server and tests via the IDE depends on the IDE being already set up.
> - Even if development.md is already linked from settingUp.md, it won't hurt to link it from ide-usage.md too.

However, the link to `static-analysis.md` is justified to be there because it involves setting up those tools in the IDE, without going to the development phase just yet. It still needs to be _before_ going to the development phase, i.e. before any reference to `development.md`.

**Comment by HarshKhatore** [comment]
@wkurniawan07  I am a first timer and can help with this. Can you provide me with further details?

**Comment by HarshKhatore** [comment]
I think it has already been done?
![screenshot 25](https://user-images.githubusercontent.com/17762022/28752334-0cc824d2-753a-11e7-9227-2aeb0b20824d.png)

**Comment by whipermr5** [comment]
There should be a link as the final step.

**Comment by HarshKhatore** [comment]
So we just have to add a new final step for both Eclipse IDE and IntelliJ IDEA?

**Comment by whipermr5** [comment]
Yes, as mentioned in the discussion above. Also as mentioned above, `setting-up.md` should be modified such that the link to `development.md` appears after step 4.

**Comment by gaurav122197** [comment]
@AnaghHegde I have done the following modifications on my forked repository. Are these changes appropriate and sufficient?
![screenshot from 2017-09-09 01-42-39](https://user-images.githubusercontent.com/17140537/30229699-97a5d26c-9500-11e7-891b-64816bc9ec6f.png)
![screenshot from 2017-09-09 01-43-29](https://user-images.githubusercontent.com/17140537/30229698-97a37288-9500-11e7-9b90-ab951be78dc8.png)
