### ISSUE TITLE
Uploading Files 

### ISSUE THREAD

**Issue by angelosdmg** [TEAMMATES/teammates#7211]
Hello Everybody,
I'm trying to create a functionality in order to add instructors or students via CSV file. Can you please provide me with insights on how to upload a file in GAE? Is there an API for that?

*I know that this is not a official "to-do" feature, but please help me do that. I find it very interesting and I'd be glad to implement it (not matter if it gets accepted or not)

Thank you very much.

**Comment by damithc** [comment]
@angelosdmg if you are a first time contributor to TEAMMATES, please start with a `d.FristTimers` issue. 
Please refer to our 'Contributor Orientation Guide' (link given in our [project home page](/teammates/teammates)) for more help.

**Comment by angelosdmg** [comment]
@damithc Thanks for your answer. I may be a first time contributor, I've been reading the code for weeks now though. I chose to do so in order to provide a better user experience for the admins and this could be also done for the student registration.
Do you think such a feature is feasible? Can you provide me instructions?

**Comment by damithc** [comment]
Yes @angelosdmg such a feature may be useful, but you should start with smaller tasks first. Hence the recommendation to do a `d.FirstTimer` issue first.

**Comment by damithc** [comment]
Thanks for the feature suggestion @angelosdmg 

Our resources are limited; so we prefer to spend them on higher priority issues. Also, we can invest in helping a contributor do a big issue only after we have seen evidence that the said contributor is capable of completing such a big issue. That's why we insist new contributors start with small issues and work their way up to bigger issues.

I'm closing this issue. for now Enhancements to student/instructor creation will be added as more specific issues e.g. #7225
