### ISSUE TITLE
Instructor home page: use consistent formatting for tool tip of 'copy' button

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7223]
The copy button for sessions has a different formatting than other tool tips:

![image](https://cloud.githubusercontent.com/assets/1673303/25707346/d1ac1fb0-3115-11e7-9325-fa2789db9f04.png)

![image](https://cloud.githubusercontent.com/assets/1673303/25707383/f2235a56-3115-11e7-8a5b-16447d1cfb34.png)

Suggestion: Use the same formatting for copy button

**Comment by HirdayGupta** [comment]
@damithc working on it. 😄

**Comment by HirdayGupta** [comment]
@damithc Just to be clear you are talking about the copy button in Feedback Session Actions listed alongside the list of feedback sessions in the Sessions page for instructors, right? 

i.e, this set of actions?:
![screen shot 2017-05-06 at 10 58 09 am](https://cloud.githubusercontent.com/assets/18088721/25770141/1e77ec4e-324b-11e7-8f36-e9cb1830cbf3.png)

I am confirming because I am not able to replicate the behaviour you have shown. As of now, when I hover over the copy button, no tooltip displays at all. The GIF below highlights this:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/18088721/25770163/e28eab72-324b-11e7-9d78-37c466bf3f0b.gif)

As of now I have come up with a fix for that^^ issue and it displays the tooltip in the same format. Submitting a PR with the fix soon.

**Comment by damithc** [comment]
@HirdayGupta the issue is present in instructor home page as well as in the `sessions` page.  Perhaps the technique used for the 'copy' button tool tip is not supported in your Browser.

**Comment by HirdayGupta** [comment]
@damithc The fix I've pushed in the PR seems to fix both instances of the issue (since the tag is reused). 

I would also like to know which browser you were using to replicate the behavior. This is because, at least in the tag's HTML file, the copy button did not have any implementation of tooltip at all, so there might be some additional redundant JS code that I have to remove.

**Comment by damithc** [comment]
> I would also like to know which browser you were using to replicate the behavior.

I'm using Chrome on Windows
