### ISSUE TITLE
Instructor: edit session: add icons to buttons

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7227]
In the page used by instructors to edit session/question details, we can add suitable icons to the buttons.

![image](https://cloud.githubusercontent.com/assets/1673303/25738548/59ecaf44-31b0-11e7-992d-92837e71a1ca.png)

**Comment by VamsiSangam** [comment]
Can I work on this?

**Comment by VamsiSangam** [comment]
On an unrelated note, wouldn't it be nice if we added a "Discard changes" option for the feedback session details too? Precisely speaking, when we try to edit a feedback question,

![edit-feedback-3](https://cloud.githubusercontent.com/assets/11662001/25746268/5621ab98-31c0-11e7-94b2-751e22e8ffce.JPG)

we get these options -

![edit-feedback-4](https://cloud.githubusercontent.com/assets/11662001/25746210/039e5948-31c0-11e7-9355-b57742ee067d.JPG)

But when we edit the feedback session details, 

![edit-feedback-1](https://cloud.githubusercontent.com/assets/11662001/25746279/63dccd1c-31c0-11e7-9573-991c7557d144.JPG)

we don't get a "Discard changes" option -

![edit-feedback-2](https://cloud.githubusercontent.com/assets/11662001/25746232/1df79e94-31c0-11e7-8be8-df704a147801.JPG)

(Icons appear because I tinkered with the code)

Justification - If the instructor wants to discard changes in the feedback details, he has no option but to reload the page, but by doing so, they will lose changes made to the feedback questions.

**Comment by damithc** [comment]
> On an unrelated note, wouldn't it be nice if we added a "Discard changes" option for the feedback session details too?

@VamsiSangam please add an issue for it

**Comment by VamsiSangam** [comment]
Added the issue #7232
