### ISSUE TITLE
New contributor self intro Shubham Garg

### ISSUE THREAD

**Issue by shubham49** [TEAMMATES/teammates#7229]
a) Link to my app: https://teammates-shubham49.appspot.com/
b) Link to fork: https://github.com/shubham49/teammates
c) I changes the title to "TEAMMATES (HOME) - Online Peer Feedback/Evaluation System for Student Team Projects" and changed image in the center.
![new_contri](https://cloud.githubusercontent.com/assets/10528953/25743425/eb2cc1be-31b1-11e7-9e33-28c404246ccd.JPG)

d) My name is Shubham Garg. I am a final year student at GNDU. I have made some college projects on Spring, struts, hibernate. I wanted to learn more frameworks and technologies. I never got the opportunity to work with professionals, so I want to learn from them for my personal growth.

**Comment by VamsiSangam** [comment]
Hi @shubham49 ! Welcome to TEAMMATES! :smile:

Looks like you deployed the application perfectly! But you were expected to do your modifications in a new branch named `tinker`, not in your `master` branch. You might have missed the Phase C in [contributor's orientation guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md). Please revert the code in the `master` branch.

Don't worry, take your time to make the changes. Setting up the project is a crucial step. Feel free to comment here if you are stuck at anything. :smile:

**Comment by shubham49** [comment]
Hi @VamsiSangam  Thanks for the help. Actually I am new to git so not very familiar with git commands. 
I have made appropriate changes at my repository.

**Comment by VamsiSangam** [comment]
@shubham49 , you manually removed all the changes. That is not what I meant by revert. Your `master` branch is still 2 commits ahead of `TEAMMATES:master`. I understand you are new to git. So don't hesitate/feel shy to ask for help here. We all came here to learn. :wink:

Have a look at [this](http://stackoverflow.com/questions/6459080/how-can-i-undo-a-git-commit-locally-and-on-a-remote-after-git-push). Instead of removing 1 commit, you simply need to remove 2.

**Comment by shubham49** [comment]
I did everything from eclipse. In the history tab I see two extra commits that need to be deleted.
But there is not option of re-basing master to older revision. 
![image](https://cloud.githubusercontent.com/assets/10528953/25749197/4faf2762-31cb-11e7-9ef9-b0b3e4c5d7a6.png)
Through command line I get status "fatal: your current branch 'master' does not have any commits yet"

**Comment by VamsiSangam** [comment]
It is generally not recommended to use the IDE to do git stuff. Most programmers prefer using the command line. So let us keep Eclipse out of this :stuck_out_tongue_closed_eyes: 

Can you paste the list of commands you executed and their output here so that I can assist you better?

**Comment by shubham49** [comment]
![image](https://cloud.githubusercontent.com/assets/10528953/25749694/0dc26de4-31cd-11e7-85c3-be6c700386e6.png)

**Comment by VamsiSangam** [comment]
It is a little unusual that you don't have an `origin`. Ideally, on typing `git remote -v` you should get a result like this -

![remote](https://cloud.githubusercontent.com/assets/11662001/25755926/78069f94-31e2-11e7-86c8-6a99ac00e1fa.JPG)

I think you might have set up the project a little differently than what's mentioned in the docs. Please start again freshly. Don't feel bad that I'm asking you to set up the project again :sweat_smile: This is a one-time effort, and it ensures that future development won't be messy. I will guide you through the steps.

Please follow the [documentation strictly](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md), and if you have any doubts regarding git commands, please ask here.

So, according to [setUp.md](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md), I assume you have completed Step 1. Now in Step 2, you have already forked our teammates repo. Now you already have a copy of the teammates project in GitHub. To get a copy on your PC, type the command -

```
git clone https://github.com/shubham49/teammates.git
```

Then add a new remote `upstream` by following 2nd point in Step 2 of [setUp.md](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md). As a part of verification, please post the output of `git remote -v` here, after you complete this step.

After setting `upstream`, follow 3rd point in Step 2 of [setUp.md](https://github.com/TEAMMATES/teammates/blob/master/docs/settingUp.md). Now, open this fresh project in your PC, in Eclipse. Follow the settings in the docs exactly as given. Let me know if you have any issues.

**Comment by shubham49** [comment]
I have followed above instructions and reverted my master branch. Now I want to create branch tinker and commit changes through command line. Earlier I did that with eclipse Egit. Please share some resources to make new branch (or to work with branches) and commit selected files to that (as there would be a lot uncommitted files).

**Comment by VamsiSangam** [comment]
Nice work so far! :+1: [Check this link](https://www.atlassian.com/git/tutorials/using-branches) for info about branches. To create a new branch you would do -

```
git branch tinker
```

But remember, doing that does not take you to `tinker` branch yet. And also you must execute the above branch from `master` branch. So to go to `tinker`, you need to checkout -

```
git checkout tinker
```

Then, you would do some creative modifications. You can view the files you changed by -

```
git status
```

Now you need to `add` the modified files so that the file is marked as something called `staged`. [Refer to this](https://www.atlassian.com/git/tutorials/saving-changes) for more info. You can simply do -

```
git add .
```

This adds all the un-staged files. Refer to the link I gave to add certain files only. Now you must commit your changes. You do that by -

```
git commit -m "Changed page title"
```

What you give after `-m` is the commit message. It is highly recommended to give meaningful commit messages, i.e., commit messages must shortly describe what you have done. They shouldn't be something like `Added code`, `Modified page`, etc.

Now [push](https://www.atlassian.com/git/tutorials/syncing#git-push) your changes. Personally I like the Atlassian tutorials a lot. I hope you'll find them useful too :smile:

**Comment by shubham49** [comment]
I made new branch tinker and committed changes. On pushing changes I got "every thing up to date"
![image](https://cloud.githubusercontent.com/assets/10528953/25770639/8694bc50-3258-11e7-9ac2-694f47dacaee.png)
Now just want to verify if everything is set up correctly!

**Comment by VamsiSangam** [comment]
LGTM :+1: Nice work! Please get started by solving a [d.FirstTimers](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.FirstTimers) issue. You are allowed to solve only a single `d.FirstTimers` issue, after which you must move to [d.Contributors](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3Ad.Contributors) issues, where you can work on multiple `d.Contributors` issues.

Good luck :smile:

**Comment by shubham49** [comment]
Do you know why these kind of test cases are getting failed?
![image](https://cloud.githubusercontent.com/assets/10528953/25895446/8ac5cd8a-359d-11e7-9b86-9268d2013f8f.png)
It seems like some sort of character encoding issue.
I have also changed Text file encoding to UTF-8.

**Comment by VamsiSangam** [comment]
Those kind of errors occur due to incorrect encoding scheme. Please check if you have configured your eclipse's project settings according to steps given in [ide-usage.md](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-usage.md). What you need to check for this error is `Text encoding` in the 4th point 

> 4. Configure the following project-specific settings (all can be found in Project → Properties → ...):

Change the encoding scheme to `UTF-8`.

**Comment by shubham49** [comment]
yes I had changed it.

**Comment by shubham49** [comment]
This one worked. I think this link should also be added to docs(may be in troubleshooting-guide.md)

**Comment by VamsiSangam** [comment]
There were plenty of options in that link, right? Can you specify which one worked?

@whipermr5 similar encoding related issues have occurred to people before, and the link helped. May be we should consider adding the link to docs in the future if this issue keeps troubling the devs.

**Comment by whipermr5** [comment]
@VamsiSangam Good idea. Can you open an issue for it?

**Comment by VamsiSangam** [comment]
Done. #7274 😄

**Comment by shubham49** [comment]
@VamsiSangam option 1 worked for me.

**Comment by VamsiSangam** [comment]
Noted @shubham49 👍 Thanks! 😄
