### ISSUE TITLE
Instructor: edit session questions: MCQ and MSQ questions: support generating options from team members

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7237]
Current: 
Options can be generated based on students, teams, and instructors.
![image](https://cloud.githubusercontent.com/assets/1673303/25769855/1e21a2a6-3257-11e7-9a42-8d8948294a3c.png)

Suggested:
Add options `team members (excluding self)` `team members (including self)` 

Justification:
In some cases the choices need to be limited to team members only

**Comment by dipikaisdbest** [comment]
@damithc Could I grab this one? I am a first time contributor.

**Comment by damithc** [comment]
> @damithc Could I grab this one? I am a first time contributor.

@dipikaisdbest If you are first time contributor, you may want to start with an issue labelled `ForFirstTimers`. This issue may be too difficult for a first timer.

**Comment by dipikaisdbest** [comment]
Hi @damithc thanks for a correct guidance.

**Comment by xyliew25** [comment]
Hi @damithc and all, was wondering haven't the two requested options, i.e. `team members (excluding self)` and `team members (including self)`, been added previously, or am I misinterpreting the issue here?

MCQ:
![image](https://user-images.githubusercontent.com/75534016/170866004-670b0d9f-f8ba-40cf-ae11-f6fc18cbf990.png)

MSQ:
![image](https://user-images.githubusercontent.com/75534016/170866025-cd2da58d-fd46-45f6-9d61-4787cac166bb.png)

**Comment by damithc** [comment]
> Hi @damithc and all, was wondering haven't the two requested options, i.e. `team members (excluding self)` and `team members (including self)`, been added previously, or am I misinterpreting the issue here?

yes, looks like it. Not surprise, as this issue is quite old.
