### ISSUE TITLE
'Rank' options: support min/max number of choices

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7282]
Similar to #7280, but for 'rank options/recipients' questions

**Comment by VamsiSangam** [comment]
@damithc sir, in the context of a rank question, how does it make sense to have a min/max number of choices feature? Also please correct me if I am wrong, `min/max number of choices` here means `min/max rank which can be selected`, isn't it? That is, instead of showing options `1 ... N`, we will show options `min ... max` in the ranks drop-down, is this the intention of issue?

**Comment by damithc** [comment]
Rather, `min=3` means the respondent has to rank at least 3 options. Similar for `max`. e.g. Nominate 3-5 peers to be class monitor and rank your nominations.

**Comment by VamsiSangam** [comment]
Ok sir, understood :+1: 

Also, even if there's a `min = 2` or such sort of a restriction, is it considered valid if the student decides to skip the question?

**Comment by damithc** [comment]
Good question. And I guess the answer is yes, to be consistent with how we handle this kind of situation elsewhere. The respondent can still skip questions but if she attempts the question the answer has to follow the given restrictions. That means for `min=2'  case 0 nominations is still valid but not 1 nomination.

**Comment by VamsiSangam** [comment]
Ok, thank you sir.

Working on this issue.

**Comment by whipermr5** [comment]
Pending creation of another issue for rank recipients questions: https://github.com/TEAMMATES/teammates/pull/7972#issuecomment-325191310
