### ISSUE TITLE
*.jsp: change to 2-space indentation

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7352]
Refactor all *.jsp pages to use 2-space indentation instead of 4.

**Comment by amarlearning** [comment]
@damithc taking this one

**Comment by wkurniawan07** [comment]
Just a heads-up, this is quite a dirty work (but somebody has to do it), and it's not as easy as writing a script to change 4 spaces to 2 spaces because of some custom indentations applied in the past. It could be the starting step, but needs manual re-tracing once again to make sure nothing looks weird.

This should be broken into few PRs, otherwise the changeset could easily reach 5 digits.

**Comment by whipermr5** [comment]
Effort tracker, to be updated as each PR is merged:

| PR | Effort |
| - | - |
| #7535 | 2 |

**Comment by sujeet14108** [comment]
@wkurniawan07  I think all files are covered now ?

**Comment by wkurniawan07** [comment]
@sujeet14108 actually, there are some files that you missed, but you have done enough.

**Comment by dipzzzz** [comment]
@damithc can i take this issue?

**Comment by whipermr5** [comment]
@dipzzzz Feel free to take any of the first timer issues you commented on that have no currently open PRs (but you may only choose one).

**Comment by dipzzzz** [comment]
OK.Thank you.
