### ISSUE TITLE
InstructorFeedbackEditPageUiTest: fix unstable visibility message verification

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7450]
All CI builds are failing due to #7300 making a [wrong assertion](https://github.com/TEAMMATES/teammates/commit/e9f697b814a123e342c11f7b47485967a1e8560b#diff-714bdb03e5eff875eaea9c2bf099a9e6R814) and removing one wait call that is actually needed 😅

**Comment by HirdayGupta** [comment]
@whipermr5 does this have anything to do with `teammates.test.cases.action.InstructorFeedbackResponseCommentDeleteActionTest.testExecuteAndPostProcess` failing with message: `java.lang.AssertionError at InstructorFeedbackResponseCommentDeleteActionTest.java:124` (OR) `java.lang.NullPointerException at InstructorFeedbackResponseCommentDeleteActionTest.java:52`

I ask because I have noticed this test also failing across multiple PRs:

- #7427 ([link to travis error logs](https://travis-ci.org/TEAMMATES/teammates/builds/239746185?utm_source=github_status&utm_medium=notification))
- #7236 ([link to travis error logs](https://travis-ci.org/TEAMMATES/teammates/builds/239605055?utm_source=github_status&utm_medium=notification))
- #7449 ([link to travis error logs](https://travis-ci.org/TEAMMATES/teammates/builds/239566263?utm_source=github_status&utm_medium=notification))
- #7441 ([link to travis error logs](https://travis-ci.org/TEAMMATES/teammates/builds/239576847?utm_source=github_status&utm_medium=notification))
