### ISSUE TITLE
Dev docs: move all IDE specific instructions to one page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7490]
Currently, most IDE specific information are in `docs/ide-usage.md` but some more IDE-specific parts are in other docs e.g. `docs/development.md`
May be we should move all such info to one page and point to it from other places?

**Comment by Surya-06** [comment]
@damithc  Would it be ok if I tried to do something about it?

**Comment by damithc** [comment]
@Surya-06 given that we are low on FirstTimer issues (and this issue is simple), I'm going to label this as a FirstTimer issue.

**Comment by Surya-06** [comment]
@damithc Ok then , could you let me know if there is anything in Java??

**Comment by damithc** [comment]
> @damithc Ok then , could you let me know if there is anything in Java??

@Surya-06 You need to go through the issue list and find something you can do. Go through `d.Contributors` issues as they are expected to be easier than others.

**Comment by wkurniawan07** [comment]
At the current stage, `ide-usage.md` is more accurate as `ide-setup.md`. Perhaps rightly so because it's described as `How to set up some IDEs for development` in the docs ToC.

I still think it's better that way because if the build/test/deploy routines are described there instead, devs need to move back and forth between two documents.

**Comment by LiHaoTan** [comment]
To be clear, this issue should be addressed but any contributor should take note of the discussion and when submitting a PR/addressing the problem, one should make proper justifications for the approach taken.

**Comment by bjrodrig** [comment]
Can I work on this? I think it's helpful to move IDE specific instructions to the IDE Usage page. That way contributors do not have to scroll past irrelevant information when reading build/test/deploy routines.

**Comment by wkurniawan07** [comment]
I have the feeling that whatever triggered the opening of this issue has been fixed. @damithc is it the case?
Otherwise, as discussed in #8195, creating a dedicated doc with all IDE-specific instructions actually cause unnecessary bloat and unnecessary navigation (e.g. when reading `development.md`, instead of simply following the flow, one needs to open a new document). The IDE-specific parts existing in other docs are in their respective places for good reasons.

**Comment by damithc** [comment]
> I have the feeling that whatever triggered the opening of this issue has been fixed. @damithc is it the case?

Yes, that seems to be the case.  Closing.
