### ISSUE TITLE
Add source maps for easier JavaScript debugging

### ISSUE THREAD

**Issue by shubham49** [TEAMMATES/teammates#7532]
Debugging of minified JS files is difficult. We can beautify the file for debugging but locating functions in it is difficult. Do we have any other easy method to debug JS? or should we skip minifying JS files for development environment?

**Comment by wkurniawan07** [comment]
I don't see the issue here because:
- Merely not minifying will not grant you access to the original ES6 files; Webpack adds many layers of code in order to make bundling work, and the JS is transpiled to ES5 syntax.
- Most browser debugging tools can prettify minified JS. That means you can add line breakpoints just as you would do for unminified JS. The only downside is they will not recover the variable/function names.

If you are really uncomfortable with the minified variable/function names, you can turn minifying off by simply [removing this line](https://github.com/TEAMMATES/teammates/blob/master/webpack-main.config.js#L50), but I foresee that it will not help that much.

**Comment by shubham49** [comment]
I find it difficult to debug without locating functions and variable names. In that case I guess  there is no other option.

**Comment by whipermr5** [comment]
Source maps?

**Comment by shubham49** [comment]
source maps works without uglify plugin. This works for me. thanks @whipermr5

**Comment by Crphang** [comment]
Closing issue as source-maps are added.
