### ISSUE TITLE
Add `package-lock.json`

### ISSUE THREAD

**Issue by HirdayGupta** [TEAMMATES/teammates#7533]
Current behaviour: Everytime I run `npm install` this file, package-lock.json gets created and gets added to the git changes. 

Should this be ignored by git?

**Comment by wkurniawan07** [comment]
`package-lock.json` is a new concept introduced in NPM 5.0.0, released very recently. If this is anything like Rails' `Gemfile.lock`, then it needs to be source-controlled, but we'd need some time to study it first.

**Comment by whipermr5** [comment]
Noticed this too after updating `npm` on my system :)

**Comment by HirdayGupta** [comment]
Ahh, understood @wkurniawan07. So for now, I shouldn't be committing the changes to `package-lock.json` along with PRs, correct?

**Comment by wkurniawan07** [comment]
It seems apt to add `package-lock.json` to VCS. @whipermr5 any thoughts?

**Comment by whipermr5** [comment]
Just read through https://docs.npmjs.com/files/package-lock.json. Sounds good!

**Comment by wkurniawan07** [comment]
To the one working on this issue: this also calls for making Node.js v8 the minimum requirement. Strictly speaking it's NPM v5, but since it comes under Node.js v8, we might as well make that one the minimum requirement, and Node.js v8 [will be entering LTS phase soon](https://github.com/nodejs/LTS#lts-schedule1) anyway.

**Comment by wkurniawan07** [comment]
Done quite a while back
