### ISSUE TITLE
Attributes tests: avoid passing in an empty Google ID for student profiles

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7645]
The Objectify code constructs a key for the `Ref` object in linking `Account` and `StudentProfile` entities in a parent-child relationship. The key construction fails if the `StudentProfile` ID (the Google ID) is empty. Currently, the code adds an ugly workaround just to get existing tests to pass: https://github.com/TEAMMATES/teammates/pull/7338#discussion_r122919378

The tests should be fixed and the workaround, removed.

**Comment by craaaa** [comment]
It seems to me the underlying problem is that it's possible to build a `StudentProfile` without a Google ID. Changes to `StudentProfileAttributes` created a Builder class, but declaring a Google ID is not required. This freedom seems to only be around because of the tests -- a possible solution is to require Google ID for all `StudentProfileAttributes`, which should then force `StudentProfile` to have a Google ID too. Does this seem fair?

**Comment by whipermr5** [comment]
@craaaa Yes, that's fair 👍 Thanks for taking this up!
