### ISSUE TITLE
Instructor: edit question: do not warn about deleting responses if destructive changes are cancelled

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7678]
Steps to replicate the bug:
1. Click 'Edit' for a question with existing responses.
1. Change the visibility option to some other listed option.
1. Change the visibility option to the original option (or discard changes).
1. Attempt to save the question.

A modal warning the user that responses will be deleted is shown although the visibility is not changed.  

Edit: After #6124 is solved, the issue will not affect (most?) visibility changes, but is still present for team contribution question and when feedback path is edited and then reverted.

**Comment by whipermr5** [comment]
Noticed this too. In fact, steps 2-3 are not even needed.

**Comment by VamsiSangam** [comment]
There are multiple bugs in this issue. As @leeyimin said, discard changes and try to save, `delete existing responses` shows up. It happens because when we restore original version of a question, we only restore the `.panel-body` contents, whereas `editstatus` attribute is changed in `form` tag to `mustDeleteResponses` but it is not reverted. This causes the warning modal.

And about what @whipermr5 said,

> E.g. team contrib questions, for which merely clicking edit followed by save results in the modal warning.

It happens because, when edit button is clicked for contribution questions, `fixContribQnGiverRecipient()` and `setContribQnVisibilityFormat()` are called which change the visibility options (as observed in developer tools), so upon saving the warning modal shows up.

And if I may add another bug. When editing visibility option, simply selecting the same visibility option again (don't even change it to another) will also cause the warning modal to show up! This is because, there's a flaw in checking if the visibility option is changed. Current logic compares the text of `.visibility-options-dropdown button` and the selected option's text. It will always fail due to space issues -

![1](https://user-images.githubusercontent.com/11662001/27926355-c79cee34-62a5-11e7-8942-c50f9c8bd6e0.JPG)

Also upon saving, we need to check if the question is same before and after editing, i.e. cases where visibility option is changed but reverted back to normal, in which case `mustDeleteResponses` attribute value should be removed if present. This too will prevent the warning dialog.

On second thoughts, maybe we should stop instructor from saving a question if it is same before and after editing. We could save a few requests. :stuck_out_tongue_winking_eye:

**Comment by VamsiSangam** [comment]
I'd like to work on this issue. Also to confirm with you @leeyimin , can I assume that the bug I stated above is added to the scope of this issue as well?

**Comment by whipermr5** [comment]
> whereas editstatus attribute is changed in form tag to mustDeleteResponses but it is not reverted

This means the backend actually deletes the responses if the user confirms, right? It's not just an issue of a false warning appearing. I believe this is quite a bad bug, as it means that users cannot edit any part of team contrib questions that already have responses without losing all responses.

**Comment by leeyimin** [comment]
@whipermr5 The deletion mechanism works independently from the front end I believe, see #7642.

**Comment by damithc** [comment]
Does #7642 invalidate this issue?

**Comment by leeyimin** [comment]
@damithc I have tested and the team contribution issue is still present.

**Comment by leeyimin** [comment]
It is still an issue if feedback path is edited once and then reverted to original.

**Comment by whipermr5** [comment]
> It happens because, when edit button is clicked for contribution questions, fixContribQnGiverRecipient() and setContribQnVisibilityFormat() are called which change the visibility options (as observed in developer tools), so upon saving the warning modal shows up.

This is actually due to code I wrote a long time ago 😅 #6669

**Comment by VamsiSangam** [comment]
> This is actually due to code I wrote a long time ago :sweat_smile: #6669

IMO the real culprit is this -

![capture](https://user-images.githubusercontent.com/11662001/27946771-d7b87232-6310-11e7-8c4a-eced374d81bd.JPG)

Whenever the page is loaded, somehow the input fields `showresponsesto`, `showgiverto`, `showrecipientto` seem to set to `RECEIVER,INSTRUCTORS` for all the questions. But when submitting the question form (even without any edits), the correct values are being sent.

![capture](https://user-images.githubusercontent.com/11662001/27946907-6f8273b0-6311-11e7-89b6-4473fcf4be8d.JPG)

I think we should look into this too. Maybe if we loaded the values of `showresponsesto`, `showgiverto`, `showrecipientto`  fields during HTML templating itself, then even if `fixContribQnGiverRecipient()` or `setContribQnVisibilityFormat()` are called for contrib questions, it probably wouldn't lead to a destructive change. Just a hunch :sweat_smile:

**Comment by HirdayGupta** [comment]
@VamsiSangam You are working on this?

**Comment by VamsiSangam** [comment]
Yes I am.

**Comment by zhaojj2209** [comment]
Closing as per https://github.com/TEAMMATES/teammates/pull/12387#issuecomment-1515909055.
