### ISSUE TITLE
StudentFeedbackSubmissionEditPage: Disable text area for closed feedback session

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7797]
Text areas on StudentFeedbackSubmissionEditPage are not disabled and are still editable for a closed feedback session. They should be disabled since feedback can no longer be edited.

**Comment by amarlearning** [comment]
working on this

**Comment by jabrah29** [comment]
I am new to open source and would like to work on this problem. How do I find the file(s) relevant for this issue to fix?

**Comment by HirdayGupta** [comment]
@jabrah29 Since @amarlearning already commented that he would be working on this, the TEAMMATES convention is that you would have to ask him before doing this issue yourself. That being said, you seem to new here, and might want to read our [Contributor Orientation Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) on getting started with contributing to TEAMMATES.
