### ISSUE TITLE
*FeedbackSubmitPageUiTest: Fix dependency on current time

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#7808]
StudentFeedbackSubmitPageUiTest may fail due to test case "Grace period session", as the `endTime` of "Grace period session" is not set with respect to the time zone of the session, but to UTC.

InstructorFeedbackSubmitPageUiTest may fail due to test case "Private session", as it contains a `null` endTime and the `getEndTimeString` fails to handle it properly.

**Comment by leeyimin** [comment]
Some discussion in #7740.

**Comment by HirdayGupta** [comment]
Working on this. 😅

**Comment by HirdayGupta** [comment]
@leeyimin @whipermr5 

Adding in the lines @whipermr5 suggested in https://github.com/TEAMMATES/teammates/pull/7740#discussion_r128686702 solves the "InstructorFeedbackSubmitPageUiTest.java` issue by removing the end time from display altogether. I believe this is how it was done prior to the changes in #7740. ([See line 55 of this diff](https://github.com/TEAMMATES/teammates/commit/929055a735e152f9f86932839fd0014323324c73#diff-465a3e731e2caf55a2fac626e8bf27c3))

However, about the StudentFeedbackSubmissionTest, I think your diagnosis above (which is also what I thought until now) might be wrong. You can try running the test as it is right now in the `master` and add a `Thread.sleep` at between line 102 & 103 and you will see that the test does indeed display the current time in UTC even now (despite the grace period test changing the end time to the Current Time in UTC followed 'getEndTimeString()` trying to convert it to UTC by shifting through offset). I don't see why this happens right now or why our HtmlHelper doesn't replace this with `${datetime.now}`. (PS: same is the case with the end time being displayed in InstructorFeedbackSubmitPageUiTest` but the above solution is for it is good because it also solves an inherent problem with the `convertLocalDateToUtc` method)

**Comment by leeyimin** [comment]
@HirdayGupta I believe the issue is that FeedbackSessionAttributes assumes endTime to "show" time in its timezone. Suppose the desired end time is 21 Jul 2017 1600 UTC+0800, which converts to 21 Jul 2017 0800 UTC, `endTime` should store `21 Jul 2017 1600 UTC`.

So suppose the current time is 21 Jul 2017 0700 UTC+0800 (-1 day, 2300 UTC), 
what the test is doing is setting the `endTime` to `20 Jul 2017 2259 UTC`, 
when it should have been `21 Jul 2017 0659 UTC`. 

This causes the test failure between UTC time 1600 to 0000, as the date in UTC+8 would be a day ahead. 

I believe the current html might even be wrong since the student should have been able to submit his responses due to the grace period effect.

**Comment by HirdayGupta** [comment]
> So suppose the current time is 21 Jul 2017 0700 UTC+0800 (-1 day, 2300 UTC),
what the test is doing is setting the endTime to 20 Jul 2017 2259 UTC,
when it should have been 21 Jul 2017 0659 UTC.

@leeyimin This is exactly what I thought too. And you are correct to an extent. The FS `EndTime` attribute does assume that its data is in the course's time zone and yes, the `StudentFeedbackSubmitEditPage`'s `Grace Period Session` Test Section violates this assumption. However, your suggestion would mean that I set the end time of the course as <The Current Time in the course's time zone> - 1 minute. The problem with this is that our HtmlHelper only looks for dates that are the current date in UTC when replacing with `${datetime.now}`. As a result, I think that instead of changing the end time to be set as the current time in the course's time zone, we should instead change the time zone of the grace session to UTC for the test. Thoughts?

**Comment by HirdayGupta** [comment]
Anyway, I have a couple of possible solutions lined up. I am currently waiting until UTC 1600 to start testing them (all builds are passing now haha). Any suggestions on changing the system time so I can test these now?

**Comment by HirdayGupta** [comment]
> what the test is doing is setting the endTime to `20 Jul 2017 2259 UTC`

Also, just as a continuation to this. What happens next is that when this end time is to be displayed, the `getEndTimeString()` method is called. This method "converts" the given endTime to UTC first by shifting it through the offset of the course time zone (so it converts this date to 20 Jul 2017  14:59) and then this date is sent to the `formatDateTimeForSessions` method which, among other things, also **reconverts** the date to its original timezone (ie shifting it back from UTC to current timezone). So this date again becomes (20 Jul 2017 22:59) - which is basically the current time in UTC. And this is what is displayed in the browser's HTML. 

Now, while this data is indeed incorrect with respect to the session's time zone, it should work for our build because the HtmlHelper's replaceUnpredictableValuesWithPlaceholders() method (See [this line](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/driver/HtmlHelper.java#L390)). only checks for the current time **In UTC**.  And since our page is anyway displaying the current time in UTC, there's no reason for it to not be replaced. 

This is what is confusing me about this issue right now. Hopefully I'll be able to see things more clearly when the tests start failing again. Until then, any further thoughts on what I've said in this comment @leeyimin @whipermr5?

**Comment by HirdayGupta** [comment]
> The problem with this is that our HtmlHelper only looks for dates that are the current date in UTC when replacing with ${datetime.now}. As a result, I think that instead of changing the end time to be set as the current time in the course's time zone, we should instead change the time zone of the grace session to UTC for the test. Thoughts?

@leeyimin @whipermr5 My apologies. I overlooked [this line](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/driver/HtmlHelper.java#L394) in HtmlHelper which sets the current time zone according to the time zone mentioned on the page. This led to my confusion regarding your proposed solution @leeyimin. My apologies once again. 

Changing the `grace period session` part of the `StudentFeedbackSubmitPageUiTest` to set the current time in the course's time zone instead of UTC works as the solution. Thanks and apologies once again :)
