### ISSUE TITLE
Student: submit feedback: use an alternative term to 'To:'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7812]
Requested by a user:

![image](https://user-images.githubusercontent.com/1673303/28487624-316e5190-6ec7-11e7-93f4-8d3ec187ee1d.png)

Problem: The term `To:` indicates the feedback by received by the person in concern although in some cases (based on visibility setting) the feedback may not be sent to the person. Therefore, this term can be misleading.

Suggestion: Use `Evaluee` perhaps with a tool tip `The party being evaluated or given feedback to`.

`Evaluee (Student): Adam`
`Evaluee (Team): Team 1`
`Evaluee (Instructor): Jean`
etc.

**Comment by stanislous** [comment]
Can I take this issue?

**Comment by arjunsuri** [comment]
Please tell me the location of this file.

**Comment by damithc** [comment]
> Please tell me the location of this file.

Figuring out which file to modify is part of your expected work :-)

**Comment by damithc** [comment]
> Can I take this issue?

@stanislous sure

**Comment by stanislous** [comment]
@damithc, for all questions(1,2,3...) do I need to apply these changes?

**Comment by damithc** [comment]
> @damithc, for all questions(1,2,3...) do I need to apply these changes?

@stanislous yes. it shoulb be applied to all question types e.g. essay, mcq, etc.

I'm not sure how much work this issue will take though. If it seems too complicated, feel free to ditch it and look for an easier issue.

**Comment by amarlearning** [comment]
@stanislous are you working on this?

**Comment by stanislous** [comment]
@amarlearning of course. You can work on it. :-)

**Comment by amarlearning** [comment]
@damithc need some confirmation before I proceed with this issue.

1.  Use `Evaluee` in place of `To` and with a tooltip saying `The party being evaluated or given feedback to Evaluee (Student): Francis Gabriel`
![screenshot from 2017-08-02 15-03-52](https://user-images.githubusercontent.com/9383897/28867497-f2f574fe-7793-11e7-9559-82f86ed1b3cc.png)

and same for Team and Instructor?

**Comment by damithc** [comment]
> and same for Team and Instructor?

Yes.

**Comment by amarlearning** [comment]
@damithc there are a couple of cases which are different and needed to be handled differently like:

- When there is `only one instructor`, the view on the student feedback page is something like this _[screenshot]_. In this case, the tooltip can be added as you suggested. 
![screenshot from 2017-08-03 03-03-00](https://user-images.githubusercontent.com/9383897/28897265-8a915238-77fd-11e7-9979-02f6ddf8cd86.png)

- But when there is `more than one Instructor` that is being evaluated, in that case, the view of the student feedback page is something like this: _[screenshot]_. In this case, the tooltip should be general because `Evaluee` can be any out the given options.
![imageedit_2_8607849635](https://user-images.githubusercontent.com/9383897/28897330-dbeb5eee-77fd-11e7-84de-5c8b62b0a03e.png)

***

- The Same problem arises when the `Student` is giving feedback to its `team members`, view of the page _[screenshot]_.  In this case, the tooltip can be added as you suggested. 
![screenshot from 2017-08-03 03-47-43](https://user-images.githubusercontent.com/9383897/28897500-a7cccd72-77fe-11e7-802d-d6eb3fd54577.png)

- And when the `student` is giving feedback to `other student present in the course`, the view of the page _[screenshot]_. In this case, the tooltip should be general because `Evaluee` can be any out the given options.
![screenshot from 2017-08-03 03-49-10](https://user-images.githubusercontent.com/9383897/28897575-fb5484da-77fe-11e7-9dae-d1b8623f6ed2.png)

**Comment by damithc** [comment]
Not sure if you understood the issue correctly. The issue is meant to change only the part `To :`, not the part that shows recipient name.

Current
`To : {Recipient name}`

Suggested:
`Evaluee : {Recipient name}`

`Evaluee` is not a widely used term, hence the need to add a tooltip for it with a longer explanation of what it means.

**Comment by amarlearning** [comment]
> The issue is meant to change only the part `To :,` not the part that shows recipient name.

@damithc that was clear. I have a little confusion about the tooltip. what should be the tooltip out of the two:

1. `The party being evaluated or given feedback to`
2. `The party being evaluated or given feedback to Evaluee (Student): {Recipient name}`

**Comment by damithc** [comment]
First one.
It can be like this too:

Show in the page:
`Evaluee (Student):`

Tooltip for word `Evaluee` : `The party being evaluated or given feedback to`
