### ISSUE TITLE
GateKeeper: Update methods to follow happy path

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TEAMMATES/teammates#7833]
Methods in `GateKeeper`: `verifyLoggedInUserPrivileges()`, `verifyAdminPrivileges(AccountAttributes)`, `verifyInstructorPrivileges(AccountAttributes)` do not follow the happy path. For example:

```
public void verifyLoggedInUserPrivileges() {
    if (isUserLoggedOn()) {
        return;
    }

    throw new UnauthorizedAccessException("User is not logged in");
}
```

The happy path happens when the exception isn’t thrown. As such, the code should look like this:

```
public void verifyLoggedInUserPrivileges() {
    if (!isUserLoggedOn()) {
	throw new UnauthorizedAccessException("User is not logged in");
    }
}
```

Let’s update these methods accordingly.

**Comment by wkurniawan07** [comment]
I think @damithc will have something to say here, particularly about "using guard clause to reduce the nesting depth".

From myself: for this particular case, it does make sense to do the said refactoring. However, "following the happy path" is not and cannot be a hard rule to follow. Otherwise you can easily end up with an arrowhead anti-pattern.

**Comment by Zhiyuan-Amos** [comment]
> "using guard clause to reduce the nesting depth"

This follows the guard clause right? Previously when I coded in Swift, I think the code looks something like:

```
guard isUserLoggedOn() else { // guard clause
    throw new UnauthorizedAccessException("User is not logged in");
}

// happy path
```

> However, "following the happy path" is not and cannot be a hard rule to follow.

Ah I see, noted thanks!

**Comment by damithc** [comment]
Perhaps the name 'happy path' is a bit misleading. Sometimes the main job of a method is an unhappy one. A more accurate way to put it is 'keep the main path unindented'. In this particular case, not withstanding the name of the method, the main job of the method is to 'throw an exception if the user is not logged in' (rather than 'do nothing if the user is logged in'). Therefore, we can argue that the current code keeps the main path unintended. Intuitively, the current code is easier to read too. However, I also understand that this depends on how you interprets the main job of the method is.

**Comment by Zhiyuan-Amos** [comment]
Ah yes. I'm thinking from the perspective of the callers, since the success case of these callers happen when the Exception isnt thrown.
