### ISSUE TITLE
StudentsLogic: Simplify createStudents(String, String)

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [TEAMMATES/teammates#7839]
The code is too hard to understand. 

```
if (StringHelper.isWhiteSpace(line)) {
    continue;
}
```
This code should be called immediately after the for-loop instead of the try-block. 

We can also look to remove the variable `studentEmailList` and simplify this chunk of code to use `studentList` instead:
```
if (isStudentEmailDuplicated(student.email, studentEmailList)) {
    String info =
            StringHelper.toString(
                    getInvalidityInfoInDuplicatedEmail(student.email, studentEmailList, linesArray),
                    "<br>" + Const.StatusMessages.ENROLL_LINES_PROBLEM_DETAIL_PREFIX + " ");
    invalidityInfo.add(String.format(Const.StatusMessages.ENROLL_LINES_PROBLEM, sanitizedLine, info));
}
```

We can also try to apply Single Level of Abstraction Principle (SLAP) on this method as it is too long.

**Comment by wkurniawan07** [comment]
While I have to agree, it will be good if you can qualify/quantify what you meant by "too hard to understand". Is it because of nesting depth? Cyclomatic complexity? Lack of comments? Not testable? Unchecked copy-and-pastes? And what can be done in its place to make it more understandable, with reference to the said metrics?

A generic "too hard to understand" may well be because someone is not well-acquainted enough with the code.

**Comment by Zhiyuan-Amos** [comment]
Ok! Will put additional comments when I'm free. Sorry about that; I wanted to fix it thus I thought I could just raise this issue in a simple manner.

**Comment by Zhiyuan-Amos** [comment]
Done!

**Comment by sujeet14108** [comment]
@Zhiyuan-Amos Are you working on this?

**Comment by Zhiyuan-Amos** [comment]
Hi @sujeet14108, nope as I'm busy, feel free to work on it ^^

**Comment by wkurniawan07** [comment]
@Zhiyuan-Amos I hope you now understand why I asked to make the issue as clear as possible.

**Comment by Zhiyuan-Amos** [comment]
@wkurniawan07 yup thanks! ^^
