### ISSUE TITLE
'Distribute points' questions: increase the width of status info message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7876]
Current:
Very narrow width. Appears squished.

![image](https://user-images.githubusercontent.com/1673303/28749773-3c0ee288-7505-11e7-9a38-252d6384c30d.png)

Suggested:
Increase width so that it appears as one line.

**Comment by uxxSam** [comment]
Hi, I would like to work on this issue.

**Comment by dikshaa42** [comment]
Hi, i also would like to work on this issue.

**Comment by amarlearning** [comment]
@dikshaa42  Since @uxxSam already commented that he would be working on this issue, I suggest you ask him before doing this issue yourself. And since you are new here I would suggest you read our [Contributor Orientation Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md) on _Getting started with contributing to TEAMMATES_.
