### ISSUE TITLE
InstructorFeedbackResultsPage: avoid use of `.click()`

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#7886]
This method does not work on Chrome (causing the AppVeyor build failures after merging #7586), and is sometimes unreliable on Firefox too. Use `AppPage`'s `click` method instead, which uses JavaScript and is reliable across both browsers.

**Comment by LiHaoTan** [comment]
Haha I don't know how unreliable is `WebElement#click` but using Javascript's click would mean that it's not really a UI test (though I am aware of the catches/limitations of Selenium so sometimes we have to use such workarounds).

I am just wondering is this the best option though? If there is a way to get `WebElement#click` we should prefer it, otherwise it is not a UI Test.

**Comment by wkurniawan07** [comment]
@LiHaoTan allow me to give you the deal breaker: <https://stackoverflow.com/questions/38923356/element-is-not-clickable-at-point-other-element-would-receive-the-click>.

**Comment by whipermr5** [comment]
@wkurniawan07 Are you suggesting using `maximize()`?

**Comment by wkurniawan07** [comment]
[We already used that](https://github.com/TEAMMATES/teammates/blob/master/src/test/java/teammates/test/pageobjects/Browser.java#L38), evidently with limited success.
