### ISSUE TITLE
Remove MashupPageUiTest

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#7926]
The mashup page is badly broken and the test is not used for its intended purpose anyway.  Lets get rid of it.

**Comment by amarlearning** [comment]
I'm not 100% sure, but I think removing

- [`mashup.jsp`](https://github.com/TEAMMATES/teammates/blob/5b9b3fbe19355cd1ceb4e7875f4ca2e3846186c5/src/main/webapp/test/mashup.jsp)

- [`MashupPageUiTest.java`](https://github.com/TEAMMATES/teammates/blob/ede7d3932dfb301afb1d89e6647975bd79b5a8c8/src/test/java/teammates/test/cases/browsertests/MashupPageUiTest.java) file.

- https://github.com/TEAMMATES/teammates/blob/339cc1f2dab90a7b645f4a02045ef8a1dc3dc233/src/test/testng-local.xml#L13-L17

- https://github.com/TEAMMATES/teammates/blob/3ad37ca65e299f0cc7b3499c2d50ff2d81499564/src/main/java/teammates/common/util/Const.java#L1147

will remove the _MashupPageUiTest_.

**Comment by AlexM9200** [comment]
Can I try this?

**Comment by LiHaoTan** [comment]
@AlexM9200 sure you can but there are still quite a few more things to remove/modify other than what @amarlearning mentioned. If you can figure them out go ahead otherwise maybe you should do a `d.FirstTimers` first instead.

**Comment by AlexM9200** [comment]
OK thanks i'll have a look. If I don't make a pull request within a few hours someone else can have it.

**Comment by wkurniawan07** [comment]
I can tell which files need to be removed, but before that, let's get some things straight first:

> The mashup page is badly broken

I just checked, it is indeed broken but has a simple two-liner fix.

> The test is not used for its intended purpose anyway

I never asked this before: what is the intended purpose to begin with?
- If it is to make sure that "all pages can load", then it has never served the purpose since the beginning; a page being failed to load will not cause this to fail.
- If it is to manually eyeball the page (as suggested by the introduction), then this is not a "test" per se, but more like some kind of script to be run from time to time. It may be worth to be moved to scripts instead.

**Comment by wkurniawan07** [comment]
> Previously, it used to be the last test to run and leaves the page loaded at the end of the test suite for me to inspect before I set the new version live. That no longer happens

This is because the said test is excluded from CI tests or staging tests (before it was removed). Possible solutions here:
- Use "All tests" configuration
- Include in "CI tests", however the reason for the exclusion needs to be examined (I do not think this was my decision).

> If the maintenance cost is worth the effort, I don't mind keeping it. e.g. everytime we add a new page, we should add it to the mashup as well.

I will defer this decision to the new team, but judging from the number of new pages added in recent 2-3 years (less than 5?), it should not be a big issue.

I will, however, reiterate my stand that at its current state, this cannot be called a "test".

**Comment by whipermr5** [comment]
> The mashup page is badly broken

How is the page supposed to look like? I've only ever known it in its current state. I'm guessing all the elements should be styled exactly as they appear in the actual pages?

**Comment by wkurniawan07** [comment]
@whipermr5 change the following two lines:

https://github.com/TEAMMATES/teammates/blob/3d248661dd3daa4d4fb1843f795b43bc708efed5/src/main/webapp/test/mashup.jsp#L18-L19

to:

```diff
-     <link type="text/css" href="<%= FrontEndLibrary.BOOTSTRAP_CSS %>">
-     <link type="text/css" href="<%= FrontEndLibrary.BOOTSTRAP_THEME_CSS %>">
+     <link type="text/css" href="<%= FrontEndLibrary.BOOTSTRAP_CSS %>" rel="stylesheet">
+     <link type="text/css" href="<%= FrontEndLibrary.BOOTSTRAP_THEME_CSS %>" rel="stylesheet">
```

That concludes what I said as "simple two-liner fix".

**Comment by damithc** [comment]
> How is the page supposed to look like? I've only ever known it in its current state. I'm guessing all the elements should be styled exactly as they appear in the actual pages?

Yes.

**Comment by orinn248** [comment]
Hey, has a decision been made on the appropriate approach or is this up to whoever submits the changes?

**Comment by whipermr5** [comment]
Let's fix it and move it into client scripts.

**Comment by LiHaoTan** [comment]
I'm just wondering if it has much use though? Sounds like it's more like a maintenance burden with little benefits.

**Comment by sukanta-27** [comment]
@damithc @wkurniawan07 @whipermr5 @LiHaoTan Has any decision been made regarding this issue?

**Comment by wkurniawan07** [comment]
> I'm just wondering if it has much use though

@LiHaoTan you can say the same for more than half of the current client scripts 😛

**Comment by damithc** [comment]
Putting on hold for now
