### ISSUE TITLE
InstructorFeedbackEditPage: correct variable name

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7941]
In `fillRubricDescriptionBox()` method of `InstructorFeedbackEditPage.java`, we find the rubric description box by ID and fill it. But the variable has been named as `subQnBox`, which is confusing. Change the variable name. `descBox` might be a good name.

**Scope of issue**

Change these lines -

``` java
WebElement subQnBox = browser.driver.findElement(By.id(elemId));
fillTextBox(subQnBox, description);
```

to

``` java
WebElement descBox = browser.driver.findElement(By.id(elemId));
fillTextBox(descBox, description);
```

**Comment by varshav21** [comment]
can i take up this issue? I am new to open source and this is my first contribution.

**Comment by HirdayGupta** [comment]
Sure @varshav21! In fact, doing one issue labelled `d.FirstTimers` is part of our new contributor orientation here at TEAMMATES. You can check out our [Contributor Orientation Guide](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md). It is recommended that you follow the tasks outlined in the [Orientation Task List](https://github.com/TEAMMATES/teammates/blob/master/docs/orientation-guide.md#orientation-task-list) in order to correctly set up your development environment and introduce yourself to the community. Then, working on this (or any other) `d.FirstTimers` issue will help you get oriented with our workflow. 

Welcome to TEAMMATES!

**Comment by VamsiSangam** [comment]
This issue already has an active PR. @varshav21 you take other `d.FirstTimers` issues which haven't been claimed by anyone else. Also pleas ego through the links @HirdayGupta suggested :smile:

**Comment by HirdayGupta** [comment]
Whoops. My apologies @varshav21, missed the fact that PR #7944 was a Pull Request that solved this issue and wasn't just referencing it as it didn't follow our naming conventions. Do look for another `d.FirstTimers` issue to solve. :)
