### ISSUE TITLE
Login into an instance of Teammates

### ISSUE THREAD

**Issue by eei34** [TEAMMATES/teammates#8021]
I am unable to login into an instance. I have followed [these](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#logging-in-to-a-teammates-instance) directions. After inspecting the html page, the information that I am inputting is not gathered and the instructor is not being added (which supposedly gives me access to a join request that was not really sent). There are also missing files for this request. Although the adminHome.js file is being referenced in the document, it does not exist.

**Comment by LiHaoTan** [comment]
Did you miss [Building Javascript files](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#building-javascript-files)?. That's in the same document.

I would like to know why you missed that so we can possibly improve our documentation.

Though admittedly, the workflow for building Javascript files is not very ideal and we should get around to improving it.

**Comment by eei34** [comment]
I guess I overlooked it. Was planning on referencing the rest of this document once I got into the app. My suggestion: put this part of the documentation along with the ["setting up"](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) documentation so that this considered a required step to complete your set up. Thanks.

**Comment by wkurniawan07** [comment]
> put this part of the documentation along with the "setting up" documentation so that this considered a required step to complete your set up

I have to disagree with this, because building JS files is part of the "build/test/deploy" routine instead of setting up. Your JS environment is ready the moment you ran [`npm install`](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md#step-3-set-up-project-specific-settings-and-dependencies).

However, I do agree with @LiHaoTan that both (1) the documentation is lacking the information that JS files need to be built before the "build/test/deploy" routine and if there are updates to JS files upstream, and (2) the workflow for building JS files is not very ideal now.
