### ISSUE TITLE
Instructor: prevent enrolling multiple persons with the same name

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8041]
The enrolment process should check and prevent multiple persons with the same name from being enrolled. More details here: https://github.com/TEAMMATES/teammates/pull/8036#issuecomment-330864397

Possible idea for discussion: instead of preventing enrolment, detect duplicates and provide a UI for the instructor to correct the affected names on the spot by decorating them with extra info. https://github.com/TEAMMATES/teammates/pull/8036#issuecomment-330878250

**Comment by eei34** [comment]
I think the email address is the best method to differentiate students. This should be included in the feedback results. Instead of putting information such as (J1 / J2), you will need something concrete to differentiate them when entering grades or storing results. Unless the instructor was to identify the student in his normal records (outside of Teammates) as J1 or J2 he would still need the email address to determine who is J1 / J2 which would require increased effort (not only coming up with a unique name, but also associating that unique name with his normal records). Simply adding a column with the email address seems to be the best method to allow a teacher to determine who the student is both digitally and per the downloaded copy.

**Comment by damithc** [comment]
Display space is a very precious resource in session result pages. I don't think we can justify adding a whole new column to cater for a situation that applies to 0.1% of cases and might not even help in those cases. Reason: many schools use cryptic email addresses such as u392832328@example.edu which doesn't really help the reader to identify which student is which.

**Comment by LiHaoTan** [comment]
I agree that email address is sometimes the only way to differentiate persons in terms of mapping data between TEAMMATES and other systems. But as we can see, exported results already include the email field for every person.

However, that is not the case every time because they can be very long and may not necessarily identify users in a way easy for the reader like what @damithc mentioned.

If we look into an example on how instructors identify two students with the same name, then we see  that they would **always definitely** find a way to differentiate two students, so it is at the instructor's convenience to encode that information into TEAMMATES so they have a single unified way of identifying students unless it is non-verbal.

It is true though that an instructor may identify students by email if they have a preference for identifying students by cryptic emails or the emails are in forms such as `johndoe@example.edu` and `johnd@example.edu`, but they will probably only choose a portion of the email such as `johnd`. Then the rare occurrence an instructor simply want to differentiate two students by email will need to select perhaps a `Show Email`, but that would also involve proper UX placement so as not to unnecessarily bring that to the attention of users who are usually not interested in viewing the email. 

But if we extend the reason for having a way to show the email in results, such as when the `email` field can be helpful for other reasons such as checking a couple of students' email at a time **after accessing results**. Then the UX placement may become easier because it will now be useful for more people.

However, I don't think this is a common need, and can't think of a common need where `email` will be required commonly in results but I'm not an instructor so I might fail to see why. If there is indeed a use case then a separate issue can be created, but while it may help in this issue, it only resolves the problem partially for instructors using the `email` as the disambiguator.

Similar arguments should apply for questions including persons' names as well and I believe there are a lot more things to consider and it may get really complicated.

So what I think is we should not aim to try to perfect the duplicate name issues by also considering other related issues unless it is easy for one to consider the various interlinked systems. Also because the duplicate name issue is probably not very common I believe when improving it we should try as much not to worsen the experience of other parts of the system, which introducing the email field definitely does.

**Comment by wkurniawan07** [comment]
Closing as we do not wish to add this restriction.
