### ISSUE TITLE
Home page: remove country list

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8061]
Current:
![image](https://user-images.githubusercontent.com/1673303/31010745-7e227af4-a53e-11e7-9d38-94e02dc15f99.png)

Suggested:
>TEAMMATES community is growing fast, spanning over 1000 universities from across the globe.
>
>[Who is using TEAMMATES?]()

Reason: Our country list has grown a lot over the recent times and it is not viable to give a short representative list here.

**Comment by fdigne** [comment]
Hello,

Can I look after that ? 
Thank you for response.

**Comment by chowyb** [comment]
Hi @fdigne, feel free to go ahead! Please keep our [development workflow](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md) in mind while working on the issue, and I look forward to your contribution to TEAMMATES! 😄

**Comment by fdigne** [comment]
Hello, 

I've made the changes but I can't open the PR as it's mentioned in the process. Could you please help me to do so ?

**Comment by fdigne** [comment]
When I try to push on a new branch 8061-remove-country-list, I have this error message from eclipse : 

![capture d ecran 2017-09-29 a 16 59 36](https://user-images.githubusercontent.com/25439995/31023143-3d8d38ba-a53b-11e7-82a6-103ea70a15db.png)

Is this normal ?

**Comment by chowyb** [comment]
@fdigne It appears you are trying to push to the TEAMMATES repository directly. However, as only core members have push permissions to this repository, you will have to push the changes to your own fork instead.

Since your current repository `teammates` is not recognised as a fork of our repository by GitHub, you'll have to push to a new branch on your `teammates-1` repository, and then open a PR on this repository.

**Comment by fdigne** [comment]
Thank you for the information ... 
Normally it's ok now.
