### ISSUE TITLE
setting remote name

### ISSUE THREAD

**Issue by dipzzzz** [TEAMMATES/teammates#8072]
can someone please explain me how to set a remote name to main the main repo with example?

**Comment by wkurniawan07** [comment]
@dipzzzz, I kindly request you to learn some Git and GitHub basics first before contributing here, and to do your homework and proactively find the answers to your own questions in Google, StackOverflow, or even in the documentations of this project. All the questions you asked are far too commonly asked and the most straightforward of Google search will give you the answer. Figuring out things like this is a necessary skill for contributors to any project, otherwise you will need too much hand-holding and will not be able to make meaningful contributions.
