### ISSUE TITLE
AboutUs page: add back numbering

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8098]
v5.112
Numbering seems to have disappeared. 
Actual:
![image](https://user-images.githubusercontent.com/1673303/31572521-e3c66990-b0da-11e7-92a3-786461121b4a.png)
Expected:
![image](https://user-images.githubusercontent.com/1673303/31572527-fb56d8ba-b0da-11e7-8e28-63d7240ef473.png)

**Comment by wkurniawan07** [comment]
I'm pretty sure they have disappeared as far back as when the front pages adopts a responsive design, #6488.

**Comment by wkurniawan07** [comment]
Anyway, looks like this is good time to realize #6731. Otherwise anytime we want to change the design of this page, it has to be duplicated 200+ times.

Cue @whipermr5 @thenaesh.

**Comment by damithc** [comment]
> I'm pretty sure they have disappeared as far back as when the front pages adopts a responsive design,

I checked. It is fine even in the current live version v5.111. Broke in the v5.112 (yet to be deployed)

**Comment by ncbaihly** [comment]
I took a brief look at this as I was looking for a first time PR. @wkurniawan07 might have this handled but, the issue is the CSS child selector for the ordered table class. 

The current CSS is:

`.ordered-table {
    counter-reset: rownumber;
}

.ordered-table > tr:not(.skip) {
    counter-increment: rownumber;
}

.ordered-table > tr > td:first-child::before {
    content: counter(rownumber) '.';
    margin-right: .5em;
    min-width: 1em;
}`

The problem with > is that it means **only** immediate descendants which is why this is not working. 

Just having the tag after a class is also a descendant selector, but it can be any descendant further down in the tree, not strictly an immediate descendant.

Thus if we change it to the following it works as intended:

`.ordered-table {
    counter-reset: rownumber;
}

.ordered-table tr:not(.skip) {
    counter-increment: rownumber;
}

.ordered-table tr > td:first-child::before {
    content: counter(rownumber) '.';
    margin-right: .5em;
    min-width: 1em;
}`

**Comment by wkurniawan07** [comment]
@ncbaihly good job in troubleshooting! However, I'm currently preparing something that may invalidate this issue, so you may want to pick another `d.FirstTimers`-labelled issue to work on.

**Comment by shaharyar-shamshi** [comment]
Sir I want to give suggestion to solve this issue . If we store the user info (making separate class having the instances of user name and email id) and iterate through it using JSP code then number can be added easily without so much change and also making About us page source code compact

**Comment by shaharyar-shamshi** [comment]
@wkurniawan07 sir can I work on this if u allow me

**Comment by wkurniawan07** [comment]
Hi @shaharyar-shamshi, thanks for your suggestion. Unfortunately, I have already done enough works to solve the issue at hand. You may wish to find other issues (particularly those labelled `d.Contributors`) to work on.
