### ISSUE TITLE
New Contributor Self Intro Yungang Feng

### ISSUE THREAD

**Issue by ZiChuanBuXiu** [TEAMMATES/teammates#8155]
a) link to my app 
[http://teammates-zichuanbuxiu.appspot.com/](url)

b) link to my fork
[https://github.com/ZiChuanBuXiu/teammates](url)

c) a screenshot of the change I did
![image](https://user-images.githubusercontent.com/33737119/32929175-48e6260a-cbaa-11e7-87b1-3bf4a3e62d0a.png)

d) my real name and a short self-intro
My name is Yungang Feng. I am a graduate of Master of Information Technology in Melbourne, Australia. I'm happy that I can be part of this project and I hope I can make contributions to it.  I prefer the role of back-end developer since I am confident with Java.

**Comment by chowyb** [comment]
Hi @ZiChuanBuXiu,

Welcome to TEAMMATES! While we currently do not have any `d.FirstTimers` issues with no open PRs dealing with pure Java, note that `d.FirstTimers` issues are generally simple changes by default, intended to help you focus on the workflow rather than the changes themselves; you may wish to try out one of them, then move on to `d.Contributors` issues dealing with the backend.

**Comment by ZiChuanBuXiu** [comment]
@chowyb Thank you for the instruction! One thing I wanna figure out is, whether I can solve the open `d.FirstTimers` issues that there are some PRs related to it, e.g. [https://github.com/TEAMMATES/teammates/pull/8141](url), since there is someone who is already working on it.

**Comment by chowyb** [comment]
@ZiChuanBuXiu as issue #8138 already has an active PR open, it might be best not to work on that issue. However, you could try another issue such as #8112 instead, as the currently open PR is inactive (which I will be closing momentarily).

In general though, it is indeed preferable to avoid issues which have existing open PRs.
