### ISSUE TITLE
Help Request: cannot create instructor via admin page

### ISSUE THREAD

**Issue by ZiChuanBuXiu** [TEAMMATES/teammates#8166]
- **Operating System: macOS 10.13.1 (17B48)**
- **JDK Version: 1.8.091**
- **IntelliJ Version: 2017.2.7**
- **Chrome Version: 62.0.3202.94(64bit)**

**After I set up the project and run it on the local dev server, I tried to create a new instructor via [http://localhost:8080/admin/adminHomePage](url). When I filled the table and click the "Add Instructor" button, there was no response. The console of my browser shows:**
![image](https://user-images.githubusercontent.com/33737119/32990746-e47adeb0-cd82-11e7-8a65-4d216bda58b3.png)

**So I think it was the path problem. I changed the path of the `adminHome.js` in adminHome.jsp to point it to `src/main/webapp/js/adminHome.js`, but the console shows:**
![image](https://user-images.githubusercontent.com/33737119/32990784-7fcebdfa-cd83-11e7-825e-9df2e95add86.png)

**I also changed the path of the `adminHome.js` in adminHome.jsp to point it to `src/main/webapp/dev/js/main/adminHome.js`, but there was still no response and the console shows:**
![image](https://user-images.githubusercontent.com/33737119/32990814-23baf78a-cd84-11e7-9b31-093836deafa4.png)

**I looked up the related issues, and tried to solve it with `npm run build`, but it doesn't work.**

**Comment by ZiChuanBuXiu** [comment]
Well, I clean the cache of the browser, then it works well.

**Comment by whipermr5** [comment]
Did you do `npm run build`?

**Comment by ZiChuanBuXiu** [comment]
Yes, I did run that command. I solved it by clearing the cache of the browser, and then running `npm install` and `npm run build`.

**Comment by Vivek1012** [comment]
Hi,

I'm facing the same problem, i tried with clearing the cache of my browser and re running the "npm install" and "npm run build", infact i tried this with different browsers as well. I tried to Debug the click event of "addInstructorBtn" button. but debugger don't hit on that method too. I don't know what's wrong with this case, Because my console is clean and there is no error regrading that. I can't seen any method hit on 'network' tab as well.

I'm running this on Windows 8.1
Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Eclipse Version: Oxygen.1a Release (4.7.1a)
Java Version: 1.8.0_20

Could you guys please help me to figure out the problem.

**Comment by whipermr5** [comment]
@Vivek1012 Did you restart the dev server after doing `npm run build`?

**Comment by Vivek1012** [comment]
Yes, i did restarted the dev server. 
I also have changed the path for 'adminHome.js' in adminHome.jsp and adminHomePage.html.

but no luck with this as well :(

**Comment by whipermr5** [comment]
You shouldn't have to change the path. It should point to the generated, minified version of `adminHome.js`.
