### ISSUE TITLE
New Contributor Self-Intro: Jessica Leary

### ISSUE THREAD

**Issue by jessleary96** [TEAMMATES/teammates#8181]
Link to my fork: https://github.com/jessleary96/teammates

Hello! My name is Jessica Leary and I am a student at Siena College. I am looking to better understand the process of contributing to an open source project. I am seeking primarily to manually test the application or serve as a copy editor and have set up an Instructor Account as outlined in the Orientation Guide. I have not made any UI changes to date as I aim to serve as a manual tester or copy editor. Thank you!

**Comment by LiHaoTan** [comment]
Hi Jessica, welcome to TEAMMATES!

I see you have already contributed a few suggestions and submitted a PR. I guess you would have noticed that we usually encourage contributors to first work on `d.FirstTimers`, and follow up with `d.Contributors`.

For a copy editor or tester though, the process is currently not quite the same, and it is not quite well-established.

For a tester, some possible things you can do are testing the application and reporting bugs according to our guidelines. You can also add additional details to our current issues if you like.

For a copy editor though, the situation is a little more complicated. Are you planning to contribute to technical documentation or other kinds of documentation such as user guides and community processes and guidelines?

You might have also noticed that feature recommendations are a little harder to go through because of the relationship between implementation effort (technical limitations) and value of a feature. Furthermore, we have a backlog of features that we have already prioritized though of course contributors are not expected to contribute by priority because we need all the help we can get.

Therefore, it is also possible for new features to have higher priority or that the priorities of our backlog change. With that said, It might be easier for you to get features accepted if you gain more understanding of the project and/or have some technical background.

Unfortunately, the project goals and milestones are not well defined at a micro level, which is usually what influences the project macro priorities as well. Thus, I don't know if there is an easy way for you to follow the project, but if you are interested you can take some to monitor how the project is going forward, and of course, read the project documentation for a macro view.

In any case, we are open to suggestions and you can always suggest a workflow for copy editors/testers or maybe even submit a PR for improving our documentation on how copy editors and testers can start contributing :).
