### ISSUE TITLE
ide-usage.md: Eclipse setup: update text encoding instruction

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8219]
As discovered by @sukanta-27 in https://github.com/TEAMMATES/teammates/issues/8196#issuecomment-350508266, setting the project-specific text encoding is insufficient. Update the instructions in `ide-usage.md` to indicate that the workspace-wide preference should be set instead.

**Comment by wkurniawan07** [comment]
The root cause is not the workspace-wide preference per se. It is the run configurations (this includes all individual tests) which by default uses the workspace-wide preference regardless of the encoding set up at the project level.
Strictly speaking we should refrain from tampering with the workspace-wide preference, but the trade-off this time (need to configure on every single run configs) seem to justify it. @whipermr5 what do you think?

**Comment by whipermr5** [comment]
I feel it's reasonable to ask the user to change their workspace-wide preference to UTF-8, since that encoding is quite universally accepted?

**Comment by wkurniawan07** [comment]
@whipermr5 I guess it does.
