### ISSUE TITLE
Help with Setting up Project - Testing

### ISSUE THREAD

**Issue by tshradheya** [TEAMMATES/teammates#8230]
- **Operating System: Windows 10**
- **JDK Version: 1.8**
- **Firefox / Chrome Version (where applicable): Firefox 46.0**

**What I was trying to do / What I need help with**

I was setting up the project when in phase B of setting up:
While running the `localTests` on my staging server, the tests will not proceed any further and fail after few seconds it has stopped at this webpage. 

![image](https://user-images.githubusercontent.com/12574756/34253403-6b4defc0-e658-11e7-85d0-64cd0a69b812.png)

How do I change this? 
Also, I wanted to know what changes do I need to make so that I can run tests on my local dev server?

Thanks

**Comment by damithc** [comment]
> I wanted to know what changes do I need to make so that I can run tests on my local dev server?

The `test.properties` file specifies which app to test against. If you set it to `localhost:8888`, tests will run against your dev server.

To run against staging server, you need to create actual Google accounts and add those credentials to teh `test.properties` file. You get stuck in the authentication page because you are using the dummy credentials that came with the `test.properties` file.

**Comment by chowyb** [comment]
As an added note to @damithc's comment above, note that `localhost:8888` is from an older version of TEAMMATES; this was changed to `localhost:8080` in #8071.

**Comment by tshradheya** [comment]
Got it. 

Since the Google account of admin needs to have admin right, how do we go about creating such an account?

**Comment by wkurniawan07** [comment]
@tshradheya the Google account you used to register in GCP is automatically granted admin rights.
