### ISSUE TITLE
appengine-web.xml not found

### ISSUE THREAD

**Issue by dynastykaiserlord123** [TEAMMATES/teammates#8378]
When I tried running teammates in google appengine in eclipse, I get an error that the server timed out due to an xml file appengine-web.xml not found. In my project directory folders, all I have is a file appengine-web.template.xml but not appengine-web.xml. What am I missing here?
![screenshot 19](https://user-images.githubusercontent.com/33665087/35585735-a1517e42-05ad-11e8-9371-7af01c1ce110.png)

**Comment by wkurniawan07** [comment]
@dynastykaiserlord123, I'd advise you to thoroughly follow our [setup guide](https://github.com/TEAMMATES/teammates/blob/master/docs/setting-up.md) and [IDE setup guide](https://github.com/TEAMMATES/teammates/blob/master/docs/ide-setup.md) instead of trial-and-errors.
One thing for sure, it looks like you're using Eclipse Scala IDE which may or may not pose problems later on. I'm already seeing "Project facet Dynamic Web Module version 3.1 is not supported" which is not a good news.
