### ISSUE TITLE
InstructorFeedbackSessionActions : Session.isClosed() returns wrong value for Private sessions with No specified End Time

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8406]
**Environment:**
`master` branch

While working on #8374 I changed the condition for `isAllowedToSubmit` in `InstructorFeedbackSessionActions.java` to disable `submit` button for Closed sessions, when I found out that in case of the `Private` sessions with no set `End Time` (Like the one given below), the value of the method `isClosed()` returns `true`, where if we compare the current time with `null` (which is what the `isClosed()` method does  when the end time is not specified) in a statement like
`return now.after(null)` or `return now.before(null)` , it should always returns false.<br>
![screenshot 342](https://user-images.githubusercontent.com/10681755/35854096-51b85c46-0b27-11e8-9ce8-6b45c701a2c3.png)

**Steps to reproduce:** To be sure of this (supposed) bug, I followed the following steps.
- Login as `Insturctor`
- Create a `Private` session without specifying a `Submission closing time`
- Insert these lines (To get the contradicting results) in the file `InstructorFeedbackSessionActions.java` within the `InstructorFeedbackSessionActions` constructor, **after creating one/multiple private sessions with no end time specified** 

```java
System.out.println("Name: " + session.getSessionName()+"\tEndTime:" + session.getEndTimeString()
        + "\tisClosed: " + session.isClosed());
double timeZone = session.getTimeZone();
Calendar now = TimeHelper.now(timeZone);
System.out.println(session.getSessionName()+": isAfterNull: " +now.after(null));
```
- After saving and building the project go back to the `Instructor Home page` and refresh it.
- Check out the console for the print statements and find the sessions you created as private and check the output. (Check the end time which should be `-`, which indicates that the end time is `null`)

**Expected behaviour:**
The value of `now.after(null)` in the second println statement and the value of `isClosed()` should match. As both of them are doing the same thing.

**Actual behaviour:** This is the output from my console, for the private sessions I created.

```
Name: Private	EndTime:-	isClosed: true
Private: isAfterNull: false
Name: Private yet to start	EndTime:-	isClosed: true
Private yet to start: isAfterNull: false
Name: Private with no EndTime	EndTime:-	isClosed: true
Private with no EndTime: isAfterNull: false

```
Additionally while I was working on #8374 I modified the condition for `isAllowedToSubmit` to this : 
` this.isAllowedToSubmit = (session.isVisible() || session.isPrivateSession()) && !session.isClosed() && shouldEnableSubmitLink;
`
which disabled the  `submit` button for all the private sessions without a specified end time, even if the session has already started ( current time is after `startTime`)
**[Screenshot]**
![screenshot 341](https://user-images.githubusercontent.com/10681755/35855945-7fef2aea-0b2c-11e8-886f-069749f397be.png)

**Comment by wkurniawan07** [comment]
@whipermr5 @darrenwee @tran-tien-dat this is the one I told you guys about [this method](https://github.com/TEAMMATES/teammates/blob/master/src/main/java/teammates/common/util/TimeHelper.java#L318-L325) being shady. Can one of you investigate and fix? I'd like to believe this is a legit bug, but don't really have the time to address this myself.

**Comment by sukanta-27** [comment]
@wkurniawan07 @whipermr5 @darrenwee @tran-tien-dat 
If after investigation, it is found that, this is a legit bug, then I wanted to add something to speed up the process (Even if a little bit). 
As @wkurniawan07 pointed out that maybe the method `dateToCalendar` is causing the error, I wrote a code snippet to figure out if that is the case, which is provided below. (Though this is not the most beautifully written piece of code you will read today)

```java
package com.tutorialspoint;

import java.util.*;

public class CalendarDemo {
   public static void main(String[] args) {
      
      Date date = null;
      Calendar test = dateToCalendar(date);
      // create calendar objects.
      Calendar cal = Calendar.getInstance();
      
      System.out.println("Is cal after null: " + cal.after(null));
      System.out.println("Is cal after test: " + cal.after(test));
      System.out.println("Is cal before null: " + cal.before(null));
      System.out.println("Is cal before test: " + cal.before(test));
      
   }
   
       public static Calendar dateToCalendar(Date date) {
        Calendar c = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
        if (date == null) {
            return c;
        }
        c.setTime(date);
        return c;
    }

}
```

The above code provides the output : 

```
Is cal after null: false
Is cal after test: true
Is cal before null: false
Is cal before test: false
```

This is followed by a query from my side : Why don't we instead of returning a Calendar instance, return null as a value, when the date is null.

**And if it has a easy fix (therefore not a maintainer level issue), then can I work on it?**

**Comment by tran-tien-dat** [comment]
Thank you @sukanta-27 for reporting this bug. I notice that you insert `println` into the code a lot in order to debug. If you are using an IDE such as IntelliJ, you can use the Debug feature to stop execution at specified points and inspect the value of the variables.

Back to the issue, this is similar to  #8386, a bug caused by confusion when using the old Java time classes.

https://github.com/TEAMMATES/teammates/blob/3de04308ea175a7e19254a86d80e5cd8f388d39a/src/main/java/teammates/common/datatransfer/attributes/FeedbackSessionAttributes.java#L288-L294

Here, `now` is "converted to user timezone" by `TimeHelper.now` 

https://github.com/TEAMMATES/teammates/blob/3de04308ea175a7e19254a86d80e5cd8f388d39a/src/main/java/teammates/common/util/TimeHelper.java#L109-L112

However, what `TimeHelper.now` actually does is getting the current instant in time (timezone already considered) and then add the timezone offset again. Thus it results in the wrong time for `now` being way ahead of `end`, which is the correct current instant in time.

The bug occurs because for `TimeHelper#now`, the `Calendar` object is interpreted as having no timezone (and thus timezone offset is applied), while for `end` the `Calendar` object has a timezone (`SystemParams.TIME_ZONE` which is UTC). This kind of confusion should be eliminated once we have migrated to Java 8's `java.time`.

Fixing this bug alone involves checking all usages of `Calendar` and standardizing whether to interpret them as an instant in time or just a time without any timezone. This would be done when we migrate to Java 8's `java.time` anyway, so I think we don't have to fix this bug in particular but rather speed up our migration to Java 8's `java.time` (unless the bug causes bugs in other places which need to be fixed urgently)

Regarding #8374, I think you can detect whether the session is private or not instead of relying on `isClosed`?

**Comment by tran-tien-dat** [comment]
After thinking about it again, I think this bug should be fixed independently of migrating to Java 8's time.

The bug only occurs for `endTime=null` because a valid `endTime` is in user time zone, so modifying `now` by adding user time zone offset will correctly compare it to `endTime`. However, when `endTime` is `null`, `end` is assigned current time without user time zone offset, thus resulting in the bug.

Thus, the bug is localized to the particular function `TimeHelper#dateToCalendar`, the part where `date == null`. We should just move this logic to `FeedbackSessionAttributes`, as suggested by @whipermr5 .

@sukanta-27 are you up for this?

**Comment by sukanta-27** [comment]
@tran-tien-dat If given a choice, I would be happy to try my hands on this.

>Regarding #8374, I think you can detect whether the session is private or not instead of relying on isClosed?

Regrading this, I did check if a session is private or not and based on that, enabled the submit button for all the private sessions, as doing otherwise, like checking if for a private session, the endTime is null or not and based on that, enabling the submit buttons is complicating the statement (as there are other private sessions that do have a endTime and it would be better of a solution for consistency purposes to disable all the buttons past endTime, and not to mention the build failure that is repeatly occurring that I mentioned is a comment in #8374 ) If we fix this issue independently, then we can use a simple statement to achieve a optimal solution, like enabling the submit button for the sessions that are currently visible/Private and not past endTime, and disabling for every other case.

**P.S. :** Apologies for the poorly formatted comment, as I am not on my PC, and linking all the relevant comments and styling is hard to do from a phone.

**Comment by sukanta-27** [comment]
@tran-tien-dat 
>I notice that you insert println into the code a lot in order to debug. If you are using an IDE such as IntelliJ, you can use the Debug feature to stop execution at specified points and inspect the value of the variables.

Almost forgot to mention, thank you for this tip.  Will surely follow it from the next time. :smile:

**Comment by sukanta-27** [comment]
Closing because of #8447
