### ISSUE TITLE
InstructorFeedbackSessionsPageUiTest: fix malformed date in test case

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8417]
Change `2017-31-12` to `2017-12-31`.

https://github.com/TEAMMATES/teammates/blob/3de04308ea175a7e19254a86d80e5cd8f388d39a/src/test/java/teammates/test/cases/browsertests/InstructorFeedbackSessionsPageUiTest.java#L339

**Comment by tran-tien-dat** [comment]
Oh I bumped into this as well. Changing to `2017-12-31` will not pass all tests because the test's HTML expects this session to be open at the time of running. So needs to change to some future date. I've done this in my other PR #8428, specifically this commit https://github.com/TEAMMATES/teammates/pull/8428/commits/7e485165960da6a6d45aa8935d9b619459e15144

**Comment by whipermr5** [comment]
I was thinking of changing the expected HTML actually, though I guess both approaches work.

**Comment by damithc** [comment]
@whipermr5 can this be a first timer issue?

**Comment by whipermr5** [comment]
Might be too trivial. Also it's already fixed in the latest `java-time-migration` PR.

**Comment by tshradheya** [comment]
Closing this as its fixed in #8428
