### ISSUE TITLE
Explore migrating to JUnit 5

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8527]
At one point we decided to move from JUnit to TestNg due to the higher flexibility of test configuration allowed by TestNG. It may be good to revisit this decision to see if it is still valid and if not, to migrate back to JUnit.
Reasons: 
* JUnit is the more popular of the two
* JUnit is faster to keep pace with Java's evolution while TestNG doesn't even seem to be evolving any more.

**Comment by wkurniawan07** [comment]
@tshradheya any chance you want to look into this?

**Comment by tshradheya** [comment]
Looking into it 👍

**Comment by wkurniawan07** [comment]
The original issue can be divided into two independent parts:
- Using JUnit 5 as the test runner (`junit-jupiter-engine` + `junit-jupiter-api`, `useJUnitPlatform()` in Gradle, etc.)
- Using JUnit 5 as the assertion tools (`junit-jupiter-api` only)

I have finished the second part; PR incoming soon. This issue should then be limited to the first part.

**Comment by xpdavid** [comment]
Not sure what happen to Eclipse. For IntelliJ, the lovely ‘click to see difference’ is missing after #9155 is merged.

It seems that with TestNG as test runner, IntelliJ won't parse comparison failure message properly when JUnit 5 API is used.

Expected:
![image](https://user-images.githubusercontent.com/13977235/46343952-14a92180-c672-11e8-9dd8-d24407e7dc06.png)

Actual:
![image](https://user-images.githubusercontent.com/13977235/46344007-45895680-c672-11e8-8a04-50fca8dd837d.png)

**Comment by wkurniawan07** [comment]
I take responsibility for this. Same occurrence in Eclipse. Reason being the special treatment only applies to `java.lang.AssertionError` and not `org.opentest4j.AssertionFailedError`. Re-throwing the Exception as `AssertionError` does not help.

@xpdavid we have two options:
- Use old JUnit assertion API only for `assertEquals` (I don't think there is any benefit for all other `assert*` methods?)
- Migrate to JUnit 5 in entirety

Second option will obviously take longer but will be more beneficial in the long run. If we go down that path, do you think this will cause enough inconvenience until that is resolved?

**Comment by xpdavid** [comment]
The text comparison feature is useful when compare expected HTML and actual HTML (and also expected CSV with actual CSV). Considering that currently the front-end feature development is kind of on-hold because of V7 migration (while we still have some small changes in UI), the impact will not be that big. Nevertheless, it is still troublesome to compare the text manually.

Seems like we have another options actually (can be a small mitigation until JUnit 5 is adopted): testng > 6.9.5 (we are in 6.9.4) actually support `expectThrows` https://jitpack.io/com/github/cbeust/testng/master/javadoc/. 

I kind of in favor to migration to JUnit 5 entirely. Just taken a glance of the API supported by JUnit 5. It seems like all the feature we used in TestNG is also supported in JUnit 5.

**Comment by wkurniawan07** [comment]
Indeed, upgrading to just TestNG 6.9.6 can benefit us that way. So now we have these as options:

- Change only `assertEquals` to TestNG's implementation
- Change all to TestNG 6.9.6's implementation but need to borrow JUnit for some not provided functions (e.g. `assertNotEquals`)

None are particularly beneficial over the other. @xpdavid any thoughts?

**Comment by xpdavid** [comment]
I would expect we will move to JUnit in the future when JUnit is ready. Therefore, we can just change only `assertEquals` to TestNG's implementation.
