### ISSUE TITLE
Instructor: add new session: rename session template options

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8563]
Current:
![image](https://user-images.githubusercontent.com/1673303/36839030-c66e13a8-1d7b-11e8-8d20-1616ce6f5366.png)

Suggested:
* `Session with my own questions` → `session with my own questions`. Reason: As this form is a way for the user to tell TEAMMATES what to do, `my` is more appropriate than `your`
* `Team peer evaluation session` → `session using template: team peer evaluation`

**Comment by damithc** [comment]
@craaaa @joanneong what do you think?

**Comment by sukanta-27** [comment]
Can I work on this? As I am currently working on 2 other session related issues (#8447, #8468) , I can take this one too.

**Comment by damithc** [comment]
> Can I work on this? As I am currently working on 2 other session related issues (#8447, #8468) , and as all of my current PRs are waiting for a review, I can take this one too.

May be leave it to a newer contributor? In the interest of building up your qualifications for GSoC, you can attempt increasingly harder issues instead of doing smaller issues.

**Comment by sukanta-27** [comment]
Okay sir.

**Comment by craaaa** [comment]
I like the change from `your` to `my`. About the `session using template`: are we thinking about adding other templates? The use of the colon makes it seem to me like the team peer evaluation template is one of several possible templates to be chosen from.

**Comment by sukanta-27** [comment]
@craaaa 
>are we thinking about adding other templates?

One of the features to consider in the `Questions+` project is about adding a new template with sample questions. So, if this project is to be selected than we will have more than one template to choose from.

**Comment by damithc** [comment]
> About the session using template: are we thinking about adding other templates? The use of the colon makes it seem to me like the team peer evaluation template is one of several possible templates to be chosen from.

Yes, we planned to have more templates, although never got around to actually doing it. :-p

**Comment by joanneong** [comment]
Personally I would actually prefer `session with your own questions` rather than `my`. This is because   I find it to be more consistent with other parts of TEAMMATES. For example:

From the `Courses` page:
![image](https://user-images.githubusercontent.com/24493463/36851097-69a77cea-1da3-11e8-81c2-0946c2814d05.png)

From the `Sessions` page:

![image](https://user-images.githubusercontent.com/24493463/36851135-7c422dc8-1da3-11e8-9459-b5533394c7fe.png)

From the `Search` page:

![image](https://user-images.githubusercontent.com/24493463/36851149-8abfa038-1da3-11e8-8f43-ffff1974c719.png)

The only place where the possessive determiner `my` or possessive pronoun `I` were used seems to be in the section titles of the instructor help page, and the rest of TEAMMATES defaults to `your` and `you` instead.

Meanwhile for `session using template: team peer evaluation` I think this change is better as it does also help to explain that selecting this option is equivalent to using a template. This is true even if there are no alternative templates available (yet).

P/S Not sure if this is intentional, but making the first letter of `session` lowercase for both labels in question looks good to me as well since they both continue the phrase `Create new`.

**Comment by damithc** [comment]
The normal guideline (see [here](https://ux.stackexchange.com/a/4350)):
* You: When the app is talking to the user (e.g., error messages)
* My/I: When the user is talking to the app (e.g., forms)

**Comment by tanhengyeow** [comment]
I'll attempt this issue :)

**Comment by sukanta-27** [comment]
@damithc @joanneong 

How about we modify the drop down menu to add a double drop down, something like this : 
```
Create New 
                             Session with my own questions
                             Session using template -> Team peer evaluation session
                                                       Another template
                                                       And another template
                                                       And So on
```
So that when we have multiple sessions we will not have to use the word `Session using template:` repeatedly for each type. And as @joanneong will be adding one soon in #8601, this may improve the UI?

**Comment by damithc** [comment]
> How about we modify the drop down menu to add a double drop down, something like this :

The default is going to be a second level option. Not sure if the current selection can be clearly shown in the UI. i.e., when a user looks at the UI, can the current selection be easily interpreted?

**Comment by sukanta-27** [comment]
>The default is going to be a second level option. Not sure if the current selection can be clearly shown in the UI.

This part slipped my mind.
