### ISSUE TITLE
Admin: recent activity log: show correct 'time stamp in instructor timezone' 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8594]
v6.3
Steps:
1. login as admin
2. search for a user
![image](https://user-images.githubusercontent.com/1673303/36967236-26370a30-209a-11e8-80b8-bb115a73209e.png)
3. click on `view recent actions`. This loads a list of activities and the time zones are shown in admin's time zone (could be hard coded to UTC+8 because the only real admin is in that time zone)
4. In the activity list, click on a time stamp.
![image](https://user-images.githubusercontent.com/1673303/36967165-f3d245d2-2099-11e8-967e-d2b4181d315d.png)

Expected: shows the time stamp (in yellow highlight) in the time zone of the user whose activity being listed
Actual: shows the time stamp in some other time zone, probably in UTC+0. In the screenshot above, both should be the same because it is showing my own activity (in UTC+8)

Also note that the date format is different between the two time stamps.

**Comment by tran-tien-dat** [comment]
This is related to #8386. We will fix it when migrating to java.time classes in `java-time-migration`.

**Comment by damithc** [comment]
> This is related to #8386. We will fix it when migrating to java.time classes in java-time-migration.

Roger that. putting on hold.

**Comment by tran-tien-dat** [comment]
Working on this issue now. Some notes for myself:

- The time sent to the server is Unix time, not time in Admin's timezone. Source: https://github.com/TEAMMATES/teammates/blob/6573c90b569858138d85059c62bf7f314f33487c/src/main/webapp/dev/js/main/adminActivityLog.js#L138 => Rename the parameter

- Local time zone look up is currently done by retrieving a session of the user. Since course now has a timezone field, local time zone can be determined after retrieving a course of the user. However, very old courses (before #5863) do not have a timezone field, so they will get the default UTC timezone. In case the admin need to look at the log of these courses, the log times maybe confusing. Hence, I will also display timezone in the time string of an activity log.

**Comment by tran-tien-dat** [comment]
@damithc I notice that the log time in Admin time zone is currently displayed with the the month before the date, while the time in user time zone is displayed with the date before the month. I think this can be confusing, so I would like to standardise 1 format for both. I think in Singapore we are used to seeing the date before the month, so do you mind if I change to that?

**Comment by damithc** [comment]
> I think in Singapore we are used to seeing the date before the month, so do you mind if I change to that?

Yes, let's do that.
