### ISSUE TITLE
Distribute points questions: fix total points to distribute being reset to non-default value

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8605]
**Environment**
`master` branch

**Steps to reproduce:**
- Login as Instuctor
- Create/Edit a session
- Add a `Distribute points` question. Does not matter Options/recipients
- Modify any of the `Total Points to distribute:` option, (The default is set as 100, delete it and click outside the box, or save the question)
- The value changes to 1

**Expected behaviour:** Don't know if it is expected or not, but IMO 1 point is not useful for any evaluation, specially when we are setting the value as 100 when adding a new question. 

**Actual behaviour:** Value changes to 1

**Suggested solutions:**
- Give a warning message when trying to save the changes before entering a value/ entering 0 (Like in MSQ question) : 
![screenshot 405](https://user-images.githubusercontent.com/10681755/37066186-0e161b5a-219c-11e8-8113-1e3f62d51a0d.png)

- Set the default value as 100, so even if a user leaves the field blank / enters 0, it can be replaced to 100 (for consistency?)

**Additionally:** We should disable one field when the other is selected.
![screenshot 406](https://user-images.githubusercontent.com/10681755/37066364-0c232422-219d-11e8-83b2-eda1a108f431.png)

@damithc Sir, your thoughts on this?

**Comment by joanneong** [comment]
I do agree that 1 is not very useful. In particular, if that happens, and an instructor further tries to force uneven distribution on the options/ recipients, a student may possibly never satisfy the submission criteria if there are multiple options/recipients:

![image](https://user-images.githubusercontent.com/24493463/37073740-c02e95d0-2203-11e8-9234-9a45bb2a10b2.png)

So I think it would be nice to change the default value to 100 instead.

As for whether to disable the field or not, there is no effect on the logic/backend even if the field is not disabled, but disabling it does make more sense to me as well since it is an "either-or" situation here.

So yeah, I second what @sukanta-27 proposed!

**Comment by sukanta-27** [comment]
Working on this.
