### ISSUE TITLE
HtmlHelper: Use better way to replace now timestamps with datetime.now

### ISSUE THREAD

**Issue by whipermr5** [TEAMMATES/teammates#8640]
`HtmlHelper` requires the time zone to correctly replace now timestamps with `datetime.now`.

The HTML time zone detection introduced in #7616 is unreliable as it depends on the pattern `UTC+xxxx` showing up in HTML for it to work. ~~However, pages like `StudentHomePage` do not contain the time zone in HTML at all, while others like `InstructorSearchPage` contain multiple time zones. This has resulted in peculiarities in `StudentHomePageUiTest` - see https://github.com/TEAMMATES/teammates/pull/8629#discussion_r174357658. Let's try to come up with a solution that works for all cases (perhaps include the time zone as a data attribute in HTML?).~~ It is now completely broken as the offset is no longer displayed in favour of the time zone short name since #84.

Instead of doing time zone detection, let's wrap all displays of timestamps in a tag with a data attribute containing the corresponding ISO8601 UTC formatted instant. `HtmlHelper` should then ignore the text contained inside the tag, and leave only the data attribute for comparison. We can then detect now timestamps easily as they would be in a standardised format, unaffected by time zone.

<hr>

Update: Work-around has been introduced in #8640. Need to find a more elegant way to do this instead.

**Comment by tran-tien-dat** [comment]
including the time zone as a data attribute in HTML will require more complicated RegEx to detect. The RegEx will  have to recover all kinds of HTML elements where the time data can be a children of.

https://github.com/TEAMMATES/teammates/blob/dbca7a2531c4cfccec4deac0d3569ac58298a7e8/src/test/java/teammates/test/driver/HtmlHelper.java#L414-L423

https://github.com/TEAMMATES/teammates/blob/dbca7a2531c4cfccec4deac0d3569ac58298a7e8/src/test/java/teammates/test/driver/HtmlHelper.java#L472-L475

The time zone detection is basically to figure out the correct string for the current time, and then replace it with a constant string like `datetime.now`. So how about we change the tests so that they pass a list of strings to be replaced by `datetime.now` etc. instead?

**Comment by whipermr5** [comment]
This is causing builds to fail between 12am - 8am SGT daily after #84 was merged 😅

**Comment by damithc** [comment]
Just mentioning in case relevant: There are online global courses where students come from different countries. In those cases, it is better to show times based on the base location of the course, to match with announcements of deadlines by instructors. Trying to show times based on each student's location may lead to confusions. This is the reason why we detect timezone at course/session creation and use it for all subsequent purposes.

**Comment by xpdavid** [comment]
Decrease priority now as frontend migration is underway 🎉  https://github.com/TEAMMATES/teammates/projects/4 . After completion, we will achieve what @tran-tien-dat has suggested and there is no need have full page HTML verification.

**Comment by wkurniawan07** [comment]
> there is no need have full page HTML verification.

I can't promise this. "Less HTML verification" is definitive, but "No HTML verification" is too strong a conclusion at this point of time.

**Comment by wkurniawan07** [comment]
`HtmlHelper` is decommissioned in V7.
