### ISSUE TITLE
Instructor: remind particular student: fix stray place holder in email text

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8664]
found in: v6.3.0, v6.4.0 (I didn't check earlier versions)

Steps:
* Add the instructor as a student
* Have a session that has questions for students as well as instructors
* Send a reminder using 'remind particular student' option in instructor home page

Actual: one of the emails sent has a placeholder text instead of actual content

![image](https://user-images.githubusercontent.com/1673303/37552658-a562a338-29f4-11e8-897d-cb2b6e06e544.png)

**Comment by damithc** [comment]
The problem is in the email sent to instructors asking them to submit responses.

**Comment by whipermr5** [comment]
Related to #8182?

**Comment by sukanta-27** [comment]
Looking into it.

**Comment by sukanta-27** [comment]
Found the reason of this bug.

https://github.com/TEAMMATES/teammates/blob/8a974ee703c46f4b3280552f46b3e767eb561eab/src/main/java/teammates/logic/api/EmailGenerator.java#L96-L102

`additionalContactInformation` was not passed to `generateFeedbackSessionEmailBasesForInstructorReminders` in the argument, which is why the placeholder was not getting replaced.

**[Screenshot of the email before passing the parameter]**
![screenshot 451](https://user-images.githubusercontent.com/10681755/37555014-ea297076-29d8-11e8-89c7-2a5435d605b0.png)


**[Screenshot of the email after passing the parameter]**
![screenshot 452](https://user-images.githubusercontent.com/10681755/37555018-fe8a5e90-29d8-11e8-8de5-a748fe7149b2.png)


Sending a PR within an hour.
