### ISSUE TITLE
Instructor: edit session: include only the form for the used question

### ISSUE THREAD

**Issue by Crphang** [TEAMMATES/teammates#8688]
Previously mentioned with issue: #5728

The current design of adding new questions and editing questions shows a form that contains all types of questions. This presents a problem when trying to use HTML Input Validation that uses `required`.

Consider this example:

Add 'required' to an input of any question such as  `feedbackQuestionRankOptionsEditFormTemplate.html`.

```
<input type="number" class="form-control" name="${Const.ParamsNames.FEEDBACK_QUESTION_RANK_MIN_OPTIONS_TO_BE_RANKED}"
         id="${Const.ParamsNames.FEEDBACK_QUESTION_RANK_MIN_OPTIONS_TO_BE_RANKED}-${questionNumber}" min="1" step="any" placeholder="e.g. 1" value="${minOptionsToBeRanked}" required>
```
Try to add a question that are of other types. And Google Chrome browser will raise this error:

![image](https://user-images.githubusercontent.com/4986717/37651120-119f06c0-2c72-11e8-91f3-e92517d3a3be.png)

This is because a hidden input (`display: None`) has a `required` field. This problem is discussed in [this stackoverflow post](https://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome). Currently the way we are handling adding `required` HTML input validation is to using Javascript and show Flash messages like below.:

![image](https://user-images.githubusercontent.com/4986717/37651384-e696f0a4-2c72-11e8-9cd9-fb732ed030ee.png)

However, it involves adding a handler for each input element.

In order to use HTML Form validation for `required`, method suggested in [this stackoverflow post](https://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome), is to add `required` attribute only when we are displaying that question or similarly hide `required` if we are not displaying that question.

Ultimately, it makes sense to allow each question to be displayed in it's own form and not have to worry about the logic of the other questions.

**Comment by sukanta-27** [comment]
**Context:** https://github.com/TEAMMATES/teammates/pull/8373#pullrequestreview-105758663

While working on #8611 I added the `required` attribute by using a similar method as @Crphang in #8373 and that is by adding a `data-linked-input-id` in the max/min checkbox containing the id of the corresponding number field. Then added a function in `questionMsq.js` to add the `required` attribute when checkbox is checked and removing it on unchecking.
`$(linkedInput).prop('required', isCheckboxEnabled);`

But in the following scenario we will still get the `Invalid form control` error.

- Add a question (e.g MSQ)
- Check the max/min field
- cancel the question 
- Add another question (Essay for example)
- Fill up the form and click `Save changes` (This happens because, even though the fields are hidden, because we canceled the question, the checkbox is still checked, making the field required)

To avoid the error in this scenario, In `InstructorFeedbackEdit.js` within the function `enableNewQuestion()` I checked if the max/min selectable choice field is hidden, then remove the `required` attribute. 

```javascript
   // Remove 'required' attribute if the MSQ max/min selectable choices field is hidden,
   // that is if the form is being used by any other question type. This is to avoid
   // "Invalid form control" in Google Chrome.
   if ($newQuestionTable.find(`#msqMaxSelectableChoices-${NEW_QUESTION}`).is(':hidden')) {
       $(`#msqMaxSelectableChoices-${NEW_QUESTION}`).prop('required', false);
   }
   if ($newQuestionTable.find(`#msqMinSelectableChoices-${NEW_QUESTION}`).is(':hidden')) {
       $(`#msqMinSelectableChoices-${NEW_QUESTION}`).prop('required', false);
   }
```

This workaround takes care of the issue. But the problem with this is that, whenever we want to make a field `required` we will have to add similar conditionals.

**Comment by sukanta-27** [comment]
I have also found another way to deal with this problem which is better than the one mentioned above in the sense that, it will take care of all the required fields that are hidden in the new question form. And it is to add a function in `InstructorFeedbackEdit.js` within `$(document).ready(() => ....` that will remove `required` attibute from all the hidden input elements upon clicking `Save changes` for new questions. 

The function I used is following:

```javascript
function removeRequiredIfElementHidden() {
    // If a input field is hidden, remove required attribute when saving changes 
    $('.form_question').on("click", "#button_submit_add", (e) => {
        $("input:hidden").prop('required', false);
    });
}
```
This solves the issue and is also better as we won't have to deal with every field separately. But Although I have tested this method, whether with this workaround we can add `required` in the html file itself without a issue or not is to be tested and discussed.

**Comment by Crphang** [comment]
@sukanta-27, that could work. In the context that we redesign the question form, then your method in adding 

```
function removeRequiredIfElementHidden() {
    // If a input field is hidden, remove required attribute when saving changes 
    $('.form_question').on("click", "#button_submit_add", (e) => {
        $("input:hidden").prop('required', false);
    });
}
```

is actually better than my previously suggested solution in #8373 about adding `{isRequired}`. This is because only this method needs to be removed when the change is made, instead of changing all the respective `HTML` files again. 

Also, it is easier for people to adopt when adding inputs with `required`, because this function should work for them too.

**Comment by Crphang** [comment]
@sukanta-27 my implementation in #8320:

```
/**
* If a input field is hidden, remove required attribute when saving changes. See issue #8688.
*
* TODO: Remove this function when #8688 is fixed.
*/
function removeRequiredIfElementHidden() {
   $('#form_editquestion--1').on('click', '#button_submit_add', () => {
       $('input:hidden').prop('required', false);
   });
}
```

I tried to limit it to newQuestion only, because existing questions have no other questionForms. And it's good to reduce scope to reduce unintended effect.

**Comment by LiHaoTan** [comment]
So there is still a limitation of the workaround, and there may be more we are unaware of since the workaround couples to so many different aspects of the system it makes it hard to reason about it standalone.

Steps to replicate the limitation:

1. Create a new essay question (or really any question other than Rank options/recipients question).
2. Click save question immediately, an error of question text cannot be empty will appear. The `required` attributes are now removed from the rank options/recipients questions.
3. No validation of `required` is done when adding a Rank options/recipients question.

**Comment by xpdavid** [comment]
Resolved in V7. Form data will be well-organised.
