### ISSUE TITLE
AdminPage: Unable to detect duplicate instructors with the same details added 

### ISSUE THREAD

**Issue by jacoblipech** [TEAMMATES/teammates#8691]
- **Environment**: latest version V6.4.0 

**Description of feature/enhancement**
When multiple instructors are added in the same field, there is no algorithm to check for duplicates being added. This will result multiple spam messages through email to the same user.

<img width="933" alt="screen shot 2018-03-21 at 9 16 14 am" src="https://user-images.githubusercontent.com/28522090/37691836-b7d711fe-2cef-11e8-81f1-e8087267ee7e.png">

**Justification**

The system will store additional data when there are multiple instructors of the same details being added. Multiple welcome messages will be sent to the email as well. Hence, it will be good if there is a check duplicate mechanism.

**Comment by damithc** [comment]
Good catch @jacoblipech. In practice this is a non issue because I'm the only one who use this feature and it is easy to detect duplicates manually because I do a manual check of each new user before creating an account. Probably not worth fixing :-) Will reopen if this becomes a problem in the future.
