### ISSUE TITLE
Instructor: Session Results: Able to tick the checkbox even though the text is strikedoff

### ISSUE THREAD

**Issue by jacoblipech** [TEAMMATES/teammates#8726]
In the session result page, the "Group by Teams" is striked off even though the checkbox can be ticked.

Environment: 
master branch
Steps to reproduce:

Login as Instructor
In the session table, click on Results to view the results of a session which has existing responses.
Click on Edit view
<img width="969" alt="edit view option wrong" src="https://user-images.githubusercontent.com/28522090/37985386-2e41ae9a-322b-11e8-9152-ac11fa49f381.png">

Actual behaviour: I guess if it is striked off, it should not be ticked? Or it should not be striked off.

**Comment by joanneong** [comment]
>Or it should not be striked off

The reason why you are observing this is because the current view selected is "Group by - Question". Thus the option "Group by Teams" has no effect regardless whether if it is ticked or not. If you change it to any of the other "Group by"s, and then click on "Change View", and "Edit View" again, you'll see that the first option is no longer struck out.

That said, I do agree that seeing this can be confusing for instructors...Rather than striking the option out, perhaps it is better to just disable the option directly when the corresponding view is selected. Same goes for "Show Statistics" when the next two "Group by" options are chosen.

**Comment by gthd** [comment]
I would like to work on this. If this is ok

**Comment by amarlearning** [comment]
@gthd If you are not working then I would like to take this one.

**Comment by gthd** [comment]
Hi @amarlearning its yours.

**Comment by amarlearning** [comment]
Taking this one

**Comment by jacoblipech** [comment]
@joanneong I realised that if I disable the checkbox, when I change to another "Group by" option other than "Group by Question", I am unable to check the box which is disabled. If I want to check the box, I will have to load the edit modal again. This is shown in the gif below.
![disable checkbox gif](https://user-images.githubusercontent.com/28522090/40767362-e7c6a5be-64e4-11e8-810d-c847c3aa5750.gif)

Hence, it may actually be a chore to disable the checkbox. We can either leave it as it is or we add javascript to the modal created such that when different "Group by" options are populated, the checkbox will update automatically. 

What is your take? :)

**Comment by jacoblipech** [comment]
@joanneong a reminder on your comments on this? Thank You!

**Comment by wkurniawan07** [comment]
No longer valid
