### ISSUE TITLE
Instructor: edit session: visible date: reject incorrect dates

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8791]
v6.5.1

Steps:
1. Login as instructor
2. Edit visible date of an existing session by modifying the text box (not the date picker)
3. Enter an incorrect date where the day doesn't match the date e.g., Take a valid date and change the date but not the day -- Apr 19th is not a Tuesday
![image](https://user-images.githubusercontent.com/1673303/38842610-9090c4f8-421d-11e8-8f62-9e081d1e17e3.png)

4. Save

Expected: The date is rejected or auto-corrected upon save
Actual: The incorrect date is saved

**Comment by shaharyar-shamshi** [comment]
Sit I am working on this by adopting the appraoch of autocorrection

**Comment by whipermr5** [comment]
If the page is reloaded, a valid date should show up. The field is just not getting updated upon submit because it happens over AJAX. @shaharyar-shamshi a good way to solve this would be to ride on the existing resolved time fields in the JSON response, introduced in #8687. The frontend code for updating the fields dynamically upon submit is already written (originally meant for ambiguous date times).

**Comment by shaharyar-shamshi** [comment]
@whipermr5 sir actually I am introduction a the method in Timehelper to match the day and date if they are wrong then I am changing the day to match it with the date

**Comment by tanhengyeow** [comment]
I investigated on this issue and the problem lies with invalid datetime (from user input) being parsed to `null` upon conversion to `LocalDateTime` format at the backend.

As mentioned by @whipermr5 , the update to the frontend happens over AJAX thus a page refresh would not persist the invalid datetime and would show the date back to the original datetime before modification.

I was thinking of reflecting the original datetime back in the field upon submit and making the status message more verbose to include **"...... Invalid datetime fields are reset to the original datetime field."**

@damithc Your thoughts on this?

**Comment by damithc** [comment]
> I was thinking of reflecting the original datetime back in the field upon submit and making the status message more verbose to include "...... Invalid datetime fields are reset to the original datetime field."

Sounds good @tanhengyeow It's good if we can also indicate which exact field was reverted

**Comment by damithc** [comment]
I think using a green status message for the invalid case is not suitable. Either make the whole thing orange or show two messages, one orange, one green?
Is it possible to show what was the invalid date entered, for the user's reference? It's ok if that takes too much work.

**Comment by tanhengyeow** [comment]
@damithc Yup, doable. Here's the new behavior:

![error 2](https://user-images.githubusercontent.com/25320782/42500032-cfe81048-8462-11e8-8930-bd6c90ab8030.gif)

![image](https://user-images.githubusercontent.com/25320782/42500021-cbc3c39a-8462-11e8-82c9-299628b9b18b.png)

**Comment by wkurniawan07** [comment]
Resolved in V7.
