### ISSUE TITLE
codeQuality:fix nested for-loops

### ISSUE THREAD

**Issue by douihechmaha** [TEAMMATES/teammates#8796]
# Code Enhancement
I think that we need to transform the nested for-loops  with  forEach since we use java8.
i have noticed there are too many so we should fix them .

**Comment by joanneong** [comment]
Hello @douihechmaha , thanks for the suggestion :) 

However, it would be good if you can point out some examples of where this occurs so that we can look into whether these for-loops are worth replacing. Are you referring to any scenario in particular? For example, #8216 dealt with using `forEach` to replace iterating through map entries.

P/S You might want to read and follow the issue template that shows up whenever you try to open a new issue :)

**Comment by wkurniawan07** [comment]
@douihechmaha if you're talking about converting `for (String str : strings) { ... }` to `strings.forEach(str -> ...)`, I'd advise against it because it has no obvious benefit.

**Comment by wkurniawan07** [comment]
@douihechmaha Closing due to lack of information. Feel free to reopen/request for reopen when more information can be provided.
