### ISSUE TITLE
Rubric questions: Add front-end validation for choices

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8828]
**Environment**: 
`master` branch

**Steps to reproduce:**
- Login as Instructor
- Edit an existing session or create a new one
- Add a new Rubric question
- click on `add column`
- Do not enter the choice and descriptions 
- click `save`

**Expected behaviour:** Like `Subquestion` has front-end validation, the `choices` should have front-end validataion too, and an instructor should not be allowed to enter an empty choice column, as an empty choice does not make sense.

**Actual behaviour:** The instructor is allowed to add a empty choice column.
![screenshot 492](https://user-images.githubusercontent.com/10681755/40018906-520061fc-57db-11e8-959b-f8b28ab40253.png)

**Comment by tanhengyeow** [comment]
Hi @sukanta-27 

Will you be working on this issue?

**Comment by sukanta-27** [comment]
@tanhengyeow Currently my final exams are going on. So, if you want you can take it. :+1:

**Comment by sukanta-27** [comment]
@tanhengyeow Have you started working on it yet?

**Comment by tanhengyeow** [comment]
@sukanta-27 Not at the moment, if you already found a fix you can submit a PR first 😄

**Comment by sukanta-27** [comment]
@damithc 

https://github.com/TEAMMATES/teammates/blob/4416b4db657cdf6993fd298d51cc7e3a7d630c66/src/main/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetails.java#L973-L981

This code was commented out in #2815 (specifically in https://github.com/TEAMMATES/teammates/commit/5d6aabb0e0f1366974cddcbe6689f2cb643f23a6), this is the main reason for this issue coming up. I am wondering what was the reason for allowing  Rubric choices to be empty? as I now see it was intentional.

**Comment by damithc** [comment]
> I am wondering what was the reason for allowing Rubric choices to be empty? as I now see it was intentional.

hmm... I suppose some cells can be left empty. For example, if the column heading has a value, it is fine for cells below it to be empty as the meaning of the cell is implied by the column heading.  e.g.,

&nbsp; | Bad | Good | Very Good
---|---- | ---- | ----
attitude | o | o | o

If the cell  contains an explanation, column header can be left empty. 

&nbsp; | &nbsp; | &nbsp; | &nbsp;
---|---- | ---- | ----
attitude |  o lousy |  o ok| o positive

But if both are left empty, then it is not possible to deduce the meaning of a cell. e.g.,

&nbsp; | &nbsp; | &nbsp; | &nbsp;
---|---- | ---- | ----
attitude |  o |  o | o 

We can consider this a case of 'not worth handling because if a user is silly enough to create this scenario, let s/he suffer the consequences'

**Comment by sukanta-27** [comment]
Closing this issue as this is not a bug.
