### ISSUE TITLE
Student: submit feedback: optimize layout of questions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8866]
This is how we show a question in the submission page:
![image](https://user-images.githubusercontent.com/1673303/40877642-dab3b60e-66b6-11e8-91d4-811af0687237.png)

Suggested: improve/redesign the layout/formatting to save space e.g., remove unnecessary line breaks, borders, lines, etc.

**Comment by darrenlmd** [comment]
Hi I would like to take on this issue.

For the **Question** part, I propose a simple solution of removing the new line and **bolding** the word question

For the details part, I have a few proposals. Would love to hear which one the team prefers.

### Sol 1: Remove spacing
![remove-space-1](https://user-images.githubusercontent.com/7418318/47661668-7a86bb80-dbd4-11e8-9654-dcd1ab716dd2.png)

This is the simplest solution to reduce some empty space, even though it doesn't change the display drastically.

### Sol 2: Column
![column-display-1](https://user-images.githubusercontent.com/7418318/47661345-d4d34c80-dbd3-11e8-9ae6-5aa5c68a34d7.png)

![column-display-2](https://user-images.githubusercontent.com/7418318/47661472-15cb6100-dbd4-11e8-9a7b-4a3f27ce2303.png)

This solution looks more pleasant (in my opinion) because we don't have a single line with two words in a text box. However, it doesn't solve the empty space problem entirely

### Sol 3: Collapse
![collapse-1](https://user-images.githubusercontent.com/7418318/47661807-b28dfe80-dbd4-11e8-9b9a-6add95b135a0.png)

![collapse-2](https://user-images.githubusercontent.com/7418318/47661808-b4f05880-dbd4-11e8-91dd-1b55cd66681f.png)

This solution doesn't reduce the space in the layout but it makes the details box collapsible. This can make the display more bearable if the details box is  really long. However, it's a bit of an overkill for short details box.

**Comment by damithc** [comment]
I'm ok with solution 1.
@wkurniawan07 is it OK to do this issue in the light of UI revamp that is going on in parallel?

**Comment by wkurniawan07** [comment]
OK to do this now; this page has not been touched yet.

P.S. hello @darrenlmd!

**Comment by darrenlmd** [comment]
Hi @wkurniawan07! 
I will proceed with solution 1 and make a PR soon. 
I want to check for this kind of small UI adjustment, what kind of test (if any) should I include?

**Comment by wkurniawan07** [comment]
If it is just pure UI adjustment with no user interaction affected, no new test is necessary. However, there will be a very small subset of tests affected; you can read up more about it [here](https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#god-mode) when you face it eventually.

**Comment by darrenlmd** [comment]
Made a [PR](https://github.com/TEAMMATES/teammates/pull/9222) following guidelines. Please take a look and let me know if I miss anything. Thanks!
