### ISSUE TITLE
Instructor: edit MCQ question: give an easier way to reorder options

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8879]
Current: to reorder options, user has to copy paste text of the options
![image](https://user-images.githubusercontent.com/1673303/41019938-76776c78-6993-11e8-82fa-fd3db3e082a7.png)

Suggested: provided an easier way to reorder options e.g., drad-and-drop or up/down arrows

Notes: The same mechanism could be useful in several other question types, and even in the submission page (for 'ranking' type questions)

**Comment by dhanu10896** [comment]
Can I take this issue,? I have done the setup yesterday so this can be my first issue.
but can take little time as I don't know about workflows in the application.

**Comment by mg14777** [comment]
I was researching a bit and thought if allowing users to reorder options by specifying explicit ranks would be appropriate. We could add it as an additional feature apart from drag and drop since drag and drop can become annoying when the number of items is huge. Besides, this approach also takes accessibility into account, for eg. when users prefer to only use their keyboards. 
Netflix uses this approach in addition to drag and drop. Users can directly specify the list order:
![image](https://user-images.githubusercontent.com/11634699/41154849-707c3cc8-6b13-11e8-86c1-9911fbec50da.png)

**Comment by dalessr** [comment]
@damithc Actually for MCQ/MSQ questions, do we really need a radio button before each option since it is disabled all the time?

**Comment by damithc** [comment]
> @damithc Actually for MCQ/MSQ questions, do we really need a radio button before each option since it is disabled all the time?

It's visual reminder that we are dealing with radio buttons (and not check boxes). Good to have I guess.

**Comment by damithc** [comment]
> I was researching a bit and thought if allowing users to reorder options by specifying explicit ranks would be appropriate. We could add it as an additional feature apart from drag and drop since drag and drop can become annoying when the number of items is huge. Besides, this approach also takes accessibility into account, for eg. when users prefer to only use their keyboards.

Sorry I missed this comment earlier. That's a good point @mg14777 especially about the accessibility.
I would hesitates to add it here though, as it complicates the UI (the options themselves might be numbers) and the list is not meant to be long, unlike a netflix playlist.
