### ISSUE TITLE
EmailGeneratorTest failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8908]
v6.6.0

Some of the EmailGeneratorTest tests are failing on live server e.g, EmailGeneratorTest.testGenerateInstructorJoinEmail
![image](https://user-images.githubusercontent.com/1673303/41573532-b5893e98-73af-11e8-951c-d18ab56ee1a6.png)

All due to a cause similar to this one:
![image](https://user-images.githubusercontent.com/1673303/41573485-86edebf6-73af-11e8-9748-4d835962e918.png)

**Comment by tshradheya** [comment]
I think I know the problem. Working on it

**Comment by damithc** [comment]
AdminHomeUiTest too is failing in a similar manner, although the situation seems to be reversed (or possibly expected and actual is used in the wrong way around in the test)
![image](https://user-images.githubusercontent.com/1673303/41574587-ec98f366-73b3-11e8-8bfc-890140072943.png)

**Comment by tshradheya** [comment]
Figured out the `http` and `https` problem and solved it.

With respect to `AdminHomeUiTest`, I am not sure why is there a difference of one being `6-6-0...` and `teammatesv4...` . 
When testing on live server, what link must be put in `test.properties` ? `6-6-0-dot...` or `teammates-sh....` ?

**Comment by damithc** [comment]
Live server has multiple versions running on it. The _default_ version doesn't require the version number in front i.e., https://teammates.... Live testing is done _before_ setting the new version as default, which means all live testing use the version number in front. However, this problem cropped up at v6.6.0, which means it's related to something that changed since v6.5.0, on our side or on GAE side. Was there any recent PRs that touched this part of the code?

**Comment by tshradheya** [comment]
#8801 changed the way we retrieve the `APP_URL`, it has caused the issue to come in.

**Comment by damithc** [comment]
We can drop the version-number-part when using it for actual-expected comparisons.

**Comment by xpdavid** [comment]
@damithc @tshradheya Actually, I was wondering why 6.5.0 `AdminHomeUiTest` and `EmailGeneratorTest` get passed

- For `EmailGeneratorTest`, #8902 won't affect it but #8801 should make it failed in 6.5.0

- For `AdminHomeUiTest`, 6.5.0's `com.google.appengine.runtime.default_version_hostname` is not properly set and will result in exception (more detail in #8902).

**Comment by tshradheya** [comment]
@xpdavid 
- The `isDevServer()` function wasnt working properly before also because we never set the System Property's env, but since the function was never used before, we never faced an issue. Now that `readAppUrl()` uses it, it gave http for Production server hence causing EmailGeneratorTest to fail. #8801 was part of 6.6.0 and that's why 6.5.0 always passed cause the url was taken from build.properties before.

- com.google.appengine.runtime.default_version_hostname was only introduced in 6.6.0, so that's why 6.5.0 always passed cause APP_URL wad initialised from huild properties and it didn't have to check any server environment

**Comment by xpdavid** [comment]
> it gave http for Production server

Not really correct. For production server, it indeed gives `https`. However, when you change the url to something start with `https` (yes, `https://localhost` would work) -> Fail

Huge release in 6.6.0 makes me forget #8801 belongs to 6.6.0.

**Comment by LiHaoTan** [comment]
To further add on to what @xpu said, I guess the confusion comes from when `isDevServer()` can be used. 

`isDevServer()` only works in the server instance, because App Engine will accordingly set `SystemProperty.environment`

 The problem is when we try to call it using our test runner it won't actually read the correct value because `SystemProperty.environment` is only set in the server instance and our test runner has no access to that.

If we set `SystemProperty.environment` I think this might add more confusion when someone reads the code `isDevServer()` and it automagically works even when we run it from the test runner.
