### ISSUE TITLE
Instructor Home Page: Hide options for instructors without corresponding privileges

### ISSUE THREAD

**Issue by joanneong** [TEAMMATES/teammates#8962]
- **Environment**: master branch at commit 0546019

**Description of feature/enhancement**
There are instructors who do not have the privilege to delete courses. In such cases, the `Delete` button is disabled in the `Home` and `Courses` tab. However, in the home page, such an instructor can still access the `Delete` function from the collapsible panel:

![image](https://user-images.githubusercontent.com/24493463/42735217-c41841ce-8882-11e8-9899-730277277017.png)

even if pressing on it will lead to an error page. 

**Justification**
By removing the `Delete` option from the collapsible panel for instructors without sufficient privileges:
- instructors will not mistakenly think that they can actually delete the course
- instructors will not be redirected unnecessarily to the error page
- the inability to delete without sufficient privilege is more consistent across all TEAMMATES tab

EDIT: Similarly for `Enroll Students` and `Add session` button

**Comment by dalessr** [comment]
@joanneong Actually the expected behavior in the current code (`InstructorHomeCourseAjaxPageData.java`) is that, if an instructor is not allowed to delete a course, then the `delete` button will be disabled. But it seems that this feature does not work correctly since the button is not disabled. Thus, I suspect that we can only disable a button, but cannot disable the nested buttons inside it. Same issue with Enroll (student), Add (session), and Download (Results) button.

**Comment by tshradheya** [comment]
> Thus, I suspect that we can only disable a button, but cannot disable the nested buttons inside it.

Its not a button but `<a>` tag and it is possible to [disable](https://stackoverflow.com/questions/13955667/disabled-href-tag) it.

However, it is always better to remove it as disabling <a> tag doesnt look neat as disabling a button does
