### ISSUE TITLE
Instructor: non-standard times shown for session start/end times

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9168]
v6.12.1
See the screenshot below from a user's home page. How come `x.59` shown as start/end times?

![image](https://user-images.githubusercontent.com/1673303/46355685-e5a3a780-c693-11e8-8eb5-a33aab07d92c.png)

**Comment by xpdavid** [comment]
Our sample data actual sets `x.59`?

![image](https://user-images.githubusercontent.com/13977235/46356610-ad04cd80-c695-11e8-8ebd-dd5f40876d75.png)

**Comment by damithc** [comment]
Oh, didn't realize it before. That shouldn't be the case though. :-p

**Comment by xpdavid** [comment]
> That shouldn't be the case though.

What should be the expected value/behaviour?

**Comment by wkurniawan07** [comment]
This issue, I believe, is due to the special treatment of `00:00` (or `24:00` or `12:00am` depending on how you interpret it), with the intention of displaying it as `23:59` (or `11:59pm`) but inadvertently causing incorrect data to be persisted to the database due to some wrong logic (including improperly set test data) or otherwise.

@xpdavid we'll handle this in V7. All closing times should be in `*:00` format in data form, and we shall use Angular pipe for the purpose of display.

**Comment by damithc** [comment]
So, are we going to show `0000` or `2359` to the user? 0000 can be used in the database but it's good if it can be shown as 2359 to the user.

**Comment by wkurniawan07** [comment]
The problem is, DB has already been muddled with `2359` data from V6 and before.

**Comment by wkurniawan07** [comment]
@damithc new version that fixed one half of the problem is up, along with script to be run `DataMigrationForFeedbackSessionMismatchedTimezone`.

**Comment by damithc** [comment]
@wkurniawan07 I've deployed v8.1.1 
Should I run the migration script now?

**Comment by wkurniawan07** [comment]
> Should I run the migration script now?

The sooner the better. Although there shouldn't be sessions affected other than demo sessions.

**Comment by damithc** [comment]
@wkurniawan07 Migration completed.
