### ISSUE TITLE
Student: submit response to distribute-points question: all responses are rejected 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#9198]
6.13.0
Reported by a user.
This question is rejecting (upon submission) all answers, even answers that pass the client-side validation

![image](https://user-images.githubusercontent.com/1673303/47082243-8ae77f80-d23f-11e8-9cbe-5a1fa6456e40.png)

**Comment by xpdavid** [comment]
@mg14777 FYI. Meanwhile, I'll investigate also.

**Comment by xpdavid** [comment]
Bug Found. Bug exists since V6.6.0, not specific to V6.13.0

https://github.com/TEAMMATES/teammates/blob/42f046a3a8f13bcfd9eea73e6182a69f8fa037d4/src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java#L789-L804

For distribute point to recipient question type, the answer list only contains one option (and the above check will add errors).

Since the session is opening, a quick fix for this is to ask the instructor to remove the constraint. 

Meanwhile, @joanneong do you have time to fix this since you are working on the feature?

**Comment by joanneong** [comment]
I'm nearly done with #9103 but let me just get this out first then.
