### ISSUE TITLE
No proper checks on email while adding an instructor to a course

### ISSUE THREAD

**Issue by crownedlake** [TEAMMATES/teammates#9474]
**Email address added is not being checked on front-end while adding an instructor to a course**

 **Environment**: 
commit sha: 9e3b496dec9462f498d38159860a51ed602cf9e6
OS: Ubuntu 18.04 lts

**Steps to reproduce** 

1. Login and add any course
2. Add instructor by providing the name, email and university.

**Expected behaviour**
Email validation should be done on front-end. If I provide a broken email like test@example, A promt message should be shown to correct my details on front-end

**Actual behaviour**
The email has been saved for further actions.
![screenshot from 2019-02-20 14-20-18](https://user-images.githubusercontent.com/16207718/53078933-4b95ac00-351b-11e9-864d-731a0ad8be60.png)

**Additional info**

I am not sure if this the decided workflow but it might lead to some extra work by the server.

**Comment by wkurniawan07** [comment]
@crownedlake Validation in the back-end is unavoidable (any tech-savvy user can disable any front-end validation). Validation in the front-end is just a bonus and should be done only if it smoothens user flow. What is the problem here?

**Comment by crownedlake** [comment]
Yes I agree it is unavoidable but checking it on front smoothens the user flow and any such situation where a user doesn't enter her email properly will be handled with more ease.

And why are we thinking that a user might or might want to disable the front-end validation? Having both front and back validation is required. But currently there is no such validation on front. 

What do you think? @wkurniawan07

**Comment by wkurniawan07** [comment]
> why are we thinking that a user might or might want to disable the front-end validation?

You can never know anyone's evil intention.

Also you have not answered the question: which validation is missing, front-end, back-end, or both?

**Comment by crownedlake** [comment]
@wkurniawan07 the **front-end validation is definitely missing**, I am not sure about the back-end validation. The system accepts my broken email address and what is it doing after that is still unknown to me.
If required I can look up in depth of the code.
I am new to Teammates and hence the code structure is still very new to me.

**Comment by tanhengyeow** [comment]
I helped to check and the backend persists this type of email: `test@exam`, which I believe shouldn't be allowed.

Changes allowed:
![image](https://user-images.githubusercontent.com/25320782/53090537-b3172000-354a-11e9-8a63-a8425d098a98.png)

Changes persisted:
![image](https://user-images.githubusercontent.com/25320782/53090569-d215b200-354a-11e9-9f43-5b551d2f17d4.png)

@crownedlake Front-end validation is a plus and would be ideal, but not **absolutely necessary**. 
This is because:
`There are definitely ways to bypass any type of front-end validation (subjected to one's knowledge) as the user has control over the client-side.`

However, back-end validation is **definitely necessary** as the back-end server has control over all requests/data sent and thus can properly do validation (something we cannot do in the front-end due to the point highlighted above).

Also there is an [issue](https://github.com/TEAMMATES/teammates/issues/9419) raised to explore form validation (I'll probably do it) which addresses the point you are trying to bring across.

**Comment by crownedlake** [comment]
@tanhengyeow Yes, I checked the [issue](https://github.com/TEAMMATES/teammates/issues/9419) and that feels more accurate.
