### ISSUE TITLE
Text box formatter in sessions edit page is stuck at the top of the page

### ISSUE THREAD

**Issue by monmanuela** [TEAMMATES/teammates#9665]
**Environment**: `master` branch at commit e360fc0

**Steps to reproduce**
1. Go to instructor sessions page
2. Click `Edit` on one of the feedback session
3. Click the top `Edit` button
4. Click inside the `Instructions` box
5. Scroll down, and the text box formatter stays at the top of the page

![image](https://user-images.githubusercontent.com/35655790/55965436-2ca8d000-5ca9-11e9-9b4c-8d911cd13bc1.png)

**Expected behaviour**
Text box formatter should disappear as the user scrolls down

**Actual behaviour**
Text box formatter is stuck at the top of the page

**Additional Info**
The bug only occurs when the `Instructions` text box is on focus. Clicking anywhere outside of the text box will make the text box formatter disappear.

**Comment by tanhengyeow** [comment]
One possible solution is to remove focus from the text box if it is out of the viewport.

**Comment by aishaadambek** [comment]
Hi @monmanuela,

unfortunately, with the steps you specified, the bug is not reproducible anymore. Text box formatter disappears as the user scrolls down:

![teammates](https://user-images.githubusercontent.com/29358225/74527908-1e72b280-4f51-11ea-9c37-a40291fbccac.gif)

I suspect that the bug has been fixed already.
Maybe alternative steps are needed to reproduce the bug? Otherwise, it probably makes sense to close the issue.

Thanks! :)
