### ISSUE TITLE
Auto-sync API output type: ConfirmationResponse

### ISSUE THREAD

**Issue by xpdavid** [TEAMMATES/teammates#9911]
There is a `ConfirmationResponse` in the backend (JAVA) and `ConfirmationResponse` and in the frontend (TypeScript). They have the same structure and we should make use of the `./gradlew generateTypes` to auto-sync them.

**Comment by madanalogy** [comment]
I would like to work on this, but I'm not sure how to go about implementing the class pattern in `build.gradle` because `ConfirmationResponse` is a static class declared within the `ConfirmFeedbackSessionSubmissionAction` class, so there is no class file I can point the generator to? Do I have to first extract these declarations into their own java file?

Unless I'm going about this the wrong way, any insight would be appreciated!

**Comment by xpdavid** [comment]
> Do I have to first extract these declarations into their own java file?

Yup, and put it into `src/main/java/teammates/ui/webapi/output`. When you run `./gradlew generateTypes` you will get auto-synced TypeScript interface in `api-output.ts`.

**Comment by madanalogy** [comment]
Understood, I will work on this issue and raise a PR in a couple of days, thanks!
